<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Harmonogram {{ $project->number }} — {{ $project->name }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/frappe-gantt@0.6.0/dist/frappe-gantt.css">
    <style>
        :root{--brand:{{ $appBrand?->primaryColor() ?? '#1A4D3A' }}}*{box-sizing:border-box}body{margin:0;background:#f4f5f1;color:#26332b;font-family:Inter,Arial,sans-serif}.wrap{max-width:1500px;margin:auto;padding:24px}.head{display:flex;justify-content:space-between;align-items:center;gap:20px;background:#fff;border:1px solid #e1e3dc;border-radius:13px;padding:18px 20px;margin-bottom:16px}.brand{display:flex;align-items:center;gap:12px}.brand img{width:50px;height:50px;object-fit:contain}.kicker{font-size:11px;font-weight:800;color:var(--brand);letter-spacing:.08em}.head h1{font-size:22px;margin:4px 0}.head p{margin:0;color:#6b766e;font-size:13px}.readonly{padding:7px 11px;background:#eef4ef;color:var(--brand);border-radius:999px;font-size:11px;font-weight:800}.card{background:#fff;border:1px solid #e1e3dc;border-radius:13px;padding:18px}.tools{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin-bottom:12px}.tools button{border:1px solid #d8dcd5;background:#fff;border-radius:7px;padding:7px 11px;font-weight:700;cursor:pointer}.tools button.active{background:var(--brand);border-color:var(--brand);color:#fff}.legend{margin-left:auto;font-size:12px;color:#657168}.dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin:0 5px 0 12px}.chart{min-height:300px;overflow-x:auto;border:1px solid #e4e6df;border-radius:9px}.chart .gantt-container{overflow:visible}.chart svg{min-width:100%;pointer-events:none}.chart .bar-wrapper.project-range-row .bar{fill:#cbd5e1}.chart .bar-wrapper.project-range-row .bar-progress{fill:#64748b}.chart .bar-wrapper.task-row .bar{fill:#8b5cf6}.chart .bar-wrapper.task-row .bar-progress{fill:#6d28d9}.chart .bar-wrapper.milestone-row .bar{fill:#f59e0b;stroke:#b45309;stroke-width:1;transform:rotate(45deg) scale(.72);transform-box:fill-box;transform-origin:center;rx:0;ry:0}.chart .bar-wrapper.milestone-row .bar-progress,.chart .bar-wrapper.milestone-row .handle{display:none}.project-date-marker line{stroke-width:2}.project-date-marker.today line{stroke:#ef4444;stroke-dasharray:5 4}.project-date-marker.deadline line{stroke:#111827;stroke-dasharray:8 4}.project-date-marker text{font-size:10px;font-weight:800;paint-order:stroke;stroke:#fff;stroke-width:3px}.project-date-marker.today text{fill:#dc2626}.project-date-marker.deadline text{fill:#111827}.empty{padding:60px;text-align:center;color:#777}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{text-align:left;padding:10px;border-bottom:1px solid #eee;font-size:12px}th{font-size:10px;text-transform:uppercase;color:#758078;background:#fafaf7}@media(max-width:700px){.wrap{padding:10px}.head{align-items:flex-start}.readonly{display:none}.legend{width:100%;margin-left:0}}
    </style>
</head>
<body>
<main class="wrap">
    <header class="head"><div class="brand"><img src="{{ $appBrand?->logoUrl() ?? asset('Logo2.png') }}" alt="Logo"><div><div class="kicker">{{ $project->number }}</div><h1>{{ $project->name }}</h1><p>Publiczny harmonogram projektu · aktualizacja {{ now()->format('d.m.Y H:i') }}</p></div></div><span class="readonly">Tylko podgląd</span></header>
    <section class="card">
        <div class="tools"><strong>Widok:</strong>@foreach(['Day'=>'Dzień','Week'=>'Tydzień','Month'=>'Miesiąc'] as $mode=>$label)<button class="mode {{$mode==='Week'?'active':''}}" data-mode="{{$mode}}">{{$label}}</button>@endforeach<span class="legend"><i class="dot" style="background:#8b5cf6"></i>Zadania <i class="dot" style="background:#f59e0b;transform:rotate(45deg);border-radius:1px"></i>Kamienie milowe · linie pokazują dziś i koniec projektu</span></div>
        @if($timelineItems->isEmpty())<div class="empty">Harmonogram nie zawiera jeszcze zadań.</div>@else<div id="public-gantt" class="chart"></div>
        <div style="overflow-x:auto"><table><thead><tr><th>Pozycja</th><th>Osoba</th><th>Zależne od</th><th>Termin</th><th>Postęp</th></tr></thead><tbody>@foreach($timelineItems as $item)<tr><td><strong>{{$item['name']}}</strong><br><small>{{$item['is_milestone']?'Kamień milowy — etap':'Zadanie'}}</small></td><td>{{$item['assignee']??'—'}}</td><td>{{$item['dependencies']?($timelineItems->firstWhere('id',$item['dependencies'])['name']??'—'):'—'}}</td><td>{{\Carbon\Carbon::parse($item['start'])->format('d.m.Y')}}@if(!$item['is_milestone']) – {{\Carbon\Carbon::parse($item['end'])->format('d.m.Y')}}@endif</td><td>{{$item['progress']}}%</td></tr>@endforeach</tbody></table></div>@endif
    </section>
</main>
<script src="https://cdn.jsdelivr.net/npm/frappe-gantt@0.6.0/dist/frappe-gantt.min.js"></script>
<script>
const items=@json($timelineItems),projectStartDate=@json($project->start_date?->format('Y-m-d')),projectEndDate=@json($project->end_date?->format('Y-m-d'));let gantt=null;
function markerX(date,kind){const svg=document.querySelector('#public-gantt svg.gantt');if(!svg||!gantt)return null;if(kind==='today'){const highlight=svg.querySelector('.today-highlight');if(highlight)return Number(highlight.getAttribute('x'))+Number(highlight.getAttribute('width')||0)/2;}return ((new Date(date+'T00:00:00')-new Date(gantt.gantt_start))/3600000/Number(gantt.options?.step||24))*Number(gantt.options?.column_width||38);}
function markers(){const svg=document.querySelector('#public-gantt svg.gantt');if(!svg||!gantt)return;svg.querySelectorAll('.project-date-marker').forEach(item=>item.remove());const bg=svg.querySelector('.grid-background'),width=Number(bg?.getAttribute('width')||svg.getAttribute('width')||0),height=Number(bg?.getAttribute('height')||svg.getAttribute('height')||0),today=new Date(),todayDate=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-'),data=[['today',todayDate,'Dzisiaj',16]];if(projectEndDate)data.push(['deadline',projectEndDate,'Koniec projektu',29]);data.forEach(([kind,date,text,y])=>{const x=markerX(date,kind);if(x===null||x<0||x>width)return;const group=document.createElementNS('http://www.w3.org/2000/svg','g'),line=document.createElementNS('http://www.w3.org/2000/svg','line'),label=document.createElementNS('http://www.w3.org/2000/svg','text');group.setAttribute('class','project-date-marker '+kind);line.setAttribute('x1',x);line.setAttribute('x2',x);line.setAttribute('y1',0);line.setAttribute('y2',height);label.setAttribute('x',x+4);label.setAttribute('y',y);label.textContent=text;group.append(line,label);svg.appendChild(group);});}
function render(mode='Week'){if(!document.getElementById('public-gantt')||typeof Gantt==='undefined')return;document.getElementById('public-gantt').innerHTML='';const tasks=items.map(item=>({id:item.id,name:item.assignee?item.name+' · '+item.assignee:item.name,start:item.start,end:item.end,progress:item.progress,dependencies:item.dependencies||'',custom_class:item.is_milestone?'milestone-row':'task-row'}));if(projectEndDate){const rangeStart=projectStartDate||items.map(item=>item.start).sort()[0]||projectEndDate,total=Math.max(1,new Date(projectEndDate+'T00:00:00')-new Date(rangeStart+'T00:00:00')),elapsed=Math.max(0,Math.min(100,Math.round((new Date()-new Date(rangeStart+'T00:00:00'))/total*100)));tasks.unshift({id:'project-range',name:'Okres projektu',start:rangeStart,end:projectEndDate,progress:elapsed,dependencies:'',custom_class:'project-range-row'});}gantt=new Gantt('#public-gantt',tasks,{view_mode:mode,language:'en',readonly:true,on_view_change:()=>setTimeout(markers,0)});setTimeout(markers,30);}
render();document.querySelectorAll('.mode').forEach(button=>button.addEventListener('click',()=>{render(button.dataset.mode);document.querySelectorAll('.mode').forEach(item=>item.classList.toggle('active',item===button));}));
</script>
</body>
</html>
