@extends('layouts.app')

@section('page-title', $passport->name)

@push('styles')
<style>
.pe-back{display:inline-flex;gap:6px;color:var(--green);text-decoration:none;font-size:13px;font-weight:700;margin-bottom:16px}.pe-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.pe-title{font-size:22px;font-weight:750}.pe-sub{font-size:12px;color:#748179;margin-top:4px}.pe-btn{border:0;border-radius:8px;padding:10px 16px;background:var(--green);color:#fff;font:650 13px Manrope;cursor:pointer}.pe-alert{padding:11px 14px;border-radius:8px;background:#e9f7ee;border:1px solid #bae0c8;color:#176239;margin-bottom:15px}.pe-card{background:#fff;border:1px solid #e2ded5;border-radius:13px;margin-bottom:17px;overflow:hidden}.pe-card-head{padding:15px 18px;border-bottom:1px solid #eeeae2;font-weight:700}.pe-body{padding:18px}.pe-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.pe-field{display:flex;flex-direction:column;gap:6px}.pe-field.wide{grid-column:span 2}.pe-field.full{grid-column:1/-1}.pe-field label{font-size:10px;text-transform:uppercase;color:#647068;font-weight:700}.pe-input{border:1px solid #d8d3ca;border-radius:8px;padding:9px 11px;font:13px Manrope;background:#fff;min-width:0}.pe-input:disabled{background:#f5f4f0;color:#646b67}.pe-tabs{display:flex;overflow-x:auto;border-bottom:1px solid #e7e3dc;background:#faf9f5}.pe-tab{padding:13px 17px;border:0;background:transparent;white-space:nowrap;font:650 12px Manrope;color:#718078;cursor:pointer}.pe-tab.active{color:var(--green);background:#fff;border-bottom:2px solid var(--green)}.pe-stage{display:none;padding:18px}.pe-stage.active{display:block}.pe-section{border:1px solid #e6e2da;border-radius:10px;overflow:hidden;margin-bottom:14px}.pe-section h3{background:#f6f4ee;padding:11px 14px;font-size:12px;color:#365144}.pe-question{display:grid;grid-template-columns:70px minmax(250px,1.5fr) minmax(220px,1fr);gap:12px;padding:13px 14px;border-top:1px solid #f0ede7;align-items:start}.pe-question:first-of-type{border-top:0}.pe-code{font:700 11px monospace;color:var(--green);background:#eaf4ef;border-radius:5px;padding:5px;text-align:center}.pe-qtext{font-size:13px;white-space:pre-line;line-height:1.45}.pe-unit{font-size:10px;color:#7c8881;margin-top:5px}.pe-answer textarea{width:100%;min-height:68px;resize:vertical}.pe-hint{font-size:10px;color:#7a867f;white-space:pre-line;line-height:1.4;margin-top:5px}.pe-footer{position:sticky;bottom:0;background:rgba(255,255,255,.96);border-top:1px solid #e1ddd4;padding:12px 18px;display:flex;justify-content:flex-end}.pe-empty{text-align:center;padding:35px;color:#748179}.pe-progress{height:6px;background:#e8e6df;border-radius:8px;overflow:hidden;margin-top:9px}.pe-progress span{display:block;height:100%;background:#4ca66b}@media(max-width:1000px){.pe-grid{grid-template-columns:1fr 1fr}.pe-question{grid-template-columns:60px 1fr}.pe-answer{grid-column:1/-1}}@media(max-width:600px){.pe-grid{grid-template-columns:1fr}.pe-field.wide{grid-column:auto}.pe-head{flex-direction:column}}
</style>
@endpush

@section('content')
@php
$stages=$passport->template?->sections ?? [];$responses=$passport->responses ?? [];
$questions=collect($stages)->flatMap(fn($stage)=>collect($stage['sections']??[])->flatMap(fn($section)=>$section['questions']??[]));
$answered=$questions->filter(fn($question)=>filled($responses[$question['key']]??null))->count();$percent=$questions->count()?round($answered/$questions->count()*100):0;
@endphp
<a class="pe-back" href="{{route('energy-passports.index')}}"><i class="ti ti-arrow-left"></i> Wróć do paszportów</a>
<div class="pe-head"><div><div class="pe-title">{{$passport->name}}</div><div class="pe-sub">{{$passport->template?->name ?? 'Paszport własny'}} @if($passport->company) · {{$passport->company->name}} @endif</div><div class="pe-progress" title="Uzupełniono {{$percent}}%"><span style="width:{{$percent}}%"></span></div></div>@if($canManage)<button class="pe-btn" type="submit" form="passport-form"><i class="ti ti-device-floppy"></i> Zapisz zmiany</button>@endif</div>
@if(session('success'))<div class="pe-alert"><i class="ti ti-circle-check"></i> {{session('success')}}</div>@endif
@if($errors->any())<div class="pe-alert" style="background:#fff0f0;color:#982020;border-color:#efc4c4">{{$errors->first()}}</div>@endif

<form id="passport-form" method="POST" action="{{route('energy-passports.update',$passport)}}">@csrf @method('PUT')
<section class="pe-card"><div class="pe-card-head">Dane identyfikacyjne</div><div class="pe-body"><div class="pe-grid">
<div class="pe-field wide"><label>Nazwa paszportu</label><input class="pe-input" name="name" value="{{old('name',$passport->name)}}" required @disabled(!$canManage)></div><div class="pe-field"><label>Firma</label><select class="pe-input" name="company_id" @disabled(!$canManage)><option value="">Nie przypisano</option>@foreach($companies as $company)<option value="{{$company->id}}" @selected(old('company_id',$passport->company_id)==$company->id)>{{$company->name}}</option>@endforeach</select></div><div class="pe-field"><label>Status</label><select class="pe-input" name="status" @disabled(!$canManage)>@foreach(['draft'=>'Roboczy','in_progress'=>'W trakcie','complete'=>'Kompletny','archived'=>'Archiwalny'] as $value=>$label)<option value="{{$value}}" @selected(old('status',$passport->status)===$value)>{{$label}}</option>@endforeach</select></div>
<div class="pe-field wide"><label>ID / kod urządzenia</label><input class="pe-input" name="asset_identifier" value="{{old('asset_identifier',$passport->asset_identifier)}}" @disabled(!$canManage)></div><div class="pe-field wide"><label>Lokalizacja</label><input class="pe-input" name="location" value="{{old('location',$passport->location)}}" @disabled(!$canManage)></div><div class="pe-field full"><label>Notatki</label><textarea class="pe-input" name="notes" @disabled(!$canManage)>{{old('notes',$passport->notes)}}</textarea></div>
</div></div></section>

<section class="pe-card"><div class="pe-card-head">Dane techniczne <span class="pe-sub" style="font-weight:400">· {{$answered}} z {{$questions->count()}} odpowiedzi</span></div>
@if($stages!==[])<div class="pe-tabs">@foreach($stages as $index=>$stage)<button type="button" class="pe-tab {{$index===0?'active':''}}" onclick="showStage({{$index}},this)">{{Str::of($stage['name']??('Etap '.($index+1)))->replace('_',' ')}}</button>@endforeach</div>
@foreach($stages as $index=>$stage)<div class="pe-stage {{$index===0?'active':''}}" data-stage="{{$index}}">@foreach($stage['sections']??[] as $section)<div class="pe-section"><h3>{{$section['title']}}</h3>@foreach($section['questions']??[] as $question)<div class="pe-question"><div class="pe-code">{{$question['code']}}</div><div><div class="pe-qtext">{{$question['question']}}</div>@if(filled($question['unit']??null))<div class="pe-unit">Jednostka: {{$question['unit']}}</div>@endif</div><div class="pe-answer"><textarea class="pe-input" name="responses[{{$question['key']}}]" @disabled(!$canManage)>{{old('responses.'.$question['key'],$responses[$question['key']]??'')}}</textarea>@if(filled($question['hint']??null))<div class="pe-hint"><strong>Wskazówka:</strong> {{$question['hint']}}</div>@endif</div></div>@endforeach</div>@endforeach</div>@endforeach
@else<div class="pe-empty"><i class="ti ti-notes" style="font-size:38px;color:var(--green)"></i><p>To paszport własny bez formularza technicznego. Możesz prowadzić jego dane identyfikacyjne i notatki albo utworzyć nowy paszport na podstawie szablonu XLSX.</p></div>@endif
@if($canManage)<div class="pe-footer"><button class="pe-btn"><i class="ti ti-device-floppy"></i> Zapisz wszystkie odpowiedzi</button></div>@endif</section>
</form>
@endsection

@push('scripts')
<script>function showStage(index,button){document.querySelectorAll('.pe-stage').forEach(stage=>stage.classList.toggle('active',Number(stage.dataset.stage)===index));document.querySelectorAll('.pe-tab').forEach(tab=>tab.classList.remove('active'));button.classList.add('active')}</script>
@endpush
