<!doctype html><html lang="pl"><head><meta charset="utf-8"><style>
@page{margin:32px 38px 45px}body{font-family:DejaVu Sans,sans-serif;font-size:10px;color:#23332e;line-height:1.45}h1{font-size:20px;margin:24px 0 6px}h2{font-size:12px;color:{{$protocol->issuer_snapshot['color']}};margin:19px 0 7px}.header{width:100%;border-bottom:3px solid {{$protocol->issuer_snapshot['color']}};padding-bottom:12px}.header img{max-width:145px;max-height:65px}.right{text-align:right}.muted{color:#6c7871;font-size:9px}.parties{width:100%;margin:18px 0;background:#f6f7f5}.parties td{width:50%;padding:12px;vertical-align:top}.items{width:100%;border-collapse:collapse;table-layout:fixed}.items th{background:{{$protocol->issuer_snapshot['color']}};color:white;font-size:9px;text-align:left}.items td,.items th{padding:7px;border-bottom:1px solid #dde3de;word-wrap:break-word}.items tr{page-break-inside:avoid}.box{border:1px solid #dde3de;padding:12px;margin-top:12px}.signatures{width:100%;margin-top:26px;page-break-inside:avoid}.signatures td{width:50%;vertical-align:bottom;text-align:center;padding:8px}.signature-space{height:60px}.signature-space img{max-width:160px;max-height:55px}.signature-line{border-top:1px solid #839189;padding-top:7px}.text{white-space:pre-wrap;word-wrap:break-word}.footer{position:fixed;bottom:-25px;font-size:8px;color:#77847c}.totals{text-align:right;padding:12px;background:#f6f7f5}.page:after{content:counter(page)}
</style><style>h1{margin:14px 0 5px}h2{margin:12px 0 5px}.header{padding-bottom:8px}.parties{margin:12px 0}.parties td{padding:9px}.box{padding:9px;margin-top:9px}.totals{padding:8px}.signatures{margin-top:14px}.signature-space{height:45px}</style></head><body>
<table class="header"><tr><td>@if($protocol->issuer_snapshot['logo'] ?? null)<img src="{{$protocol->issuer_snapshot['logo']}}" alt="Logo">@else<strong>{{$protocol->issuer_snapshot['name']}}</strong>@endif</td><td class="right"><strong>{{$protocol->number}}</strong><br>Data odbioru: {{$protocol->acceptance_date->format('d.m.Y')}}<br><span class="muted">Wersja {{$protocol->revision}}</span></td></tr></table>
<h1>Protokół odbioru</h1><div>{{\App\Models\ProjectProtocol::KINDS[$protocol->kind]}} · {{$protocol->place ?: 'Miejsce: nie wskazano'}}</div>
<table class="parties"><tr><td><div class="muted">ODBIERAJĄCY</div><strong>{{$protocol->issuer_snapshot['name']}}</strong><br>{{$protocol->issuer_snapshot['address']}}<br>{{$protocol->issuer_snapshot['postcode'] ?? ''}} {{$protocol->issuer_snapshot['city']}}<br>NIP: {{$protocol->issuer_snapshot['nip'] ?: '—'}}</td><td><div class="muted">DOSTAWCA / WYKONAWCA</div><strong>{{$protocol->supplier_snapshot['name']}}</strong><br>{{$protocol->supplier_snapshot['address']}}<br>{{$protocol->supplier_snapshot['city']}}<br>NIP: {{$protocol->supplier_snapshot['nip'] ?: '—'}}</td></tr></table>
<strong>Projekt:</strong> {{$protocol->issuer_snapshot['project_number']}} · {{$protocol->issuer_snapshot['project_name']}}<br><strong>Zamówienie / umowa:</strong> {{$protocol->reference ?: 'Nie wskazano'}}
<h2>Przedmiot i zakres odbioru</h2><div class="text">{{$protocol->description}}</div>
<h2>Zestawienie odebranych pozycji (PLN)</h2>
<table class="items"><thead><tr><th style="width:32%">Nazwa / opis</th><th style="width:10%">Ilość</th><th style="width:8%">J.m.</th><th style="width:17%">Cena netto</th><th style="width:8%">VAT</th><th style="width:25%">Wartość netto</th></tr></thead><tbody>@foreach($protocol->items as $item)<tr><td>{{$item['name']}}</td><td>{{number_format((float)$item['quantity'],2,',',' ')}}</td><td>{{$item['unit']}}</td><td>{{number_format((float)$item['price'],2,',',' ')}}</td><td>{{$item['vat']}}{{is_numeric($item['vat'])?'%':''}}</td><td>{{number_format($item['net_cents']/100,2,',',' ')}}</td></tr>@endforeach</tbody></table>
<div class="totals">Netto: <strong>{{number_format($protocol->totals()['net']/100,2,',',' ')}} zł</strong> &nbsp; VAT: {{number_format($protocol->totals()['vat']/100,2,',',' ')}} zł<br>Brutto: <strong>{{number_format($protocol->totals()['gross']/100,2,',',' ')}} zł</strong></div>
<div class="box"><strong>Wynik odbioru:</strong> {{\App\Models\ProjectProtocol::OUTCOMES[$protocol->outcome]}}<br><strong>Fakturowanie:</strong> {{\App\Models\ProjectProtocol::INVOICES[$protocol->invoice_decision]}}<br><span class="muted">Decyzja dotyczy pozycji i kwot ujętych w tym protokole.</span></div>
<h2>Uwagi i zastrzeżenia</h2><div class="text">{{$protocol->remarks ?: 'Brak uwag.'}}</div>@if($protocol->remedy_deadline)<p><strong>Termin usunięcia usterek:</strong> {{$protocol->remedy_deadline->format('d.m.Y')}}</p>@endif
@if($protocol->invoice_conditions)<h2>Warunki fakturowania i uzgodnienia</h2><div class="text">{{$protocol->invoice_conditions}}</div>@endif
@if($protocol->attachments)<h2>Wykaz załączników</h2><div class="text">{{$protocol->attachments}}</div>@endif
<table class="signatures"><tr><td><div class="signature-space">@if($protocol->signature_data)<img src="{{$protocol->signature_data}}" alt="Podpis odbierającego">@endif</div><div class="signature-line">{{$protocol->receiver_name}}<br><span class="muted">Odbierający - podpis i data</span></div></td><td><div class="signature-space"></div><div class="signature-line">{{$protocol->supplier_representative}}<br><span class="muted">Dostawca / wykonawca - podpis i data</span></div></td></tr></table>
<div class="footer">{{$protocol->number}} · wersja {{$protocol->revision}} · {{$protocol->issuer_snapshot['name']}} · strona <span class="page"></span></div>
</body></html>
