<!doctype html><html lang="pl"><head><meta charset="utf-8"><style>@page{margin:35px 40px 45px}body{font-family:DejaVu Sans,sans-serif;font-size:10px;color:#243a33;line-height:1.5}h1{font-size:22px;color:#1a4d3a}h2{font-size:14px;background:#edf3ef;padding:8px;page-break-after:avoid}h3{font-size:11px;page-break-after:avoid}p{white-space:pre-wrap}.header{border-bottom:3px solid #1a4d3a;padding-bottom:12px}.header img{max-height:55px;max-width:160px}.footer{position:fixed;bottom:-24px;font-size:8px}.page:after{content:counter(page)}.approval{padding:10px;border:1px solid #d9e4dc;margin:10px 0}</style></head><body>
<div class="footer">4.1 Czynniki kontekstowe · strona <span class="page"></span></div>
<div class="header">@if($review->issuer['logo']??null)<img src="{{$review->issuer['logo']}}" alt="Logo">@else<strong>{{$review->issuer['name']??''}}</strong>@endif<h1>4.1 Kontekst organizacji — czynniki</h1><strong>{{$profile->answers['organization.name']['value']??''}}</strong><p>{{$profile->answers['site.name']['value']??''}}<br>{{$profile->answers['site.address']['value']??''}}</p><p>Profil zakładu #{{$profile->id}} · Stan danych: {{$profile->as_of_date->format('d.m.Y')}}</p></div>
<h2>Ocena istotności zmiany klimatu</h2><p>{{$review->answers['FAKT_KLIMAT_ISTOTNY']==='tak'?'Istotna':'Nieistotna'}}. {{$review->answers['climate_reason']}}</p>
@php($factors=$questionnaire->factors($facts,$review->answers))
@foreach($questionnaire->schema()['sekcje'] as $section)<h2>{{$section['opis']}}</h2>@foreach($factors as $factor)@if($factor['wymiar']===$section['id'] && $factor['visible'] && ($factor['rodzaj']==='AUTO' || ($review->answers['factors'][$factor['kod']]['decyzja']??'')==='potwierdzony'))<h3>{{$factor['kod']}} · Wpływ: {{$factor['wplyw']}}</h3><p>{{$factor['rodzaj']==='AUTO'?$factor['tresc']:$review->answers['factors'][$factor['kod']]['tresc']}}</p><p>Skutek: {{$factor['skutek']}}</p>@endif @endforeach @endforeach
@if($review->answers['custom']??[])<h2>Własne czynniki</h2>@foreach($review->answers['custom'] as $row)<p>{{$row['tresc']}}<br>Wpływ: {{$row['wplyw']}}</p>@endforeach @endif
<h2>Czynniki odrzucone — uzasadnienia</h2>@foreach($factors as $factor)@if($factor['visible'] && ($review->answers['factors'][$factor['kod']]['decyzja']??'')==='odrzucony')<h3>{{$factor['kod']}}</h3><p>{{$review->answers['factors'][$factor['kod']]['powod']}}</p>@endif @endforeach
<h2>Brak danych do oceny warunków</h2>@foreach($factors as $factor)@if(!$factor['visible'] && in_array(null,$factor['dependencies'],true))<p>{{$factor['kod']}} · {{$factor['tresc']}}<br>Do uzupełnienia / weryfikacji: {{$factor['pokaz_gdy']}}</p>@endif @endforeach
<h2>Zatwierdzenia</h2>@foreach(['client_approval'=>'Klient','auditor_approval'=>'Audytor'] as $field=>$label)<div class="approval"><strong>{{$label}}</strong><br>{{$review->$field['name']}} · {{\Carbon\Carbon::parse($review->$field['at'])->format('d.m.Y H:i')}}</div>@endforeach<p>Wynik przeglądu: {{$review->review_note}}</p></body></html>
