@extends('layouts.app')
@section('page-title', 'ISO 50001')
@push('styles')
<style>
.iso-builder-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:20px}.iso-builder-head h1{margin:3px 0 6px;font-size:25px}.iso-kicker{font-size:11px;font-weight:900;color:var(--green);letter-spacing:.08em}.iso-builder-head p{margin:0;color:#69766e;font-size:13px}.iso-workspace{display:grid;grid-template-columns:minmax(0,1fr) 310px;gap:18px;align-items:start}.iso-content{background:#fff;border:1px solid #e5e1d8;border-radius:13px;padding:24px;min-height:520px}.iso-panel{display:none}.iso-panel.active{display:block}.iso-panel-number{font-size:12px;font-weight:900;color:var(--green)}.iso-panel h2{font-size:22px;margin:5px 0 8px}.iso-panel-lead{font-size:14px;color:#647169;line-height:1.65;max-width:850px}.iso-placeholder{margin-top:24px;border:1px dashed #cfd7d1;background:#fafbf8;border-radius:11px;padding:28px;text-align:center;color:#718078}.iso-placeholder i{font-size:30px;display:block;color:#a8b9af;margin-bottom:8px}.iso-nav{background:#fff;border:1px solid #e5e1d8;border-radius:13px;padding:11px;position:sticky;top:78px}.iso-nav-head{display:flex;align-items:center;gap:10px;padding:10px 9px 14px;border-bottom:1px solid #eee;margin-bottom:7px}.iso-nav-head>i{font-size:23px;color:var(--green)}.iso-nav-head div{display:flex;flex-direction:column}.iso-nav-head small{font-size:10px;color:#7a857e}.iso-nav-item{width:100%;border:0;background:transparent;border-radius:8px;padding:9px;display:grid;grid-template-columns:62px 1fr;gap:7px;text-align:left;align-items:start;font:700 11px Manrope;color:#56635b;cursor:pointer}.iso-nav-item:hover{background:#f3f6f2}.iso-nav-item.active{background:var(--green);color:#fff}.iso-nav-number{font-weight:900}.iso-nav-sub{padding-left:19px;font-size:10px}.iso-detail{margin-top:22px;display:grid;grid-template-columns:185px 250px 1fr;border:1px solid #e4e1d9;border-radius:10px;overflow:hidden}.iso-detail>div{padding:16px;border-right:1px solid #e4e1d9}.iso-detail>div:last-child{border:0}.iso-detail strong{font-size:13px}.iso-detail p{font-size:12px;line-height:1.6;color:#5d6a62;margin:0}@media(max-width:900px){.iso-workspace{grid-template-columns:1fr}.iso-nav{position:static;order:-1}.iso-detail{grid-template-columns:1fr}.iso-detail>div{border-right:0;border-bottom:1px solid #e4e1d9}}
</style>
@endpush
@section('content')
<a href="{{route('audit-types.index')}}" style="color:var(--green);font-size:12px;font-weight:800;text-decoration:none"><i class="ti ti-arrow-left"></i> Typy audytów</a>
<div class="iso-builder-head"><div><span class="iso-kicker">MODUŁ AUDYTOWY</span><h1>ISO 50001</h1><p>Tutaj wspólnie budujemy strukturę audytu, którą później zobaczą audytorzy i klienci.</p></div><span style="padding:6px 11px;border-radius:999px;background:#eaf4ef;color:var(--green);font-size:11px;font-weight:800">W budowie</span></div>
<div class="iso-workspace"><main class="iso-content">
@foreach($chapters as $chapter)
<section class="iso-panel {{$loop->first?'active':''}}" data-iso-panel="{{$chapter['id']}}"><span class="iso-panel-number">{{$chapter['number']}}</span><h2>{{$chapter['title']}}</h2><p class="iso-panel-lead">{{$chapter['description']}}</p><div class="iso-placeholder"><i class="ti ti-tools"></i>To miejsce będziemy uzupełniać kolejnymi uzgodnionymi polami i narzędziami.</div></section>
@foreach($chapter['items'] ?? [] as $item)<section class="iso-panel" data-iso-panel="{{$item['id']}}"><span class="iso-panel-number">{{$item['number']}}</span><h2>{{$item['title']}}</h2><p class="iso-panel-lead">{{$item['description']}}</p><div class="iso-detail"><div><strong>{{$item['number']}}</strong></div><div><strong>{{$item['title']}}</strong></div><div><p>{{$item['description']}}</p></div></div><div class="iso-placeholder"><i class="ti ti-forms"></i>W następnym kroku dodamy tutaj właściwe pola audytowe.</div></section>@endforeach
@endforeach
</main>@include('audit-types.partials.iso50001-menu',['side'=>'right'])</div>
@endsection
@push('scripts')
<script>document.querySelectorAll('[data-iso-target]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-iso-target]').forEach(item=>item.classList.remove('active'));document.querySelectorAll('[data-iso-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.isoPanel===button.dataset.isoTarget));button.classList.add('active')}));</script>
@endpush
