<?php

return [
    'questions' => [
        'organization' => ['label' => 'Nazwa organizacji', 'type' => 'text', 'group' => 'Dane podstawowe'],
        'scope' => ['label' => 'Zakres systemu zarządzania energią', 'type' => 'text', 'group' => 'Dane podstawowe'],
        'metering' => ['label' => 'Jak opomiarowana jest energia?', 'type' => 'select', 'group' => 'Opomiarowanie i systemy', 'options' => ['brak' => 'Tylko przyłącze główne', 'czesciowo' => 'Główne rozdzielnie', 'kompleksowo' => 'Poziom urządzeń']],
        'scada' => ['label' => 'Czy funkcjonuje SCADA, BMS lub inny system nadrzędny?', 'type' => 'boolean', 'group' => 'Opomiarowanie i systemy'],
        'mes' => ['label' => 'Czy działa system rejestracji produkcji (MES/ERP)?', 'type' => 'boolean', 'group' => 'Opomiarowanie i systemy'],
        'data_analysis' => ['label' => 'Jak często analizowane są dane o zużyciu?', 'type' => 'select', 'group' => 'Opomiarowanie i systemy', 'options' => ['nie' => 'Nie są analizowane', 'okresowo' => 'Okresowo', 'systematycznie' => 'Systematycznie']],
        'infrastructure_age' => ['label' => 'Wiek większości głównych urządzeń energetycznych [lata]', 'type' => 'number', 'group' => 'Instalacje i urządzenia'],
        'compressed_air' => ['label' => 'Czy jest instalacja sprężonego powietrza?', 'type' => 'boolean', 'group' => 'Instalacje i urządzenia'],
        'pv' => ['label' => 'Czy jest instalacja fotowoltaiczna?', 'type' => 'select', 'group' => 'Instalacje i urządzenia', 'options' => ['tak' => 'Tak', 'nie' => 'Nie', 'plan' => 'W planach']],
        'battery' => ['label' => 'Czy jest magazyn energii?', 'type' => 'boolean', 'group' => 'Instalacje i urządzenia'],
        'chp' => ['label' => 'Czy jest kogeneracja (CHP/biogaz)?', 'type' => 'boolean', 'group' => 'Instalacje i urządzenia'],
        'waste_heat' => ['label' => 'Czy powstaje ciepło odpadowe powyżej 60°C?', 'type' => 'select', 'group' => 'Instalacje i urządzenia', 'options' => ['tak' => 'Tak', 'nie' => 'Nie', 'nie_wiem' => 'Nie wiem']],
        'own_heat_source' => ['label' => 'Czy ciepło pochodzi z własnego źródła?', 'type' => 'select', 'group' => 'Instalacje i urządzenia', 'options' => ['tak' => 'Tak', 'nie' => 'Nie', 'mieszane' => 'Źródła mieszane']],
        'fossil_heat' => ['label' => 'Czy ciepło wytwarzane jest z paliw kopalnych?', 'type' => 'boolean', 'group' => 'Instalacje i urządzenia'],
        'old_lighting' => ['label' => 'Czy oświetlenie jest w większości niezmodernizowane?', 'type' => 'select', 'group' => 'Instalacje i urządzenia', 'options' => ['tak' => 'Tak', 'nie' => 'Nie', 'czesciowo' => 'Częściowo']],
        'fleet' => ['label' => 'Czy w zakresie systemu jest flota pojazdów?', 'type' => 'boolean', 'group' => 'Instalacje i urządzenia'],
        'energy_manager' => ['label' => 'Czy wyznaczono osobę odpowiedzialną za energię?', 'type' => 'select', 'group' => 'Organizacja', 'options' => ['nie' => 'Nie', 'nieformalnie' => 'Nieformalnie', 'tak' => 'Tak']],
        'locations' => ['label' => 'Liczba lokalizacji objętych systemem', 'type' => 'number', 'group' => 'Organizacja'],
        'continuous_work' => ['label' => 'Czy zakład pracuje w ruchu ciągłym?', 'type' => 'boolean', 'group' => 'Organizacja'],
        'own_maintenance' => ['label' => 'Czy utrzymanie ruchu jest realizowane siłami własnymi?', 'type' => 'boolean', 'group' => 'Organizacja'],
        'entity_type' => ['label' => 'Typ podmiotu', 'type' => 'select', 'group' => 'Organizacja', 'options' => ['prywatny' => 'Prywatny', 'komunalny' => 'Komunalny', 'publiczny' => 'Publiczny']],
        'energy_cost_share' => ['label' => 'Udział kosztów energii w kosztach operacyjnych [%]', 'type' => 'number', 'group' => 'Uwarunkowania finansowe'],
        'efficiency_budget' => ['label' => 'Czy wyodrębniono budżet na efektywność energetyczną?', 'type' => 'boolean', 'group' => 'Uwarunkowania finansowe'],
        'payback_limit' => ['label' => 'Maksymalny akceptowany okres zwrotu [lata]', 'type' => 'number', 'group' => 'Uwarunkowania finansowe'],
        'planned_investments' => ['label' => 'Czy planowane są inwestycje zmieniające zużycie energii?', 'type' => 'boolean', 'group' => 'Uwarunkowania finansowe'],
        'white_certificates' => ['label' => 'Czy organizacja korzystała z białych certyfikatów?', 'type' => 'select', 'group' => 'Uwarunkowania finansowe', 'options' => ['tak' => 'Tak', 'nie' => 'Nie', 'nie_wiem' => 'Nie wiem']],
        'consumption_tj' => ['label' => 'Roczne zużycie energii [TJ]', 'type' => 'number', 'group' => 'Otoczenie prawne i rynkowe'],
        'energy_audit' => ['label' => 'Czy wykonano audyt energetyczny przedsiębiorstwa?', 'type' => 'boolean', 'group' => 'Otoczenie prawne i rynkowe'],
        'ets' => ['label' => 'Czy instalacja jest objęta EU ETS?', 'type' => 'boolean', 'group' => 'Otoczenie prawne i rynkowe'],
        'csrd' => ['label' => 'Czy organizacja raportuje według CSRD/ESRS?', 'type' => 'boolean', 'group' => 'Otoczenie prawne i rynkowe'],
        'udt' => ['label' => 'Czy występują urządzenia pod dozorem UDT?', 'type' => 'boolean', 'group' => 'Otoczenie prawne i rynkowe'],
        'fgas' => ['label' => 'Czy występują instalacje chłodnicze z F-gazami?', 'type' => 'boolean', 'group' => 'Otoczenie prawne i rynkowe'],
        'energy_contract_expires' => ['label' => 'Czy umowa na dostawę energii wygasa w ciągu 2 lat?', 'type' => 'select', 'group' => 'Otoczenie prawne i rynkowe', 'options' => ['tak' => 'Tak', 'nie' => 'Nie', 'nie_wiem' => 'Nie wiem']],
        'customers_co2' => ['label' => 'Czy odbiorcy pytają o ślad węglowy lub efektywność?', 'type' => 'boolean', 'group' => 'Otoczenie prawne i rynkowe'],
        'power_limit' => ['label' => 'Czy moc przyłączeniowa ogranicza rozwój?', 'type' => 'boolean', 'group' => 'Otoczenie prawne i rynkowe'],
        'seasonality' => ['label' => 'Czy działalność ma charakter sezonowy?', 'type' => 'boolean', 'group' => 'Otoczenie prawne i rynkowe'],
        'tenders' => ['label' => 'Czy certyfikat jest wymagany lub punktowany w przetargach?', 'type' => 'boolean', 'group' => 'Otoczenie prawne i rynkowe'],
        'no_process_alternative' => ['label' => 'Czy główny proces nie ma dojrzałej alternatywy energetycznej?', 'type' => 'select', 'group' => 'Otoczenie prawne i rynkowe', 'options' => ['tak' => 'Tak', 'nie' => 'Nie', 'nie_wiem' => 'Nie wiem']],
    ],
    'swot' => ['strengths' => 'Mocne strony', 'weaknesses' => 'Słabe strony', 'opportunities' => 'Szanse', 'threats' => 'Zagrożenia'],
];
