<?php

return [
    '3-1' => [
        'verify' => ['Czy zarząd zna koszty energii i potencjał oszczędności?', 'Czy określono biznesowe, prawne i środowiskowe powody wdrożenia?', 'Czy decyzja obejmuje utrzymanie systemu po certyfikacji?'],
        'evidence' => ['Decyzja lub uchwała kierownictwa', 'Wstępna analiza kosztów, korzyści i ryzyk', 'Wieloletni budżet wdrożenia i utrzymania'],
        'actions' => ['Policz bazowy koszt energii i realistyczny potencjał poprawy.', 'Przedstaw zwrot z inwestycji w perspektywie 3-5 lat.', 'Ustal sponsora wdrożenia po stronie najwyższego kierownictwa.'],
        'pitfall' => 'Traktowanie certyfikatu jako celu samego w sobie, bez oczekiwanej poprawy wyniku energetycznego.',
    ],
    '3-2' => [
        'verify' => ['Czy wykonano ocenę luk względem klauzul 4-10?', 'Czy zidentyfikowano istniejące dane, dokumenty i praktyki?', 'Czy luki mają właścicieli, priorytety i terminy?'],
        'evidence' => ['Raport analizy luk', 'Lista istniejących procesów i dokumentów', 'Plan wdrożenia z kamieniami milowymi'],
        'actions' => ['Oceń każdą klauzulę jako spełnioną, częściową lub niespełnioną.', 'Oddziel brak dokumentu od braku działającego procesu.', 'Zaplanuj najpierw dane, SEU, EnPI i odpowiedzialności.'],
        'pitfall' => 'Tworzenie dokumentacji przed rozpoznaniem procesów i danych, które system ma rzeczywiście nadzorować.',
    ],
    '3-3' => [
        'verify' => ['Czy Energy Manager ma czas, kompetencje i uprawnienia?', 'Czy zespół reprezentuje produkcję, utrzymanie ruchu, zakupy, finanse i kierownictwo?', 'Czy odpowiedzialności są jednoznaczne?'],
        'evidence' => ['Powołanie zespołu EnMS', 'Zakres roli Energy Managera', 'Matryca RACI i harmonogram spotkań'],
        'actions' => ['Wyznacz właścicieli poszczególnych elementów EnMS.', 'Zapewnij zespołowi regularny czas i dostęp do danych.', 'Ustal sposób raportowania do zarządu.'],
        'pitfall' => 'Powierzenie całego systemu jednej osobie jako dodatkowego zadania bez czasu i prawa do podejmowania decyzji.',
    ],
    '3-4' => [
        'verify' => ['Czy wykorzystano wspólne procesy ISO 9001, 14001 lub 45001?', 'Czy nadzór dokumentów, audyty i działania korygujące są spójne?', 'Czy wymagania energetyczne nie giną w systemie zintegrowanym?'],
        'evidence' => ['Mapa procesów zintegrowanego systemu', 'Wspólne procedury i rejestry', 'Lista elementów wymagających odrębnego podejścia energetycznego'],
        'actions' => ['Wykorzystaj istniejące mechanizmy audytów, kompetencji i nadzoru dokumentacji.', 'Dodaj kryteria energetyczne do zakupów, projektowania i przeglądów.', 'Zachowaj odrębne EnPI, EnB, SEU i przegląd energetyczny.'],
        'pitfall' => 'Skopiowanie dokumentów z innego systemu ISO bez przełożenia ich na wykorzystanie i zużycie energii.',
    ],
    '3-5' => [
        'verify' => ['Czy istnieją dane o energii z reprezentatywnego okresu?', 'Czy zakres, zespół, budżet i harmonogram zostały zatwierdzone?', 'Czy organizacja zna główne bariery wdrożenia?'],
        'evidence' => ['Lista kontrolna gotowości', 'Dostępne faktury, odczyty i dane produkcyjne', 'Zatwierdzony harmonogram i budżet'],
        'actions' => ['Potwierdź dostęp do minimum 12 miesięcy danych.', 'Zaplanuj brakujące opomiarowanie i szkolenia.', 'Ustal daty przeglądów postępu i audytu wewnętrznego.'],
        'pitfall' => 'Rozpoczęcie certyfikacji przed zebraniem danych i uruchomieniem pełnego cyklu działania systemu.',
    ],
    '4-1' => [
        'verify' => ['Jakie czynniki zewnętrzne wpływają na energię: prawo, ceny, klimat, technologia i rynek?', 'Jakie czynniki wewnętrzne wpływają na zdolność EnMS: strategia, infrastruktura, kompetencje i kultura?', 'Czy oceniono istotność zmian klimatu dla EnMS?'],
        'evidence' => ['Analiza kontekstu z datą przeglądu', 'Dane o zmianach cen, produkcji, pogody i technologii', 'Powiązanie istotnych czynników z ryzykami, celami i planami'],
        'actions' => ['Przeprowadź analizę PESTLE/SWOT ukierunkowaną na energię.', 'Wskaż właściciela i częstotliwość aktualizacji każdego istotnego czynnika.', 'Przenieś istotne wnioski do rejestru ryzyk i planowania energetycznego.'],
        'pitfall' => 'Ogólna analiza firmy bez pokazania, jak jej wyniki wpływają na EnMS i wynik energetyczny.',
    ],
    '4-2' => [
        'verify' => ['Kto może wpływać na EnMS lub podlegać jego skutkom?', 'Jakie wymagania prawne, umowne i dobrowolne dotyczą energii?', 'Które oczekiwania stron organizacja przyjmuje jako zobowiązania?'],
        'evidence' => ['Rejestr stron zainteresowanych i wymagań', 'Rejestr wymagań prawnych i innych', 'Zapisy okresowej oceny aktualności i zgodności'],
        'actions' => ['Zmapuj właścicieli, pracowników, klientów, regulatorów, operatorów sieci, banki i dostawców.', 'Przypisz wymaganiom źródło, właściciela, sposób spełnienia i termin przeglądu.', 'Uwzględnij oczekiwania związane z klimatem, ciągłością dostaw i raportowaniem.'],
        'pitfall' => 'Lista stron bez zapisania ich konkretnych wymagań oraz bez decyzji, które z nich są wiążące.',
    ],
    '4-3' => [
        'verify' => ['Czy zakres wskazuje lokalizacje, granice fizyczne i organizacyjne?', 'Czy wymienia procesy, instalacje, media i rodzaje energii?', 'Czy nie wyłączono znaczącego zużycia pozostającego pod kontrolą organizacji?'],
        'evidence' => ['Zatwierdzony opis zakresu EnMS', 'Mapa lokalizacji, procesów i punktów pomiarowych', 'Uzasadnienia włączeń i wyłączeń'],
        'actions' => ['Narysuj granice systemu na mapie przepływu energii.', 'Potwierdź kontrolę nad każdym obszarem i dostępność danych.', 'Opublikuj zakres i aktualizuj go po zmianach organizacyjnych lub technicznych.'],
        'pitfall' => 'Zakres ograniczony tak, aby pominąć trudne lub energochłonne obszary znajdujące się pod kontrolą firmy.',
    ],
    '4-4' => [
        'verify' => ['Czy procesy EnMS są określone i wzajemnie powiązane?', 'Czy system działa w codziennych procesach, a nie wyłącznie w dokumentach?', 'Czy istnieją dowody ciągłej poprawy wyniku energetycznego?'],
        'evidence' => ['Mapa procesów EnMS', 'Zapisy realizacji celów, pomiarów, audytów i przeglądów', 'Trendy EnPI i wyniki działań poprawiających'],
        'actions' => ['Powiąż planowanie, operacje, pomiary i doskonalenie w jeden cykl PDCA.', 'Określ wejścia, wyjścia, właścicieli oraz mierniki procesów.', 'Regularnie sprawdzaj skuteczność systemu i wynik energetyczny.'],
        'pitfall' => 'System istniejący tylko przed audytem, którego pracownicy i właściciele procesów nie stosują na co dzień.',
    ],
    '5-1' => [
        'verify' => ['Czy kierownictwo bierze odpowiedzialność za skuteczność EnMS?', 'Czy cele energetyczne są spójne ze strategią firmy?', 'Czy zapewniono zasoby i usunięto bariery organizacyjne?'],
        'evidence' => ['Decyzje i protokoły kierownictwa', 'Zatwierdzone budżety, cele i przydział zasobów', 'Regularne raporty wyniku energetycznego do zarządu'],
        'actions' => ['Włącz energię do decyzji strategicznych i operacyjnych.', 'Ustal cykliczne raportowanie EnPI, ryzyk i planów.', 'Wymagaj od właścicieli procesów realizacji przyjętych działań.'],
        'pitfall' => 'Jednorazowe podpisanie polityki bez udziału kierownictwa w decyzjach, przeglądach i usuwaniu przeszkód.',
    ],
    '5-2' => [
        'verify' => ['Czy polityka pasuje do celu, skali i kontekstu organizacji?', 'Czy zawiera zobowiązania do spełniania wymagań i poprawy wyniku energetycznego?', 'Czy wspiera projektowanie, zakupy, informacje i zasoby?'],
        'evidence' => ['Aktualna polityka z datą i zatwierdzeniem', 'Dowody komunikowania pracownikom', 'Dowody dostępności dla właściwych stron'],
        'actions' => ['Napisz krótką politykę odnoszącą się do realnej działalności.', 'Powiąż ją z celami, zakupami i projektowaniem.', 'Sprawdzaj zrozumienie polityki, nie tylko fakt jej wywieszenia.'],
        'pitfall' => 'Uniwersalny tekst skopiowany z internetu, którego pracownicy nie znają i który nie kieruje decyzjami.',
    ],
    '5-3' => [
        'verify' => ['Czy role i uprawnienia są przypisane konkretnym osobom?', 'Kto raportuje kierownictwu wynik EnMS i wynik energetyczny?', 'Czy właściciele SEU rozumieją swoją odpowiedzialność?'],
        'evidence' => ['Schemat organizacyjny i matryca odpowiedzialności', 'Powołanie Energy Managera i zespołu EnMS', 'Zakresy obowiązków i zastępstwa'],
        'actions' => ['Przypisz właścicieli polityki, danych, SEU, celów, audytów i działań.', 'Nadaj Energy Managerowi dostęp do danych i kierownictwa.', 'Komunikuj role osobom, których dotyczą.'],
        'pitfall' => 'Odpowiedzialność bez uprawnień, zasobów, zastępstwa albo jednoznacznego sposobu raportowania.',
    ],
    '6-1' => [
        'verify' => ['Czy ryzyka i szanse wynikają z kontekstu oraz wymagań stron?', 'Czy oceniono prawdopodobieństwo, skutek i istotność?', 'Czy działania są zintegrowane z procesami i oceniane pod względem skuteczności?'],
        'evidence' => ['Rejestr ryzyk i szans z kryteriami oceny', 'Plany działań, właściciele i terminy', 'Ocena skuteczności działań'],
        'actions' => ['Uwzględnij ceny, awarie, dostawy energii, regulacje, klimat, technologię i kompetencje.', 'Priorytetyzuj pozycje według ustalonej metody.', 'Powiąż działania z celami, inwestycjami i nadzorem operacyjnym.'],
        'pitfall' => 'Rejestr skopiowany z systemu jakości, bez ryzyk dotyczących energii i bez działań po dokonaniu oceny.',
    ],
    '6-2' => [
        'verify' => ['Czy cele są zgodne z polityką i istotnymi możliwościami poprawy?', 'Czy zadania są mierzalne i mają wartość bazową oraz docelową?', 'Czy plan wskazuje odpowiedzialnych, zasoby, terminy i metodę oceny?'],
        'evidence' => ['Rejestr celów i zadań energetycznych', 'Plany działania i budżety', 'Raporty postępu oraz obliczenia osiągniętej poprawy'],
        'actions' => ['Formułuj cele SMART i wiąż je z EnPI.', 'Określ sposób normalizacji wyniku i weryfikacji oszczędności.', 'Aktualizuj plan po opóźnieniach, zmianach lub nieskuteczności.'],
        'pitfall' => 'Cele typu „zmniejszyć zużycie” bez wartości docelowej, terminu, właściciela i metody potwierdzenia wyniku.',
    ],
    '6-3' => [
        'verify' => ['Czy przeanalizowano przeszłe i obecne wykorzystanie oraz zużycie energii?', 'Czy SEU wybrano według udokumentowanych kryteriów?', 'Czy dla SEU określono zmienne istotne, osoby, bieżący wynik i przyszłe zużycie?', 'Czy możliwości poprawy są ocenione i priorytetyzowane?'],
        'evidence' => ['Bilans energii i historia zużycia', 'Lista SEU z udziałami i uzasadnieniem', 'Zmienne istotne, modele zużycia i prognozy', 'Rejestr możliwości poprawy z oceną techniczną i ekonomiczną'],
        'actions' => ['Zbierz faktury, liczniki, dane produkcyjne, pogodowe i eksploatacyjne.', 'Zbuduj bilans przepływów energii i zastosuj kryteria istotności.', 'Dla każdego SEU opisz zmienne, parametry pracy, kompetencje i możliwości poprawy.', 'Aktualizuj przegląd po znaczących zmianach.'],
        'pitfall' => 'Uznaniowa lista największych urządzeń bez bilansu, kryteriów SEU, zmiennych i analizy możliwości poprawy.',
    ],
    '6-4' => [
        'verify' => ['Czy EnPI odzwierciedlają wynik energetyczny organizacji i SEU?', 'Czy uwzględniają zmienne istotne, gdy wpływają one znacząco na wynik?', 'Czy metoda obliczeń pozwala wiarygodnie wykazać poprawę?'],
        'evidence' => ['Rejestr EnPI z definicjami, wzorami i jednostkami', 'Źródła danych oraz właściciele wskaźników', 'Analizy trendów i zasady normalizacji'],
        'actions' => ['Dobierz wskaźniki absolutne i względne odpowiednie do procesu.', 'Udokumentuj wzór, częstotliwość, źródło danych i odpowiedzialność.', 'Testuj, czy wskaźnik reaguje na rzeczywistą poprawę, a nie wyłącznie na zmianę produkcji.'],
        'pitfall' => 'Śledzenie jedynie rachunków lub całkowitego zużycia bez odniesienia do czynników wpływających na działalność.',
    ],
    '6-5' => [
        'verify' => ['Czy okres bazowy jest reprezentatywny i oparty na wiarygodnych danych?', 'Czy EnB jest powiązana z właściwymi EnPI?', 'Czy określono warunki korekty i normalizacji linii bazowej?'],
        'evidence' => ['Udokumentowany okres i wartości bazowe', 'Uzasadnienie wyboru okresu oraz model bazowy', 'Historia korekt EnB i ich zatwierdzeń'],
        'actions' => ['Wybierz okres obejmujący normalne warunki działania.', 'Zapisz źródła danych, założenia i zmienne istotne.', 'Koryguj EnB po trwałych zmianach procesów, obiektów lub modelu, nie po każdym gorszym wyniku.'],
        'pitfall' => 'Zmiana linii bazowej w celu ukrycia pogorszenia albo użycie niereprezentatywnego okresu bez uzasadnienia.',
    ],
    '6-6' => [
        'verify' => ['Czy plan określa dane potrzebne do monitorowania kluczowych cech?', 'Czy wskazuje źródło, częstotliwość, odpowiedzialność i sposób przechowywania?', 'Czy zapewniono dokładność, spójność i powtarzalność pomiarów?'],
        'evidence' => ['Plan zbierania danych energetycznych', 'Mapa liczników i punktów pomiarowych', 'Harmonogram odczytów, wzorcowań i kontroli jakości danych', 'Rejestr braków danych i metod ich uzupełniania'],
        'actions' => ['Powiąż każdy EnPI, SEU i cel z konkretnymi danymi.', 'Określ walidację odczytów, jednostki, agregację i retencję.', 'Regularnie sprawdzaj, czy plan nadal odpowiada potrzebom systemu.'],
        'pitfall' => 'Gromadzenie wielu danych bez określenia, kto je analizuje, jak sprawdza jakość i do jakiej decyzji są potrzebne.',
    ],
    '7-1' => [
        'verify' => ['Czy zasoby odpowiadają zakresowi, SEU i ambicji celów?', 'Czy dostępne są ludzie, czas, budżet, narzędzia i opomiarowanie?', 'Czy braki zasobów są raportowane i rozwiązywane?'],
        'evidence' => ['Plan zasobów i budżet EnMS', 'Przydział czasu zespołu', 'Plan inwestycji w pomiary, szkolenia i działania'],
        'actions' => ['Oszacuj zasoby dla utrzymania systemu, nie tylko wdrożenia.', 'Priorytetyzuj braki wpływające na wiarygodność danych i SEU.', 'Przeglądaj zasoby podczas przeglądu zarządzania.'],
        'pitfall' => 'Ambitne cele bez budżetu, czasu pracowników i dostępu do narzędzi lub danych.',
    ],
    '7-2' => [
        'verify' => ['Kto wpływa na wynik energetyczny i jakie kompetencje są wymagane?', 'Czy oceniono luki kompetencyjne?', 'Czy sprawdzono skuteczność szkoleń i zachowano dowody?'],
        'evidence' => ['Matryca kompetencji', 'Plan i rejestr szkoleń', 'Oceny skuteczności oraz kwalifikacje osób i dostawców'],
        'actions' => ['Uwzględnij operatorów, utrzymanie ruchu, projektantów, zakupy, audytorów i kierownictwo.', 'Po szkoleniu zweryfikuj wiedzę lub zachowanie w pracy.', 'Zapewnij kompetencje zastępcze dla kluczowych ról.'],
        'pitfall' => 'Lista obecności na szkoleniu traktowana jako jedyny dowód kompetencji, bez sprawdzenia skuteczności.',
    ],
    '7-3' => [
        'verify' => ['Czy pracownicy znają politykę i swój wpływ na wynik energetyczny?', 'Czy rozumieją korzyści z poprawy i skutki niestosowania wymagań?', 'Czy potrafią wskazać własne działania wspierające cele?'],
        'evidence' => ['Materiały komunikacyjne i kampanie świadomościowe', 'Rozmowy, ankiety lub obserwacje pracowników', 'Zgłoszone pomysły i działania oddolne'],
        'actions' => ['Dostosuj komunikat do stanowiska i realnego wpływu pracownika.', 'Używaj przykładów z własnych SEU i celów.', 'Regularnie odświeżaj świadomość, szczególnie po zmianach.'],
        'pitfall' => 'Wymaganie od pracowników recytowania polityki zamiast rozumienia własnego wpływu i właściwych zachowań.',
    ],
    '7-4' => [
        'verify' => ['Czy ustalono co, kiedy, komu, jak i przez kogo jest komunikowane?', 'Czy określono komunikację zewnętrzną?', 'Czy pracownicy mogą zgłaszać pomysły i problemy energetyczne?'],
        'evidence' => ['Plan lub matryca komunikacji', 'Raporty, komunikaty i protokoły spotkań', 'Rejestr sugestii wraz z odpowiedziami'],
        'actions' => ['Zdefiniuj odbiorców, kanały, częstotliwość i właścicieli komunikatów.', 'Raportuj wyniki w formie zrozumiałej dla odbiorcy.', 'Zapewnij informację zwrotną dla zgłaszających pomysły.'],
        'pitfall' => 'Komunikacja jednokierunkowa i okazjonalna, bez kanału dla informacji zwrotnej oraz bez decyzji o komunikacji zewnętrznej.',
    ],
    '7-5' => [
        'verify' => ['Czy określono dokumenty wymagane przez normę i potrzebne organizacji?', 'Czy dokumenty są identyfikowane, zatwierdzane, wersjonowane i dostępne?', 'Czy zapisy są chronione, przechowywane i usuwane według zasad?'],
        'evidence' => ['Wykaz dokumentów i zapisów EnMS', 'Procedura nadzoru dokumentacji', 'Historia wersji, zatwierdzeń, dostępów i okresów retencji'],
        'actions' => ['Ustal standard nazwy, numeru, wersji, daty i właściciela.', 'Zapewnij jedną obowiązującą wersję w miejscu użycia.', 'Nadzoruj również dokumenty zewnętrzne, dane i arkusze obliczeniowe.'],
        'pitfall' => 'Dokumenty bez wersji, rozproszone po prywatnych folderach lub tworzone dla audytora, ale nieużywane operacyjnie.',
    ],
    '8-1' => [
        'verify' => ['Czy dla SEU i planów działania ustalono kryteria pracy oraz utrzymania?', 'Czy kryteria są komunikowane i monitorowane?', 'Czy nadzorowane są zmiany i procesy zlecane na zewnątrz?'],
        'evidence' => ['Kryteria operacyjne i instrukcje dla SEU', 'Zapisy parametrów, przeglądów i konserwacji', 'Oceny zmian oraz wymagania dla wykonawców'],
        'actions' => ['Określ dopuszczalne parametry, harmonogramy, reakcje na odchylenia i odpowiedzialności.', 'Włącz wymagania energetyczne do utrzymania ruchu i planowania produkcji.', 'Sprawdzaj stosowanie kryteriów na miejscu.'],
        'pitfall' => 'Instrukcje istniejące na papierze, ale nieznane operatorom albo pozbawione mierzalnych kryteriów energetycznych.',
    ],
    '8-2' => [
        'verify' => ['Czy efektywność energetyczna jest oceniana przy nowych i modernizowanych rozwiązaniach?', 'Czy analiza obejmuje przewidywany okres użytkowania?', 'Czy wyniki oceny wpływają na wymagania projektowe i decyzję?'],
        'evidence' => ['Procedura i checklisty projektowe', 'Obliczenia energii oraz TCO dla wariantów', 'Kryteria odbioru i wyniki pomiarów po uruchomieniu'],
        'actions' => ['Włącz Energy Managera na etapie koncepcji i specyfikacji.', 'Porównuj warianty według zużycia, kosztu cyklu życia i wpływu na EnPI.', 'Po uruchomieniu potwierdź osiągnięcie projektowanych parametrów.'],
        'pitfall' => 'Analiza energii wykonana po wyborze rozwiązania, gdy nie może już wpłynąć na projekt ani koszt cyklu życia.',
    ],
    '8-3' => [
        'verify' => ['Czy dostawcy znają energetyczne kryteria oceny?', 'Czy zakupy urządzeń i usług dla SEU uwzględniają wynik energetyczny?', 'Czy zakup energii jest oceniany według ustalonych specyfikacji?'],
        'evidence' => ['Procedura zakupowa i wymagania w zapytaniach', 'Porównania ofert z energią i TCO', 'Oceny dostawców oraz specyfikacje zakupu energii'],
        'actions' => ['Określ minimalne parametry energetyczne i sposób ich weryfikacji.', 'Porównuj całkowity koszt posiadania, a nie tylko cenę zakupu.', 'Przekazuj kryteria dostawcom przed złożeniem ofert.'],
        'pitfall' => 'Wybór najniższej ceny zakupu bez analizy kosztów energii, serwisu i użytkowania przez cały cykl życia.',
    ],
    '9-1' => [
        'verify' => ['Czy monitorowane są EnPI, SEU, realizacja celów i rzeczywiste zużycie względem oczekiwanego?', 'Czy określono metody, częstotliwość i odpowiedzialność za analizę?', 'Czy istotne odchylenia są badane i prowadzą do działań?'],
        'evidence' => ['Plan monitorowania i raporty trendów', 'Analizy EnPI względem EnB i celów', 'Rejestr odchyleń, przyczyn, decyzji i działań', 'Zapisy nadzoru nad wyposażeniem pomiarowym'],
        'actions' => ['Ustal progi alarmowe i regularny rytm analizy.', 'Normalizuj wynik, gdy zmienne istotne wpływają na porównanie.', 'Prezentuj zarządowi wnioski i decyzje, nie tylko surowe liczby.'],
        'pitfall' => 'Zbieranie odczytów i faktur bez analizy przyczyn odchyleń oraz bez podejmowania decyzji.',
    ],
    '9-1-2' => [
        'verify' => ['Czy zidentyfikowano wszystkie obowiązujące wymagania?', 'Czy zgodność jest oceniana w zaplanowanych odstępach?', 'Czy niezgodności prawne są usuwane i raportowane?'],
        'evidence' => ['Aktualny rejestr wymagań', 'Okresowe oceny zgodności z dowodami', 'Działania po stwierdzonych brakach'],
        'actions' => ['Przypisz właścicieli i częstotliwość oceny każdemu wymaganiu.', 'Oceniaj faktyczne spełnienie, a nie samą znajomość przepisu.', 'Aktualizuj rejestr po zmianach prawnych i organizacyjnych.'],
        'pitfall' => 'Lista przepisów bez udokumentowanej oceny, czy konkretne obowiązki są rzeczywiście spełnione.',
    ],
    '9-2' => [
        'verify' => ['Czy program audytów uwzględnia ryzyko, znaczenie procesów, zmiany i poprzednie wyniki?', 'Czy audytorzy są kompetentni i niezależni od ocenianej pracy?', 'Czy wyniki są raportowane, a działania realizowane terminowo?'],
        'evidence' => ['Program i plany audytów', 'Kompetencje oraz niezależność audytorów', 'Raporty, dowody, niezgodności i działania korygujące'],
        'actions' => ['Audytuj procesy w miejscu ich wykonywania i rozmawiaj z pracownikami.', 'Sprawdzaj zgodność, wdrożenie i skuteczność.', 'Śledź zamknięcie ustaleń bez zbędnej zwłoki.'],
        'pitfall' => 'Audyt ograniczony do przeglądu segregatora przez osobę audytującą własną pracę.',
    ],
    '9-3' => [
        'verify' => ['Czy przegląd obejmuje wszystkie wymagane dane wejściowe?', 'Czy najwyższe kierownictwo analizuje wyniki i podejmuje decyzje?', 'Czy wyjścia obejmują zmiany, zasoby, cele i możliwości poprawy?'],
        'evidence' => ['Agenda i komplet danych wejściowych', 'Protokół z decyzjami, odpowiedzialnymi i terminami', 'Monitorowanie wykonania decyzji'],
        'actions' => ['Przedstaw kontekst, ryzyka, EnPI, cele, zgodność, audyty, zasoby i poprawę.', 'Zapisuj konkretne decyzje zamiast samej prezentacji.', 'Rozliczaj wykonanie decyzji na kolejnym przeglądzie.'],
        'pitfall' => 'Spotkanie informacyjne bez udziału decydentów, decyzji, przydziału zasobów i kontroli wcześniejszych ustaleń.',
    ],
    '10-1' => [
        'verify' => ['Czy organizacja reaguje na niezgodność i usuwa jej skutki?', 'Czy bada przyczynę źródłową oraz możliwość wystąpienia problemu gdzie indziej?', 'Czy sprawdza skuteczność działań i aktualizuje system?'],
        'evidence' => ['Rejestr niezgodności i korekcji', 'Analizy przyczyn źródłowych', 'Działania korygujące, terminy i weryfikacje skuteczności'],
        'actions' => ['Najpierw zabezpiecz sytuację, następnie usuń przyczynę systemową.', 'Stosuj 5 Why, diagram Ishikawy lub inną adekwatną metodę.', 'Sprawdź skuteczność po czasie i oceń potrzebę zmian ryzyk lub dokumentacji.'],
        'pitfall' => 'Działanie ograniczone do przypomnienia pracownikowi, bez zbadania przyczyny systemowej i potwierdzenia skuteczności.',
    ],
    '10-2' => [
        'verify' => ['Czy poprawia się przydatność, adekwatność i skuteczność EnMS?', 'Czy organizacja wykazuje poprawę wyniku energetycznego?', 'Czy źródła doskonalenia obejmują dane, audyty, pracowników i benchmarking?'],
        'evidence' => ['Trendy znormalizowanych EnPI', 'Zrealizowane projekty i zweryfikowane oszczędności', 'Rosnące cele oraz rejestr pomysłów i usprawnień'],
        'actions' => ['Buduj portfel działań od optymalizacji operacyjnej po inwestycje.', 'Weryfikuj oszczędności względem EnB i zmiennych istotnych.', 'Wykorzystuj wyniki do kolejnego cyklu planowania.'],
        'pitfall' => 'Uznanie braku niezgodności za dowód doskonalenia, bez mierzalnej poprawy EnPI i wyniku energetycznego.',
    ],
    '11-1' => [
        'verify' => ['Czy wykonano pełny audyt wewnętrzny i przegląd zarządzania?', 'Czy system działa wystarczająco długo, aby wykazać wyniki?', 'Czy zamknięto kluczowe luki i niezgodności?'],
        'evidence' => ['Raport audytu gotowości', 'Komplet aktualnych zapisów EnMS', 'Plan zamknięcia ostatnich luk'],
        'actions' => ['Wykonaj próbę audytową obejmującą dokumenty, rozmowy i wizję lokalną.', 'Sprawdź spójność danych od źródła do EnPI i decyzji.', 'Nie planuj etapu 2 przed usunięciem braków systemowych.'],
        'pitfall' => 'Zgłoszenie do certyfikacji systemu, który ma dokumenty, ale nie przeszedł jeszcze pełnego cyklu PDCA.',
    ],
    '11-2' => [
        'verify' => ['Czy jednostka posiada właściwą akredytację?', 'Czy audytorzy znają branżę i procesy energetyczne organizacji?', 'Czy zakres, terminy i koszty oferty są porównywalne?'],
        'evidence' => ['Potwierdzenie akredytacji i zakresu', 'Porównanie ofert oraz kompetencji zespołu', 'Umowa i program certyfikacji'],
        'actions' => ['Zweryfikuj akredytację w oficjalnym wykazie.', 'Porównaj doświadczenie branżowe, czas audytu i zasady nadzoru.', 'Ustal jasny zakres certyfikacji zgodny z zakresem EnMS.'],
        'pitfall' => 'Wybór wyłącznie według najniższej ceny bez sprawdzenia akredytacji, kompetencji i adekwatnego czasu audytu.',
    ],
    '11-3' => [
        'verify' => ['Czy na etapie 1 oceniono gotowość dokumentacji i lokalizacji?', 'Czy etap 2 sprawdza faktyczne wdrożenie oraz skuteczność?', 'Czy ustalenia mają właścicieli i terminy reakcji?'],
        'evidence' => ['Plan audytu etapu 1 i 2', 'Raporty oraz odpowiedzi na ustalenia', 'Dowody korekcji i działań korygujących'],
        'actions' => ['Przygotuj pracowników do rozmowy o ich rzeczywistej pracy, bez wyuczonych odpowiedzi.', 'Zapewnij dostęp do obiektów, danych i właścicieli procesów.', 'Traktuj ustalenia jako informację do poprawy systemu.'],
        'pitfall' => 'Przygotowanie pokazowe na dzień audytu zamiast prezentacji normalnie działającego systemu.',
    ],
    '11-4' => [
        'verify' => ['Czy po certyfikacji EnMS działa stale?', 'Czy organizacja przygotowuje się do audytów nadzoru i recertyfikacji poprzez bieżące działania?', 'Czy wiedza jest odporna na rotację personelu?'],
        'evidence' => ['Roczny kalendarz EnMS', 'Aktualizacje przeglądu energetycznego, EnPI, audytów i przeglądów', 'Plany ciągłości ról i transferu wiedzy'],
        'actions' => ['Utrzymuj miesięczny i roczny rytm analiz, audytów oraz przeglądów.', 'Aktualizuj system po zmianach procesów, energii i organizacji.', 'Planuj audyty nadzoru i recertyfikację z wyprzedzeniem.'],
        'pitfall' => 'Spadek aktywności po otrzymaniu certyfikatu i odtwarzanie zapisów dopiero przed kolejnym audytem.',
    ],
];
