<?php

// Formularz i biblioteka czynników z Generator_4.1_demo.html.
return [
    'stakeholders' => [
        ['Zarząd', 'wewn.', 'Ograniczenie kosztów energii, przewidywalność wydatków', 'nie'],
        ['Pracownicy', 'wewn.', 'Jasne zasady eksploatacji, bezpieczne warunki pracy', 'nie'],
        ['Służby utrzymania ruchu', 'wewn.', 'Dostęp do danych, realny wpływ na decyzje eksploatacyjne', 'nie'],
        ['Organy regulacyjne', 'zewn.', 'Spełnienie wymagań prawnych w zakresie efektywności energetycznej', 'TAK'],
        ['Odbiorcy', 'zewn.', '@customers', '@customerCompliance'],
        ['Dostawcy energii', 'zewn.', 'Przewidywalność poboru, zgodność z warunkami umowy', 'nie'],
        ['Jednostka certyfikująca', 'zewn.', 'Kompletność i dostępność zapisów systemowych', 'TAK'],
    ],
    'relatedDocuments' => [
        ['D-EnMS-ZAK-01 — Zakres systemu', 'Kontekst determinuje zakres; oba dokumenty muszą być spójne'],
        ['D-EnMS-RYZ-01 — Rejestr ryzyk i szans', 'Zagrożenia i słabości → ryzyka; szanse i mocne strony → szanse'],
        ['D-EnMS-CEL-01 — Cele energetyczne', 'Wnioski z sekcji 6 zasilają cele'],
        ['Protokół Przeglądu Zarządzania', 'Kontekst jest obowiązkowym punktem agendy (kl. 9.3)'],
    ],
    'questions' => ['organization' => ['label' => 'Nazwa organizacji',
        'type' => 'text',
        'group' => 'Dane podstawowe'],
        'scope' => ['label' => 'Zakres systemu',
            'type' => 'text',
            'group' => 'Dane podstawowe'],
        'metering' => ['label' => 'Jak opomiarowana jest energia?',
            'type' => 'select',
            'group' => 'Opomiarowanie i systemy',
            'options' => ['brak' => 'tylko przyłącze główne',
                'czesciowo' => 'główne rozdzielnie',
                'kompleksowo' => 'poziom urządzeń']],
        'scada' => ['label' => 'Czy funkcjonuje SCADA, BMS lub inny system nadrzędny?',
            'type' => 'select',
            'group' => 'Opomiarowanie i systemy',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'mes' => ['label' => 'Czy jest system rejestracji produkcji (MES/ERP)?',
            'type' => 'select',
            'group' => 'Opomiarowanie i systemy',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'data_analysis' => ['label' => 'Czy dane o zużyciu są regularnie analizowane?',
            'type' => 'select',
            'group' => 'Opomiarowanie i systemy',
            'options' => ['nie' => 'nie',
                'okresowo' => 'okresowo',
                'systematycznie' => 'systematycznie']],
        'infrastructure_age' => ['label' => 'Wiek większości głównych urządzeń energetycznych (lata)',
            'type' => 'number',
            'group' => 'Instalacje i urządzenia'],
        'compressed_air' => ['label' => 'Czy jest instalacja sprężonego powietrza?',
            'type' => 'select',
            'group' => 'Instalacje i urządzenia',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'pv' => ['label' => 'Czy jest instalacja fotowoltaiczna?',
            'type' => 'select',
            'group' => 'Instalacje i urządzenia',
            'options' => ['tak' => 'tak',
                'nie' => 'nie',
                'w planach' => 'w planach']],
        'battery' => ['label' => 'Czy jest magazyn energii?',
            'type' => 'select',
            'group' => 'Instalacje i urządzenia',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'chp' => ['label' => 'Czy jest kogeneracja (CHP, biogaz)?',
            'type' => 'select',
            'group' => 'Instalacje i urządzenia',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'own_heat_source' => ['label' => 'Czy ciepło pochodzi z własnego źródła?',
            'type' => 'select',
            'group' => 'Instalacje i urządzenia',
            'options' => ['tak' => 'tak',
                'nie' => 'nie',
                'mieszane' => 'mieszane']],
        'fossil_heat' => ['label' => 'Czy ciepło wytwarzane jest z paliw kopalnych?',
            'type' => 'select',
            'group' => 'Instalacje i urządzenia',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'waste_heat' => ['label' => 'Czy w procesach powstaje ciepło odpadowe powyżej 60°C?',
            'type' => 'select',
            'group' => 'Instalacje i urządzenia',
            'options' => ['tak' => 'tak',
                'nie' => 'nie',
                'nie wiem' => 'nie wiem']],
        'old_lighting' => ['label' => 'Czy oświetlenie jest w większości niezmodernizowane?',
            'type' => 'select',
            'group' => 'Instalacje i urządzenia',
            'options' => ['tak' => 'tak',
                'nie' => 'nie',
                'czesciowo' => 'czesciowo']],
        'fleet' => ['label' => 'Czy w zakresie systemu jest flota pojazdów?',
            'type' => 'select',
            'group' => 'Instalacje i urządzenia',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'energy_manager' => ['label' => 'Czy wyznaczono osobę odpowiedzialną za energię?',
            'type' => 'select',
            'group' => 'Organizacja',
            'options' => ['nie' => 'nie',
                'nieformalnie' => 'nieformalnie',
                'tak' => 'tak']],
        'locations' => ['label' => 'Ile lokalizacji obejmuje system?',
            'type' => 'number',
            'group' => 'Organizacja'],
        'shifts' => ['label' => 'Ile zmian produkcyjnych na dobę?',
            'type' => 'select',
            'group' => 'Organizacja',
            'options' => ['1' => 'jedna',
                '2' => 'dwie',
                '3' => 'trzy',
                '4' => 'ruch ciągły']],
        'own_maintenance' => ['label' => 'Czy utrzymanie ruchu realizowane jest siłami własnymi?',
            'type' => 'select',
            'group' => 'Organizacja',
            'options' => ['tak' => 'tak',
                'nie' => 'nie',
                'mieszane' => 'mieszane']],
        'entity_type' => ['label' => 'Typ podmiotu',
            'type' => 'select',
            'group' => 'Organizacja',
            'options' => ['prywatny' => 'prywatny',
                'komunalny' => 'komunalny',
                'publiczny' => 'publiczny']],
        'energy_cost_share' => ['label' => 'Udział kosztów energii w kosztach operacyjnych (%)',
            'type' => 'number',
            'group' => 'Uwarunkowania finansowe'],
        'efficiency_budget' => ['label' => 'Czy wyodrębniono budżet na efektywność energetyczną?',
            'type' => 'select',
            'group' => 'Uwarunkowania finansowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'payback_limit' => ['label' => 'Maksymalny akceptowany okres zwrotu (lata)',
            'type' => 'number',
            'group' => 'Uwarunkowania finansowe'],
        'planned_investments' => ['label' => 'Czy planowane są inwestycje zmieniające zużycie energii?',
            'type' => 'select',
            'group' => 'Uwarunkowania finansowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'white_certificates' => ['label' => 'Czy organizacja korzystała z białych certyfikatów?',
            'type' => 'select',
            'group' => 'Uwarunkowania finansowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie',
                'nie wiem' => 'nie wiem']],
        'consumption_tj' => ['label' => 'Roczne zużycie energii (TJ)',
            'type' => 'number',
            'group' => 'Otoczenie prawne i rynkowe'],
        'energy_audit' => ['label' => 'Czy wykonano audyt energetyczny przedsiębiorstwa?',
            'type' => 'select',
            'group' => 'Otoczenie prawne i rynkowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'ets' => ['label' => 'Czy instalacja objęta EU ETS?',
            'type' => 'select',
            'group' => 'Otoczenie prawne i rynkowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'csrd' => ['label' => 'Czy organizacja raportuje wg CSRD / ESRS?',
            'type' => 'select',
            'group' => 'Otoczenie prawne i rynkowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'udt' => ['label' => 'Czy są urządzenia pod dozorem UDT?',
            'type' => 'select',
            'group' => 'Otoczenie prawne i rynkowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'fgas' => ['label' => 'Czy są instalacje chłodnicze z f-gazami?',
            'type' => 'select',
            'group' => 'Otoczenie prawne i rynkowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'energy_contract_expires' => ['label' => 'Czy umowa na dostawę energii wygasa w ciągu 2 lat?',
            'type' => 'select',
            'group' => 'Otoczenie prawne i rynkowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie',
                'nie wiem' => 'nie wiem']],
        'customers_co2' => ['label' => 'Czy odbiorcy pytają o ślad węglowy lub efektywność?',
            'type' => 'select',
            'group' => 'Otoczenie prawne i rynkowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'power_limit' => ['label' => 'Czy dostępna moc przyłączeniowa ogranicza rozwój?',
            'type' => 'select',
            'group' => 'Otoczenie prawne i rynkowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'tenders' => ['label' => 'Czy startujecie w przetargach, gdzie certyfikat jest punktowany?',
            'type' => 'select',
            'group' => 'Otoczenie prawne i rynkowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'seasonality' => ['label' => 'Czy działalność ma charakter sezonowy?',
            'type' => 'select',
            'group' => 'Otoczenie prawne i rynkowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie']],
        'no_process_alternative' => ['label' => 'Czy główny proces nie ma alternatywy energetycznej?',
            'type' => 'select',
            'group' => 'Otoczenie prawne i rynkowe',
            'options' => ['tak' => 'tak',
                'nie' => 'nie',
                'nie wiem' => 'nie wiem']]],
    'swot' => ['strengths' => 'Mocne strony',
        'weaknesses' => 'Słabe strony',
        'opportunities' => 'Szanse',
        'threats' => 'Zagrożenia'],
    'dimensions' => ['WT' => 'Czynniki wewnętrzne — techniczne',
        'WO' => 'Czynniki wewnętrzne — organizacyjne',
        'WF' => 'Czynniki wewnętrzne — finansowe',
        'ZR' => 'Czynniki zewnętrzne — regulacyjne',
        'ZM' => 'Czynniki zewnętrzne — rynkowe',
        'ZT' => 'Czynniki zewnętrzne — technologiczne'],
    'factors' => [['id' => 'KTX-WT-01',
        'dimension' => 'WT',
        'impact' => '-',
        'text' => 'Pomiar energii realizowany jest wyłącznie na przyłączu głównym; zużycie nie jest przypisane do poszczególnych procesów ani obszarów.',
        'effect' => 'Linia bazowa wyznaczona na poziomie zakładu, nie SEU. Plan zbierania danych przewiduje rozbudowę opomiarowania.',
        'automatic' => false,
        'condition' => ['field' => 'metering',
            'op' => '===',
            'value' => 'brak']],
        ['id' => 'KTX-WT-02',
            'dimension' => 'WT',
            'impact' => '-',
            'text' => 'Opomiarowanie obejmuje główne rozdzielnie i wybrane obszary, brak pomiaru na poziomie pojedynczych urządzeń.',
            'effect' => 'Wskaźniki EnPI budowane na poziomie obszarów; doprecyzowanie w kolejnym cyklu.',
            'automatic' => false,
            'condition' => ['field' => 'metering',
                'op' => '===',
                'value' => 'czesciowo']],
        ['id' => 'KTX-WT-03',
            'dimension' => 'WT',
            'impact' => '+',
            'text' => 'Opomiarowanie jest rozbudowane, z odczytem zdalnym; dane dostępne są w systemie nadrzędnym.',
            'effect' => 'Możliwe wyznaczenie EnPI na poziomie SEU już w pierwszym cyklu.',
            'automatic' => false,
            'condition' => ['field' => 'metering',
                'op' => '===',
                'value' => 'kompleksowo']],
        ['id' => 'KTX-WT-04',
            'dimension' => 'WT',
            'impact' => '-',
            'text' => 'Istotna część infrastruktury energetycznej eksploatowana jest ponad projektowany okres użytkowania, co obniża sprawność i zwiększa awaryjność.',
            'effect' => 'Priorytet działań modernizacyjnych w pierwszym planie działań.',
            'automatic' => false,
            'condition' => ['field' => 'infrastructure_age',
                'op' => '>',
                'value' => 15]],
        ['id' => 'KTX-WT-05',
            'dimension' => 'WT',
            'impact' => '-',
            'text' => 'Instalacja sprężonego powietrza pracuje bez sterowania nadrzędnego; sprężarki sterowane są lokalnie, bez optymalizacji doboru do obciążenia.',
            'effect' => 'Sprężone powietrze wskazane jako kandydat na SEU; działanie w planie na pierwszy rok.',
            'automatic' => false,
            'condition' => ['field' => 'compressed_air',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-WT-06',
            'dimension' => 'WT',
            'impact' => '-',
            'text' => 'Nie prowadzi się systematycznej kontroli szczelności instalacji sprężonego powietrza.',
            'effect' => 'Wprowadzenie kryteriów eksploatacyjnych dla SEU (kl. 8.1).',
            'automatic' => false,
            'condition' => ['field' => 'compressed_air',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-WT-07',
            'dimension' => 'WT',
            'impact' => '+',
            'text' => 'Organizacja eksploatuje instalację fotowoltaiczną, której produkcja pokrywa część zapotrzebowania na energię elektryczną.',
            'effect' => 'Bilans energii obejmuje produkcję własną; wpływ na definicję linii bazowej.',
            'automatic' => false,
            'condition' => ['field' => 'pv',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-WT-08',
            'dimension' => 'WT',
            'impact' => 'o',
            'text' => 'Brak magazynu energii powoduje, że nadwyżki produkcji własnej oddawane są do sieci na warunkach mniej korzystnych niż autokonsumpcja.',
            'effect' => 'Analiza opłacalności magazynu jako możliwość poprawy (kl. 6.3).',
            'automatic' => false,
            'condition' => ['all' => [['field' => 'pv',
                'op' => '===',
                'value' => 'tak'],
                ['field' => 'battery',
                    'op' => '===',
                    'value' => 'nie']]]],
        ['id' => 'KTX-WT-09',
            'dimension' => 'WT',
            'impact' => 'o',
            'text' => 'Organizacja eksploatuje układ kogeneracyjny — bilans energetyczny obejmuje zarówno zużycie, jak i produkcję nośników.',
            'effect' => 'Odrębna metodyka wyznaczania linii bazowej i wskaźników dla źródła.',
            'automatic' => false,
            'condition' => ['field' => 'chp',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-WT-10',
            'dimension' => 'WT',
            'impact' => '+',
            'text' => 'Funkcjonuje system nadrzędny obejmujący część instalacji, stanowiący źródło danych o pracy urządzeń.',
            'effect' => 'Dane do przeglądu energetycznego pozyskiwane z systemu zamiast obchodem.',
            'automatic' => false,
            'condition' => ['field' => 'scada',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-WT-11',
            'dimension' => 'WT',
            'impact' => '-',
            'text' => 'Brak systemu nadrzędnego; dane o pracy urządzeń pozyskiwane są ręcznie i nie są archiwizowane.',
            'effect' => 'Plan zbierania danych musi określić sposób i częstotliwość odczytów ręcznych.',
            'automatic' => false,
            'condition' => ['field' => 'scada',
                'op' => '===',
                'value' => 'nie']],
        ['id' => 'KTX-WT-12',
            'dimension' => 'WT',
            'impact' => 'o',
            'text' => 'Zapotrzebowanie na ciepło pokrywane jest z własnego źródła; gospodarka cieplna stanowi odrębny obszar analizy.',
            'effect' => 'Ciepło ujęte jako odrębny nośnik w przeglądzie energetycznym.',
            'automatic' => false,
            'condition' => ['any' => [['field' => 'own_heat_source',
                'op' => '===',
                'value' => 'tak'],
                ['field' => 'own_heat_source',
                    'op' => '===',
                    'value' => 'mieszane']]]],
        ['id' => 'KTX-WT-13',
            'dimension' => 'WT',
            'impact' => 'o',
            'text' => 'Organizacja dysponuje flotą pojazdów, której zużycie paliw stanowi wyodrębniony obszar zużycia energii.',
            'effect' => 'Flota ujęta w granicach systemu; odrębny wskaźnik EnPI.',
            'automatic' => false,
            'condition' => ['field' => 'fleet',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-WT-14',
            'dimension' => 'WT',
            'impact' => '-',
            'text' => 'Nie realizuje się odzysku ciepła odpadowego, mimo występowania źródeł o parametrach umożliwiających odzysk.',
            'effect' => 'Odzysk ciepła wpisany na listę możliwości poprawy (kl. 6.3).',
            'automatic' => false,
            'condition' => ['field' => 'waste_heat',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-WO-01',
            'dimension' => 'WO',
            'impact' => '-',
            'text' => 'Nie wyznaczono osoby odpowiedzialnej za gospodarkę energetyczną; obowiązki rozproszone są między służby utrzymania ruchu a dział techniczny.',
            'effect' => 'Powołanie Energy Managera i formalne przypisanie ról (kl. 5.3).',
            'automatic' => false,
            'condition' => ['field' => 'energy_manager',
                'op' => '===',
                'value' => 'nie']],
        ['id' => 'KTX-WO-02',
            'dimension' => 'WO',
            'impact' => '-',
            'text' => 'Osoba zajmująca się energią została wyznaczona, jednak bez formalnego zakresu obowiązków i uprawnień decyzyjnych.',
            'effect' => 'Formalizacja zakresu obowiązków w zarządzeniu o powołaniu zespołu.',
            'automatic' => false,
            'condition' => ['field' => 'energy_manager',
                'op' => '===',
                'value' => 'nieformalnie']],
        ['id' => 'KTX-WO-03',
            'dimension' => 'WO',
            'impact' => '-',
            'text' => 'Organizacja nie posiada wdrożonego systemu zarządzania; struktura systemowa, procedury i zasady nadzoru nad dokumentacją budowane są od podstaw.',
            'effect' => 'Pełny zakres prac dokumentacyjnych; brak możliwości reużycia istniejących procedur.',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-WO-04',
            'dimension' => 'WO',
            'impact' => '-',
            'text' => 'Decyzje o zakupie urządzeń podejmowane są na podstawie ceny nabycia, bez analizy kosztu cyklu życia i kosztu energii.',
            'effect' => 'Wprowadzenie kryteriów energetycznych w zakupach (kl. 8.3).',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-WO-05',
            'dimension' => 'WO',
            'impact' => '-',
            'text' => 'Wiedza o zasadach eksploatacji instalacji skupiona jest w wąskiej grupie pracowników; brak udokumentowanych instrukcji eksploatacyjnych.',
            'effect' => 'Opracowanie kryteriów i instrukcji eksploatacji SEU (kl. 8.1).',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-WO-06',
            'dimension' => 'WO',
            'impact' => '-',
            'text' => 'Dane o zużyciu energii nie są systematycznie analizowane; faktury służą wyłącznie do rozliczeń finansowych.',
            'effect' => 'Ustanowienie procesu monitorowania i analizy (kl. 9.1).',
            'automatic' => false,
            'condition' => ['field' => 'data_analysis',
                'op' => '===',
                'value' => 'nie']],
        ['id' => 'KTX-WO-07',
            'dimension' => 'WO',
            'impact' => '-',
            'text' => 'Energia postrzegana jest w organizacji jako koszt stały, pozostający poza wpływem służb operacyjnych.',
            'effect' => 'Rozszerzony program działań świadomościowych (kl. 7.3).',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-WO-08',
            'dimension' => 'WO',
            'impact' => 'o',
            'text' => 'Struktura wielozakładowa wymaga ujednolicenia zasad zarządzania energią oraz porównywalności wskaźników między lokalizacjami.',
            'effect' => 'Wskaźniki definiowane jednolicie dla wszystkich lokalizacji.',
            'automatic' => false,
            'condition' => ['field' => 'locations',
                'op' => '>',
                'value' => 1]],
        ['id' => 'KTX-WO-09',
            'dimension' => 'WO',
            'impact' => '-',
            'text' => 'Praca w ruchu ciągłym ogranicza możliwość wyłączeń instalacji na potrzeby pomiarów diagnostycznych.',
            'effect' => 'Metodyka przeglądu oparta na pomiarach w ruchu i danych historycznych.',
            'automatic' => false,
            'condition' => ['field' => 'shifts',
                'op' => '===',
                'value' => '4']],
        ['id' => 'KTX-WO-10',
            'dimension' => 'WO',
            'impact' => '-',
            'text' => 'Rotacja personelu operacyjnego wpływa na trwałość efektów szkoleń i wymaga cyklicznego powtarzania działań.',
            'effect' => 'Szkolenia wpisane w cykl roczny, nie jednorazowy (kl. 7.2).',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-WO-11',
            'dimension' => 'WO',
            'impact' => '+',
            'text' => 'Utrzymanie ruchu realizowane jest siłami własnymi, co ułatwia wdrożenie nadzoru operacyjnego nad obszarami znaczącego zużycia.',
            'effect' => 'Nadzór operacyjny oparty na własnych służbach, bez kosztu zewnętrznego.',
            'automatic' => false,
            'condition' => ['field' => 'own_maintenance',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-WF-01',
            'dimension' => 'WF',
            'impact' => 'o',
            'text' => 'Koszty energii stanowią istotną pozycję kosztów operacyjnych, co uzasadnia priorytet działań w zakresie efektywności energetycznej.',
            'effect' => 'Wysoki poziom ambicji celów energetycznych (kl. 6.2).',
            'automatic' => false,
            'condition' => ['field' => 'energy_cost_share',
                'op' => '>=',
                'value' => 5]],
        ['id' => 'KTX-WF-02',
            'dimension' => 'WF',
            'impact' => 'o',
            'text' => 'Udział kosztów energii w kosztach operacyjnych jest umiarkowany, co ogranicza presję ekonomiczną na szybkie działania inwestycyjne.',
            'effect' => 'Cele oparte w większym stopniu na działaniach organizacyjnych niż inwestycyjnych.',
            'automatic' => false,
            'condition' => ['field' => 'energy_cost_share',
                'op' => '<',
                'value' => 5]],
        ['id' => 'KTX-WF-03',
            'dimension' => 'WF',
            'impact' => '-',
            'text' => 'Nie wyodrębniono budżetu na przedsięwzięcia służące poprawie efektywności energetycznej.',
            'effect' => 'Plany działań ograniczone do przedsięwzięć bezkosztowych i niskonakładowych w pierwszym cyklu.',
            'automatic' => false,
            'condition' => ['field' => 'efficiency_budget',
                'op' => '===',
                'value' => 'nie']],
        ['id' => 'KTX-WF-04',
            'dimension' => 'WF',
            'impact' => '-',
            'text' => 'Organizacja stosuje krótki wymagany okres zwrotu inwestycji, co ogranicza zakres przedsięwzięć możliwych do realizacji.',
            'effect' => 'Kryterium oceny możliwości poprawy uwzględnia próg zwrotu przyjęty przez organizację.',
            'automatic' => false,
            'condition' => ['field' => 'payback_limit',
                'op' => '<=',
                'value' => 3]],
        ['id' => 'KTX-WF-05',
            'dimension' => 'WF',
            'impact' => '+',
            'text' => 'Planowane przedsięwzięcia mogą kwalifikować się do wsparcia w systemie świadectw efektywności energetycznej.',
            'effect' => 'Analiza kwalifikowalności ujęta w planach działań (kl. 6.2).',
            'automatic' => false,
            'condition' => ['field' => 'white_certificates',
                'op' => '!==',
                'value' => 'tak']],
        ['id' => 'KTX-WF-06',
            'dimension' => 'WF',
            'impact' => '+',
            'text' => 'Dla przedsięwzięć o wyższym nakładzie dostępne jest finansowanie w formule ESCO lub umowy o efekt energetyczny.',
            'effect' => 'Rozszerzenie katalogu możliwych działań o przedsięwzięcia kapitałochłonne.',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-WF-07',
            'dimension' => 'WF',
            'impact' => 'o',
            'text' => 'W horyzoncie funkcjonowania systemu planowane są inwestycje zmieniające profil zużycia energii.',
            'effect' => 'Linia bazowa wymaga normalizacji po zakończeniu inwestycji (kl. 6.5).',
            'automatic' => false,
            'condition' => ['field' => 'planned_investments',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZR-01',
            'dimension' => 'ZR',
            'impact' => '-',
            'text' => 'Roczne zużycie energii przekracza próg 85 TJ, w związku z czym obowiązek posiadania systemu zarządzania energią wynika z art. 11 dyrektywy (UE) 2023/1791, z terminem 11 października 2027 r.',
            'effect' => 'Wdrożenie ma charakter obowiązkowy; harmonogram podporządkowany terminowi ustawowemu.',
            'automatic' => true,
            'condition' => ['field' => 'consumption_tj',
                'op' => '>',
                'value' => 85]],
        ['id' => 'KTX-ZR-02',
            'dimension' => 'ZR',
            'impact' => 'o',
            'text' => 'Roczne zużycie energii mieści się w przedziale objętym obowiązkiem audytu energetycznego; wdrożenie systemu zarządzania energią stanowi decyzję dobrowolną organizacji.',
            'effect' => 'Zakres i tempo wdrożenia ustalane wg priorytetów organizacji, nie terminu ustawowego.',
            'automatic' => true,
            'condition' => ['field' => 'consumption_tj',
                'op' => '<=',
                'value' => 85]],
        ['id' => 'KTX-ZR-03',
            'dimension' => 'ZR',
            'impact' => '+',
            'text' => 'Organizacja przeprowadziła audyt energetyczny przedsiębiorstwa, którego wyniki stanowią materiał wejściowy do przeglądu energetycznego.',
            'effect' => 'Przegląd energetyczny prowadzony jako aktualizacja, nie od podstaw (kl. 6.3).',
            'automatic' => false,
            'condition' => ['field' => 'energy_audit',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZR-04',
            'dimension' => 'ZR',
            'impact' => 'o',
            'text' => 'Instalacja objęta jest systemem handlu uprawnieniami do emisji; działania w obszarze energii przekładają się bezpośrednio na koszt uprawnień.',
            'effect' => 'Powiązanie celów energetycznych z celami emisyjnymi.',
            'automatic' => false,
            'condition' => ['field' => 'ets',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZR-05',
            'dimension' => 'ZR',
            'impact' => 'o',
            'text' => 'Organizacja podlega obowiązkowi sprawozdawczości zrównoważonego rozwoju; wskaźniki zużycia i intensywności energetycznej podlegają raportowaniu zewnętrznemu.',
            'effect' => 'Wskaźniki EnPI definiowane spójnie z wymaganiami sprawozdawczymi.',
            'automatic' => false,
            'condition' => ['field' => 'csrd',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZR-06',
            'dimension' => 'ZR',
            'impact' => 'o',
            'text' => 'Eksploatowane urządzenia podlegają dozorowi technicznemu, co narzuca harmonogram przeglądów i ogranicza swobodę planowania wyłączeń.',
            'effect' => 'Harmonogram audytów i pomiarów skoordynowany z terminami dozorowymi.',
            'automatic' => false,
            'condition' => ['field' => 'udt',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZR-07',
            'dimension' => 'ZR',
            'impact' => 'o',
            'text' => 'Instalacje chłodnicze zawierają fluorowane gazy cieplarniane, co wiąże się z obowiązkami kontroli szczelności i prowadzenia dokumentacji.',
            'effect' => 'Rejestr F-gaz włączony do rejestru wymagań prawnych.',
            'automatic' => false,
            'condition' => ['field' => 'fgas',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZR-08',
            'dimension' => 'ZR',
            'impact' => '+',
            'text' => 'System świadectw efektywności energetycznej umożliwia uzyskanie wsparcia finansowego dla przedsięwzięć służących poprawie efektywności.',
            'effect' => 'Kwalifikowalność przedsięwzięć oceniana na etapie planowania działań.',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-ZR-09',
            'dimension' => 'ZR',
            'impact' => '-',
            'text' => 'Otoczenie regulacyjne w obszarze efektywności energetycznej podlega częstym zmianom, co wymaga cyklicznej aktualizacji rejestru wymagań prawnych.',
            'effect' => 'Przegląd rejestru wymagań co najmniej raz w roku (kl. 9.1.2).',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-ZR-10',
            'dimension' => 'ZR',
            'impact' => '-',
            'text' => 'Organizacja stosuje procedury zamówień publicznych, co wydłuża proces realizacji przedsięwzięć inwestycyjnych.',
            'effect' => 'Harmonogram planów działań uwzględnia czas procedur zakupowych.',
            'automatic' => false,
            'condition' => ['field' => 'entity_type',
                'op' => '!==',
                'value' => 'prywatny']],
        ['id' => 'KTX-ZM-01',
            'dimension' => 'ZM',
            'impact' => '-',
            'text' => 'Ceny nośników energii podlegają istotnym wahaniom, co zwiększa ryzyko kosztowe i uzasadnia działania ograniczające zużycie.',
            'effect' => 'Ryzyko cenowe wpisane do rejestru ryzyk (kl. 6.1).',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-ZM-02',
            'dimension' => 'ZM',
            'impact' => '+',
            'text' => 'Umowa na dostawę energii wygasa w horyzoncie funkcjonowania systemu, co stanowi okazję do renegocjacji profilu zakupowego.',
            'effect' => 'Optymalizacja umowy ujęta jako możliwość poprawy (kl. 6.3).',
            'automatic' => false,
            'condition' => ['field' => 'energy_contract_expires',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZM-03',
            'dimension' => 'ZM',
            'impact' => 'o',
            'text' => 'Odbiorcy zgłaszają wymagania dotyczące śladu węglowego lub efektywności energetycznej wyrobów.',
            'effect' => 'Wymaganie rozważane jako wymóg zgodności (kl. 4.2); wskaźnik raportowany zewnętrznie.',
            'automatic' => false,
            'condition' => ['field' => 'customers_co2',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZM-04',
            'dimension' => 'ZM',
            'impact' => 'o',
            'text' => 'Odbiorcy nie zgłaszają obecnie wymagań energetycznych, jednak tendencja rynkowa wskazuje na ich pojawienie się w horyzoncie kilku lat.',
            'effect' => 'Monitorowanie zmian wymagań odbiorców w cyklu przeglądu kontekstu.',
            'automatic' => false,
            'condition' => ['field' => 'customers_co2',
                'op' => '===',
                'value' => 'nie']],
        ['id' => 'KTX-ZM-05',
            'dimension' => 'ZM',
            'impact' => '-',
            'text' => 'Ograniczona dostępność mocy przyłączeniowej stanowi barierę rozwoju i podnosi znaczenie działań po stronie efektywności.',
            'effect' => 'Redukcja zapotrzebowania jako alternatywa dla rozbudowy przyłącza.',
            'automatic' => false,
            'condition' => ['field' => 'power_limit',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZM-06',
            'dimension' => 'ZM',
            'impact' => '+',
            'text' => 'Podmioty konkurencyjne posiadają certyfikowane systemy zarządzania energią, w związku z czym certyfikat ma znaczenie w budowaniu pozycji rynkowej.',
            'effect' => 'Cel certyfikacji równorzędny z celem oszczędnościowym.',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-ZM-07',
            'dimension' => 'ZM',
            'impact' => '+',
            'text' => 'Posiadanie certyfikowanego systemu zarządzania energią jest wymagane lub premiowane w postępowaniach przetargowych, w których organizacja uczestniczy.',
            'effect' => 'Termin certyfikacji podporządkowany kalendarzowi postępowań.',
            'automatic' => false,
            'condition' => ['field' => 'tenders',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZM-08',
            'dimension' => 'ZM',
            'impact' => '+',
            'text' => 'Dostępne dane branżowe umożliwiają odniesienie wskaźników wyniku energetycznego do wartości referencyjnych.',
            'effect' => 'Wskaźniki EnPI kalibrowane wobec benchmarku branżowego.',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-ZM-09',
            'dimension' => 'ZM',
            'impact' => 'o',
            'text' => 'Sezonowość działalności istotnie wpływa na profil zużycia energii i wymaga normalizacji wskaźników względem zmiennych istotnych.',
            'effect' => 'Metodyka normalizacji linii bazowej uwzględnia sezonowość (kl. 6.5).',
            'automatic' => false,
            'condition' => ['field' => 'seasonality',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZT-01',
            'dimension' => 'ZT',
            'impact' => '+',
            'text' => 'Dostępne są technologie o potwierdzonej skuteczności — falowniki, sterowanie nadrzędne, odzysk ciepła — możliwe do zastosowania bez ingerencji w proces technologiczny.',
            'effect' => 'Zasilenie listy możliwości poprawy niskiego ryzyka (kl. 6.3).',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-ZT-02',
            'dimension' => 'ZT',
            'impact' => '+',
            'text' => 'Spadek kosztu instalacji fotowoltaicznych i magazynów energii zmienia opłacalność produkcji własnej w stosunku do lat ubiegłych.',
            'effect' => 'Ponowna analiza opłacalności OZE w planach działań.',
            'automatic' => false,
            'condition' => ['always' => true]],
        ['id' => 'KTX-ZT-03',
            'dimension' => 'ZT',
            'impact' => '+',
            'text' => 'Rozwiązania monitoringu energii dostępne są w cenie umożliwiającej opomiarowanie na poziomie pojedynczych urządzeń.',
            'effect' => 'Rozbudowa opomiarowania ujęta w planie zbierania danych (kl. 6.6).',
            'automatic' => false,
            'condition' => ['field' => 'metering',
                'op' => '!==',
                'value' => 'kompleksowo']],
        ['id' => 'KTX-ZT-04',
            'dimension' => 'ZT',
            'impact' => '+',
            'text' => 'Modernizacja oświetlenia z zastosowaniem źródeł LED może być prowadzona etapowo, bez przerywania działalności.',
            'effect' => 'Działanie o niskim ryzyku wdrożeniowym w pierwszym planie działań.',
            'automatic' => false,
            'condition' => ['field' => 'old_lighting',
                'op' => '!==',
                'value' => 'nie']],
        ['id' => 'KTX-ZT-05',
            'dimension' => 'ZT',
            'impact' => '+',
            'text' => 'Technologie pomp ciepła umożliwiają zastąpienie części zapotrzebowania na ciepło wytwarzane z paliw kopalnych.',
            'effect' => 'Kierunek dekarbonizacji ujęty w celach długoterminowych.',
            'automatic' => false,
            'condition' => ['field' => 'fossil_heat',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZT-06',
            'dimension' => 'ZT',
            'impact' => '-',
            'text' => 'Dla kluczowego procesu technologicznego nie są dostępne dojrzałe rozwiązania alternatywne, co ogranicza potencjał poprawy w tym obszarze.',
            'effect' => 'Cele koncentrowane na procesach pomocniczych, nie na procesie głównym.',
            'automatic' => false,
            'condition' => ['field' => 'no_process_alternative',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZT-07',
            'dimension' => 'ZT',
            'impact' => '+',
            'text' => 'Integracja danych energetycznych z systemami produkcyjnymi umożliwia budowę wskaźników odnoszących zużycie do wielkości produkcji.',
            'effect' => 'EnPI definiowane jako zużycie na jednostkę produkcji (kl. 6.4).',
            'automatic' => false,
            'condition' => ['field' => 'mes',
                'op' => '===',
                'value' => 'tak']],
        ['id' => 'KTX-ZT-08',
            'dimension' => 'ZT',
            'impact' => '+',
            'text' => 'Dostępne są rozwiązania odzysku ciepła odpadowego z procesów wysokotemperaturowych o akceptowalnym okresie zwrotu.',
            'effect' => 'Odzysk ciepła jako priorytetowa możliwość poprawy.',
            'automatic' => false,
            'condition' => ['field' => 'waste_heat',
                'op' => '===',
                'value' => 'tak']]]];
