@extends('layouts.app')
@section('title','HR')
@section('page-title','HR')
@section('content')
<style>
.hr-head,.hr-tabs,.hr-actions{display:flex;align-items:center;gap:10px}.hr-head{justify-content:space-between;margin-bottom:18px;flex-wrap:wrap}.hr-tabs{border-bottom:2px solid #e5e1d8;margin-bottom:18px;flex-wrap:wrap}.hr-tab{padding:10px 16px;margin-bottom:-2px;text-decoration:none;color:#778078;font-size:13px;font-weight:700;border-bottom:2px solid transparent}.hr-tab.active{color:var(--green);border-color:var(--green)}.hr-card{background:#fff;border:1px solid #e5e1d8;border-radius:12px;overflow:hidden}.hr-card-head{padding:14px 18px;background:#fafaf6;border-bottom:1px solid #eee;display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.hr-table{width:100%;border-collapse:collapse;font-size:13px}.hr-table th,.hr-table td{padding:11px 13px;text-align:left;border-bottom:1px solid #f1eee8;vertical-align:top}.hr-table th{font-size:10px;text-transform:uppercase;color:#7b827d;background:#fafaf6}.hr-btn{border:0;border-radius:7px;padding:9px 13px;background:var(--green);color:#fff;font-weight:700;cursor:pointer;text-decoration:none}.hr-btn.danger{background:#fee2e2;color:#991b1b;padding:6px 9px}.hr-filter,.hr-input{padding:9px 10px;border:1px solid #cec8bc;border-radius:7px;background:#fff}.hr-modal{display:none;position:fixed;inset:0;z-index:9000;background:rgba(0,0,0,.5);align-items:center;justify-content:center;padding:18px}.hr-modal.open{display:flex}.hr-modal-card{background:#fff;border-radius:14px;width:min(820px,100%);max-height:92vh;overflow:auto;padding:24px}.hr-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.hr-field label{display:block;font-size:11px;font-weight:700;margin-bottom:4px}.hr-field input,.hr-field select,.hr-field textarea{width:100%;box-sizing:border-box;padding:9px 10px;border:1px solid #cec8bc;border-radius:7px}.hr-full{grid-column:1/-1}.hr-empty{text-align:center;padding:42px;color:#89918c}.hr-badge{display:inline-block;padding:3px 8px;border-radius:99px;background:#eef6f1;color:var(--green);font-size:11px;font-weight:700}@media(max-width:700px){.hr-grid{grid-template-columns:1fr}.hr-full{grid-column:auto}.hr-table{min-width:850px}}
</style>
<div class="hr-head"><div><h1 style="margin:0;color:var(--green)"><i class="ti ti-users-group"></i> HR</h1><div style="font-size:12px;color:#7b827d;margin-top:4px">Delegacje, obecność i samochody pracowników.</div></div>
 @if($canTeam)<form method="GET" action="{{route('hr.index')}}"><input type="hidden" name="tab" value="{{$tab}}"><select class="hr-filter" name="user_id" onchange="this.form.submit()"><option value="">Wszyscy użytkownicy</option>@foreach($users as $person)<option value="{{$person->id}}" @selected(request('user_id')==$person->id)>{{$person->name}}</option>@endforeach</select></form>@endif
</div>
@if(session('success'))<div style="padding:11px 14px;background:#ecfdf5;color:#166534;border-radius:8px;margin-bottom:14px">{{session('success')}}</div>@endif
@if($errors->any())<div style="padding:11px 14px;background:#fef2f2;color:#991b1b;border-radius:8px;margin-bottom:14px">{{$errors->first()}}</div>@endif
<div class="hr-tabs">
 @if($canDelegations)<a class="hr-tab {{$tab==='delegations'?'active':''}}" href="{{route('hr.index',['tab'=>'delegations'])}}"><i class="ti ti-map-pin"></i> Delegacje</a>@endif
 @if($canAttendance)<a class="hr-tab {{$tab==='attendance'?'active':''}}" href="{{route('hr.index',['tab'=>'attendance'])}}"><i class="ti ti-calendar-check"></i> Lista obecności</a>@endif
 @if($canDelegations)<a class="hr-tab {{$tab==='vehicles'?'active':''}}" href="{{route('hr.index',['tab'=>'vehicles'])}}"><i class="ti ti-car"></i> Samochody</a>@endif
</div>

@if($tab==='delegations')
<div class="hr-card"><div class="hr-card-head"><strong>Delegacje {{$canTeam ? 'pracowników' : '— moje'}}</strong><button class="hr-btn" onclick="openHrModal('trip-modal')"><i class="ti ti-plus"></i> Dodaj delegację</button></div><div style="overflow:auto"><table class="hr-table"><thead><tr><th>Pracownik / cel</th><th>Termin</th><th>Trasa</th><th>Samochód</th><th>Koszty autostradowe</th><th></th></tr></thead><tbody>
@forelse($trips as $trip)<tr><td><strong>{{$trip->user?->name}}</strong><br>{{$trip->purpose}}</td><td>{{$trip->departure_at->format('d.m.Y H:i')}}<br>{{optional($trip->return_at)->format('d.m.Y H:i') ?: '—'}}<br><span class="hr-badge">{{$trip->days}} dni</span></td><td>{{$trip->origin}} → {{$trip->destination}}<br><small>{{$trip->distance_km !== null ? number_format((float)$trip->distance_km,1,',',' ').' km' : 'przebieg niepodany'}} · {{$trip->travel_hours !== null ? number_format((float)$trip->travel_hours,1,',',' ').' godz.' : 'czas niepodany'}}</small></td><td>{{$trip->vehicle_type==='company'?'Służbowy':'Prywatny'}}<br><small>{{collect([$trip->vehicle_name,$trip->registration_number])->filter()->implode(' · ') ?: '—'}}</small></td><td>{{number_format((float)$trip->toll_cost,2,',',' ')}} zł</td><td><form method="POST" action="{{route('hr.delegations.destroy',$trip)}}" onsubmit="return confirm('Usunąć delegację?')">@csrf @method('DELETE')<button class="hr-btn danger"><i class="ti ti-trash"></i></button></form></td></tr>@empty<tr><td colspan="6" class="hr-empty">Brak delegacji.</td></tr>@endforelse
</tbody></table></div></div>
@elseif($tab==='attendance')
<div class="hr-card"><div class="hr-card-head"><strong>Lista obecności</strong><button class="hr-btn" onclick="openHrModal('attendance-modal')"><i class="ti ti-plus"></i> Dodaj wpis</button></div><div style="overflow:auto"><table class="hr-table"><thead><tr><th>Pracownik</th><th>Data</th><th>Status</th><th>Godziny</th><th>Notatki</th><th></th></tr></thead><tbody>
@php($statuses=['present'=>'Obecny','remote'=>'Praca zdalna','leave'=>'Urlop','sick'=>'Chorobowe','absent'=>'Nieobecny'])
@forelse($attendances as $entry)<tr><td><strong>{{$entry->user?->name}}</strong></td><td>{{$entry->work_date->format('d.m.Y')}}</td><td><span class="hr-badge">{{$statuses[$entry->status] ?? $entry->status}}</span></td><td>{{substr((string)$entry->started_at,0,5)}} – {{substr((string)$entry->finished_at,0,5)}}</td><td>{{$entry->notes ?: '—'}}</td><td><form method="POST" action="{{route('hr.attendance.destroy',$entry)}}" onsubmit="return confirm('Usunąć wpis?')">@csrf @method('DELETE')<button class="hr-btn danger"><i class="ti ti-trash"></i></button></form></td></tr>@empty<tr><td colspan="6" class="hr-empty">Brak wpisów obecności.</td></tr>@endforelse
</tbody></table></div></div>
@else
<div class="hr-card"><div class="hr-card-head"><strong>Samochody służbowe i prywatne</strong><button class="hr-btn" onclick="openHrModal('vehicle-modal')"><i class="ti ti-plus"></i> Dodaj samochód</button></div><div style="overflow:auto"><table class="hr-table"><thead><tr><th>Typ</th><th>Nazwa</th><th>Marka / model</th><th>Nr rejestracyjny</th><th>Użytkownik</th><th></th></tr></thead><tbody>
@forelse($vehicles as $vehicle)<tr><td><span class="hr-badge">{{$vehicle->type==='company'?'Służbowy':'Prywatny'}}</span></td><td><strong>{{$vehicle->name}}</strong></td><td>{{$vehicle->make_model ?: '—'}}</td><td>{{$vehicle->registration_number}}</td><td>{{$vehicle->user?->name ?: 'Samochód firmowy'}}</td><td>@if($vehicle->user_id===auth()->id() || $canTeam)<form method="POST" action="{{route('hr.vehicles.destroy',$vehicle)}}" onsubmit="return confirm('Usunąć samochód z listy?')">@csrf @method('DELETE')<button class="hr-btn danger"><i class="ti ti-trash"></i></button></form>@endif</td></tr>@empty<tr><td colspan="6" class="hr-empty">Brak samochodów.</td></tr>@endforelse
</tbody></table></div></div>
@endif

@include('hr.partials.modals')
<script>function openHrModal(id){document.getElementById(id)?.classList.add('open')}function closeHrModal(id){document.getElementById(id)?.classList.remove('open')}function chooseHrVehicle(select){const option=select.selectedOptions[0];if(!option?.value)return;document.getElementById('trip-vehicle-type').value=option.dataset.type;document.getElementById('trip-vehicle-name').value=option.dataset.name;document.getElementById('trip-registration').value=option.dataset.registration}function calculateTripReturn(){const departure=document.getElementById('trip-departure');const hours=document.getElementById('trip-hours');const arrival=document.getElementById('trip-return');if(!departure.value||!hours.value||arrival.value)return;const date=new Date(departure.value);date.setMinutes(date.getMinutes()+Math.round(Number(hours.value)*60));const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);arrival.value=local.toISOString().slice(0,16)}</script>
@endsection
