@extends('layouts.app')
@section('title','HR')
@section('page-title','HR')
@section('content')
<style>
.hr-head,.hr-tabs,.hr-actions{display:flex;align-items:center;gap:10px}.hr-head{justify-content:space-between;margin-bottom:18px;flex-wrap:wrap}.hr-tabs{border-bottom:2px solid #e5e1d8;margin-bottom:18px;flex-wrap:wrap}.hr-tab{padding:10px 16px;margin-bottom:-2px;text-decoration:none;color:#778078;font-size:13px;font-weight:700;border-bottom:2px solid transparent}.hr-tab.active{color:var(--green);border-color:var(--green)}.hr-card{background:#fff;border:1px solid #e5e1d8;border-radius:12px;overflow:hidden}.hr-card-head{padding:14px 18px;background:#fafaf6;border-bottom:1px solid #eee;display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.hr-table{width:100%;border-collapse:collapse;font-size:13px}.hr-table th,.hr-table td{padding:11px 13px;text-align:left;border-bottom:1px solid #f1eee8;vertical-align:top}.hr-table th{font-size:10px;text-transform:uppercase;color:#7b827d;background:#fafaf6}.hr-btn{border:0;border-radius:7px;padding:9px 13px;background:var(--green);color:#fff;font-weight:700;cursor:pointer;text-decoration:none}.hr-btn.danger{background:#fee2e2;color:#991b1b;padding:6px 9px}.hr-filter,.hr-input{padding:9px 10px;border:1px solid #cec8bc;border-radius:7px;background:#fff}.hr-modal{display:none;position:fixed;inset:0;z-index:9000;background:rgba(0,0,0,.5);align-items:center;justify-content:center;padding:18px}.hr-modal.open{display:flex}.hr-modal-card{background:#fff;border-radius:14px;width:min(820px,100%);max-height:92vh;overflow:auto;padding:24px}.hr-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.hr-field label{display:block;font-size:11px;font-weight:700;margin-bottom:4px}.hr-field input,.hr-field select,.hr-field textarea{width:100%;box-sizing:border-box;padding:9px 10px;border:1px solid #cec8bc;border-radius:7px}.hr-full{grid-column:1/-1}.hr-empty{text-align:center;padding:42px;color:#89918c}.hr-badge{display:inline-block;padding:3px 8px;border-radius:99px;background:#eef6f1;color:var(--green);font-size:11px;font-weight:700}@media(max-width:700px){.hr-grid{grid-template-columns:1fr}.hr-full{grid-column:auto}.hr-table{min-width:850px}}
</style>
<style>.hr-route-fields[hidden],.hr-route-map[hidden],#trip-other-vehicle-fields[hidden]{display:none}.hr-date-time,.hr-duration{display:grid;grid-template-columns:minmax(140px,1fr) 100px;gap:7px}.hr-duration{grid-template-columns:120px 100px}.hr-costs-row{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.hr-rate-info{padding:10px 12px;background:#f7f7f3;border-radius:8px;color:#616963;font-size:12px}.hr-private-car-check{display:flex;align-items:center;gap:10px;padding:9px 11px;border:1px solid #cec8bc;border-radius:7px;cursor:pointer}.hr-private-car-check input{width:auto}.hr-private-car-check small{display:block;color:#6b7280;font-size:11px}.hr-route-map{margin-top:6px}.hr-route-map strong{display:block;margin-bottom:8px}.hr-route-map iframe{display:block;width:100%;height:340px;border:0;border-radius:10px;background:#f3f4f6}@media(max-width:700px){.hr-route-map iframe{height:260px}.hr-date-time,.hr-duration{grid-template-columns:minmax(130px,1fr) 95px}.hr-costs-row{grid-template-columns:1fr}}</style>
<div class="hr-head"><div><h1 style="margin:0;color:var(--green)"><i class="ti ti-users-group"></i> HR</h1><div style="font-size:12px;color:#7b827d;margin-top:4px">Delegacje, obecność i samochody pracowników.</div></div>
 <div class="hr-actions">@if($canManageHrSettings)<button type="button" class="hr-btn" onclick="openHrModal('hr-settings-modal')"><i class="ti ti-settings"></i> Ustawienia HR</button>@endif
 @if($canTeam)<form method="GET" action="{{route('hr.index')}}"><input type="hidden" name="tab" value="{{$tab}}"><select class="hr-filter" name="user_id" onchange="this.form.submit()"><option value="">Wszyscy użytkownicy</option>@foreach($users as $person)<option value="{{$person->id}}" @selected(request('user_id')==$person->id)>{{$person->name}}</option>@endforeach</select></form>@endif
</div>
</div>
@if(session('success'))<div style="padding:11px 14px;background:#ecfdf5;color:#166534;border-radius:8px;margin-bottom:14px">{{session('success')}}</div>@endif
@if($errors->any())<div style="padding:11px 14px;background:#fef2f2;color:#991b1b;border-radius:8px;margin-bottom:14px">{{$errors->first()}}</div>@endif
<div class="hr-tabs">
 @if($canDelegations)<a class="hr-tab {{$tab==='delegations'?'active':''}}" href="{{route('hr.index',['tab'=>'delegations'])}}"><i class="ti ti-map-pin"></i> Delegacje</a>@endif
 @if($canDelegations)<a class="hr-tab {{$tab==='leaves'?'active':''}}" href="{{route('hr.index',['tab'=>'leaves'])}}"><i class="ti ti-calendar-off"></i> Urlopy / L4</a>@endif
 @if($canAttendance)<a class="hr-tab {{$tab==='attendance'?'active':''}}" href="{{route('hr.index',['tab'=>'attendance'])}}"><i class="ti ti-calendar-check"></i> Lista obecności</a>@endif
 @if($canDelegations)<a class="hr-tab {{$tab==='vehicles'?'active':''}}" href="{{route('hr.index',['tab'=>'vehicles'])}}"><i class="ti ti-car"></i> Samochody</a>@endif
</div>

@if($tab==='delegations')
<div class="hr-card"><div class="hr-card-head"><strong>Delegacje {{$canTeam ? 'pracowników' : '— moje'}}</strong><button class="hr-btn" onclick="openNewTrip()"><i class="ti ti-plus"></i> Dodaj delegację</button></div><div style="overflow:auto"><table class="hr-table"><thead><tr><th>Pracownik / cel</th><th>Podróż</th><th>Trasa</th><th>Samochód</th><th>Rozliczenie</th><th>Akcje</th></tr></thead><tbody>
@forelse($trips as $trip)@php($tripPayload=['id'=>$trip->id,'user_id'=>$trip->user_id,'purpose'=>$trip->purpose,'departure_at'=>$trip->departure_at?->format('Y-m-d\TH:i'),'outbound_arrival_at'=>$trip->outbound_arrival_at?->format('Y-m-d\TH:i'),'return_departure_at'=>$trip->return_departure_at?->format('Y-m-d\TH:i'),'return_at'=>$trip->return_at?->format('Y-m-d\TH:i'),'outbound_travel_hours'=>$trip->outbound_travel_hours,'return_travel_hours'=>$trip->return_travel_hours,'origin'=>$trip->origin,'destination'=>$trip->destination,'distance_km'=>$trip->distance_km,'km_rate'=>$trip->km_rate,'diet_rate'=>$trip->diet_rate,'vehicle_id'=>$trip->vehicle_id,'vehicle_type'=>$trip->vehicle_type,'vehicle_name'=>$trip->vehicle_name,'registration_number'=>$trip->registration_number,'toll_cost'=>$trip->toll_cost,'notes'=>$trip->notes])<tr><td><strong>{{$trip->user?->name}}</strong><br>{{$trip->purpose}}</td><td><strong>Tam:</strong> {{$trip->departure_at->format('d.m.Y H:i')}} → {{optional($trip->outbound_arrival_at)->format('d.m.Y H:i') ?: '—'}}<br><strong>Powrót:</strong> {{optional($trip->return_departure_at)->format('d.m.Y H:i') ?: '—'}} → {{optional($trip->return_at)->format('d.m.Y H:i') ?: '—'}}<br><span class="hr-badge">{{$trip->days}} dni · {{number_format((float)$trip->travel_hours,2,',',' ')}} godz. jazdy</span></td><td>{{$trip->origin}} → {{$trip->destination}}<br><small>{{$trip->distance_km !== null ? number_format((float)$trip->distance_km,1,',',' ').' km' : 'przebieg niepodany'}}</small></td><td>{{$trip->vehicle_type==='company'?'Służbowy':'Prywatny'}}<br><small>{{collect([$trip->vehicle_name,$trip->registration_number])->filter()->implode(' · ') ?: '—'}}</small></td><td>Dieta: {{number_format((float)$trip->diet_amount,2,',',' ')}} zł<br>Kilometrówka: {{number_format((float)$trip->mileage_amount,2,',',' ')}} zł<br><strong>Razem: {{number_format((float)$trip->total_amount,2,',',' ')}} zł</strong></td><td><div class="hr-actions"><a class="hr-btn" href="{{route('hr.delegations.show',$trip)}}" title="Podgląd rozliczenia"><i class="ti ti-eye"></i></a><button type="button" class="hr-btn" onclick="editTrip(@js($tripPayload))" title="Edytuj"><i class="ti ti-pencil"></i></button><a class="hr-btn" href="{{route('hr.delegations.pdf',$trip)}}" title="Pobierz PDF"><i class="ti ti-file-type-pdf"></i></a><form method="POST" action="{{route('hr.delegations.destroy',$trip)}}" onsubmit="return confirm('Usunąć delegację?')">@csrf @method('DELETE')<button class="hr-btn danger"><i class="ti ti-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="6" class="hr-empty">Brak delegacji.</td></tr>@endforelse
</tbody></table></div></div>
@elseif($tab==='leaves')
<div class="hr-card"><div class="hr-card-head"><strong>Urlopy i nieobecności {{$canTeam ? 'pracowników' : '— moje'}}</strong><button class="hr-btn" onclick="openNewLeave()"><i class="ti ti-plus"></i> Dodaj urlop / L4</button></div><div style="overflow:auto"><table class="hr-table"><thead><tr><th>Pracownik</th><th>Rodzaj</th><th>Termin</th><th>Liczba dni</th><th>Uwagi</th><th>Akcje</th></tr></thead><tbody>
@forelse($leaves as $leave)@php($leavePayload=['id'=>$leave->id,'user_id'=>$leave->user_id,'type'=>$leave->type,'start_date'=>$leave->start_date->toDateString(),'days'=>$leave->days,'notes'=>$leave->notes])<tr><td><strong>{{$leave->user?->name}}</strong></td><td><span class="hr-badge">{{\App\Models\HrLeave::TYPES[$leave->type] ?? $leave->type}}</span></td><td>{{$leave->start_date->format('d.m.Y')}} – {{$leave->end_date->format('d.m.Y')}}</td><td>{{$leave->days}}</td><td>{{$leave->notes ?: '—'}}</td><td><div class="hr-actions"><button type="button" class="hr-btn" title="Edytuj" onclick="editLeave(@js($leavePayload))"><i class="ti ti-pencil"></i></button><form method="POST" action="{{route('hr.leaves.destroy',$leave)}}" onsubmit="return confirm('Usunąć tę nieobecność?')">@csrf @method('DELETE')<button class="hr-btn danger" title="Usuń"><i class="ti ti-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="6" class="hr-empty">Nie ma jeszcze zapisanych urlopów ani zwolnień chorobowych.</td></tr>@endforelse
</tbody></table></div></div>
@elseif($tab==='attendance')
<div class="hr-card"><div class="hr-card-head"><strong>Lista obecności</strong><button class="hr-btn" onclick="openHrModal('attendance-modal')"><i class="ti ti-plus"></i> Dodaj wpis</button></div><div style="overflow:auto"><table class="hr-table"><thead><tr><th>Pracownik</th><th>Data</th><th>Status</th><th>Godziny</th><th>Notatki</th><th></th></tr></thead><tbody>
@php($statuses=['present'=>'Obecny','remote'=>'Praca zdalna','leave'=>'Urlop','sick'=>'Chorobowe','absent'=>'Nieobecny'])
@forelse($attendances as $entry)<tr><td><strong>{{$entry->user?->name}}</strong></td><td>{{$entry->work_date->format('d.m.Y')}}</td><td><span class="hr-badge">{{$statuses[$entry->status] ?? $entry->status}}</span></td><td>{{substr((string)$entry->started_at,0,5)}} – {{substr((string)$entry->finished_at,0,5)}}</td><td>{{$entry->notes ?: '—'}}</td><td><form method="POST" action="{{route('hr.attendance.destroy',$entry)}}" onsubmit="return confirm('Usunąć wpis?')">@csrf @method('DELETE')<button class="hr-btn danger"><i class="ti ti-trash"></i></button></form></td></tr>@empty<tr><td colspan="6" class="hr-empty">Brak wpisów obecności.</td></tr>@endforelse
</tbody></table></div></div>
@else
<div class="hr-card"><div class="hr-card-head"><strong>Samochody służbowe i prywatne</strong><button class="hr-btn" onclick="openHrModal('vehicle-modal')"><i class="ti ti-plus"></i> Dodaj samochód</button></div><div style="overflow:auto"><table class="hr-table"><thead><tr><th>Typ</th><th>Nazwa</th><th>Marka / model</th><th>Nr rejestracyjny</th><th>Użytkownik</th><th></th></tr></thead><tbody>
@forelse($vehicles as $vehicle)<tr><td><span class="hr-badge">{{$vehicle->type==='company'?'Służbowy':'Prywatny'}}</span></td><td><strong>{{$vehicle->name}}</strong></td><td>{{$vehicle->make_model ?: '—'}}</td><td>{{$vehicle->registration_number}}</td><td>{{$vehicle->user?->name ?: 'Samochód firmowy'}}</td><td>@if($vehicle->user_id===auth()->id() || $canTeam)<form method="POST" action="{{route('hr.vehicles.destroy',$vehicle)}}" onsubmit="return confirm('Usunąć samochód z listy?')">@csrf @method('DELETE')<button class="hr-btn danger"><i class="ti ti-trash"></i></button></form>@endif</td></tr>@empty<tr><td colspan="6" class="hr-empty">Brak samochodów.</td></tr>@endforelse
</tbody></table></div></div>
@endif

@include('hr.partials.modals')
<script>
function openHrModal(id){document.getElementById(id)?.classList.add('open')}
function closeHrModal(id){document.getElementById(id)?.classList.remove('open')}
function openNewLeave(){const form=document.getElementById('leave-form');form.reset();form.action=@js(route('hr.leaves.store'));document.getElementById('leave-method').disabled=true;document.getElementById('leave-modal-title').textContent='Nowy urlop / L4';document.getElementById('leave-start-date').value=localDateValue(new Date()).slice(0,10);openHrModal('leave-modal')}
function editLeave(leave){openNewLeave();['user_id','type','start_date','days','notes'].forEach(key=>{const field=document.getElementById(`leave-${key.replaceAll('_','-')}`);if(field)field.value=leave[key]??''});document.getElementById('leave-form').action=`{{url('/hr/leaves')}}/${leave.id}`;document.getElementById('leave-method').disabled=false;document.getElementById('leave-modal-title').textContent='Edytuj urlop / L4'}
function chooseHrVehicle(select){const manual=select.value==='manual';document.getElementById('trip-other-vehicle-fields').hidden=!manual;['trip-vehicle-type','trip-private-vehicle','trip-vehicle-name','trip-registration','trip-remember-vehicle'].forEach(id=>{document.getElementById(id).disabled=!manual});if(manual)syncManualVehicleType();updateTripSummary()}
function syncManualVehicleType(){document.getElementById('trip-vehicle-type').value=document.getElementById('trip-private-vehicle').checked?'private':'company';updateTripSummary()}
function localDateValue(date){const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
function tripFields(direction){return direction==='outbound'?{start:document.getElementById('trip-departure'),end:document.getElementById('trip-outbound-arrival'),hours:document.getElementById('trip-outbound-hours')}:{start:document.getElementById('trip-return-departure'),end:document.getElementById('trip-return'),hours:document.getElementById('trip-return-hours')}}
const tripDateParts={departure:['trip-departure','trip-departure-date','trip-departure-time'],'return-departure':['trip-return-departure','trip-return-departure-date','trip-return-departure-time'],'outbound-arrival':['trip-outbound-arrival','trip-outbound-arrival-date','trip-outbound-arrival-time'],'return-arrival':['trip-return','trip-return-date','trip-return-time']}
function syncTripDateTime(key){const [hiddenId,dateId,timeId]=tripDateParts[key],date=document.getElementById(dateId).value,time=document.getElementById(timeId).value;document.getElementById(hiddenId).value=date&&time?`${date}T${time}`:'';if(key==='departure')hoursToArrival('outbound');if(key==='return-departure')hoursToArrival('return');updateTripSummary()}
function showDateTimeParts(key){const [hiddenId,dateId,timeId]=tripDateParts[key],value=document.getElementById(hiddenId).value;if(!value)return;const [date,time]=value.split('T');document.getElementById(dateId).value=date;document.getElementById(timeId).value=(time||'00:00').slice(0,5)}
function syncDurationParts(direction){const value=Math.max(0,Number(document.getElementById(`trip-${direction}-hours`).value||0)),minutes=Math.round(value*4)*15;document.getElementById(`trip-${direction}-hours-part`).value=Math.floor(minutes/60);document.getElementById(`trip-${direction}-minutes-part`).value=minutes%60}
function syncTravelDuration(direction){const hours=Number(document.getElementById(`trip-${direction}-hours-part`).value),minutes=Number(document.getElementById(`trip-${direction}-minutes-part`).value);document.getElementById(`trip-${direction}-hours`).value=(hours+minutes/60).toFixed(2);hoursToArrival(direction)}
function datesToHours(direction){const f=tripFields(direction);if(f.start.value&&f.end.value){const minutes=Math.max(0,Math.round((new Date(f.end.value)-new Date(f.start.value))/900000)*15);f.hours.value=(minutes/60).toFixed(2);syncDurationParts(direction)}updateTripSummary()}
function hoursToArrival(direction){const f=tripFields(direction);if(f.start.value&&f.hours.value!==''){const date=new Date(f.start.value);date.setMinutes(date.getMinutes()+Math.round(Number(f.hours.value)*4)*15);f.end.value=localDateValue(date);showDateTimeParts(direction==='outbound'?'outbound-arrival':'return-arrival')}updateTripSummary()}
function dietAmount(minutes,rate){if(minutes<=1440)return minutes<480?0:(minutes<=720?rate/2:rate);const days=Math.floor(minutes/1440),rem=minutes%1440;return rate*(days+(rem===0?0:(rem<=480 ? .5 : 1)))}
function updateTripSummary(){const start=document.getElementById('trip-departure').value,end=document.getElementById('trip-return').value,rate=Number(document.getElementById('trip-diet-rate').value||0),km=Number(document.getElementById('trip-distance').value||0),kmRate=Number(document.getElementById('trip-km-rate').value||0),toll=Number(document.getElementById('trip-toll').value||0),hotel=Number(document.getElementById('trip-accommodation').value||0),other=Number(document.getElementById('trip-other-cost').value||0),vehicle=document.getElementById('trip-vehicle-id'),selected=vehicle.options[vehicle.selectedIndex],vehicleType=vehicle.value==='manual'?document.getElementById('trip-vehicle-type').value:selected?.dataset.type,isPrivate=vehicleType==='private';if(!start||!end)return;const minutes=Math.max(0,(new Date(end)-new Date(start))/60000),diet=dietAmount(minutes,rate),mileage=isPrivate?km*kmRate:0;document.getElementById('trip-calculation').textContent=`Czas delegacji: ${(minutes/60).toFixed(2)} godz. · dieta: ${diet.toFixed(2)} zł · kilometrówka: ${mileage.toFixed(2)} zł${vehicleType==='company'?' (auto służbowe — bez kilometrówki)':''} · pozostałe koszty: ${(toll+hotel+other).toFixed(2)} zł · razem: ${(diet+mileage+toll+hotel+other).toFixed(2)} zł`}
function hideTripRouteDetails(){document.getElementById('trip-route-fields').hidden=true;document.getElementById('trip-route-map-wrap').hidden=true;document.getElementById('trip-route-map').removeAttribute('src')}
function showTripRouteDetails(){document.getElementById('trip-route-fields').hidden=false}
function showTripRouteMap(){const origin=document.getElementById('trip-origin').value.trim(),destination=document.getElementById('trip-destination').value.trim(),map=document.getElementById('trip-route-map'),wrap=document.getElementById('trip-route-map-wrap');if(!origin||!destination){wrap.hidden=true;return}map.src=`https://www.google.com/maps?output=embed&saddr=${encodeURIComponent(origin)}&daddr=${encodeURIComponent(destination)}&dirflg=d`;wrap.hidden=false}
function openNewTrip(){const form=document.getElementById('trip-form'),today=localDateValue(new Date()).slice(0,10);form.reset();form.action=@js(route('hr.delegations.store'));document.getElementById('trip-method').disabled=true;document.getElementById('trip-modal-title').textContent='Nowa delegacja';document.getElementById('trip-km-rate').value=@js($defaultKmRate);document.getElementById('trip-diet-rate').value=@js($defaultDietRate);document.getElementById('trip-origin').value=@js($defaultOrigin);document.getElementById('trip-departure-date').value=today;document.getElementById('trip-return-departure-date').value=today;document.getElementById('trip-departure-time').value='08:00';document.getElementById('trip-return-departure-time').value='16:00';syncTripDateTime('departure');syncTripDateTime('return-departure');document.getElementById('trip-route-status').textContent='';chooseHrVehicle(document.getElementById('trip-vehicle-id'));hideTripRouteDetails();openHrModal('trip-modal')}
const tripExtraCosts=@js($trips->mapWithKeys(fn($trip)=>[$trip->id=>['accommodation_cost'=>$trip->accommodation_cost,'other_cost'=>$trip->other_cost]]));
function editTrip(trip){trip={...trip,...(tripExtraCosts[trip.id]||{})};openNewTrip();const map={purpose:'trip-purpose',departure_at:'trip-departure',outbound_arrival_at:'trip-outbound-arrival',return_departure_at:'trip-return-departure',return_at:'trip-return',outbound_travel_hours:'trip-outbound-hours',return_travel_hours:'trip-return-hours',origin:'trip-origin',destination:'trip-destination',distance_km:'trip-distance',vehicle_id:'trip-vehicle-id',vehicle_type:'trip-vehicle-type',vehicle_name:'trip-vehicle-name',registration_number:'trip-registration',toll_cost:'trip-toll',accommodation_cost:'trip-accommodation',other_cost:'trip-other-cost',notes:'trip-notes',user_id:'trip-user-id'};Object.entries(map).forEach(([key,id])=>{const field=document.getElementById(id);if(field)field.value=trip[key]??''});if(!trip.vehicle_id){document.getElementById('trip-vehicle-id').value='manual';document.getElementById('trip-private-vehicle').checked=trip.vehicle_type==='private'}Object.keys(tripDateParts).forEach(showDateTimeParts);syncDurationParts('outbound');syncDurationParts('return');chooseHrVehicle(document.getElementById('trip-vehicle-id'));document.getElementById('trip-form').action=`{{url('/hr/delegations')}}/${trip.id}`;document.getElementById('trip-method').disabled=false;document.getElementById('trip-modal-title').textContent='Edytuj delegację';showTripRouteMap();updateTripSummary()}
async function calculateGoogleRoute(){const status=document.getElementById('trip-route-status'),origin=document.getElementById('trip-origin').value,destination=document.getElementById('trip-destination').value;if(!origin||!destination){status.textContent='Najpierw wpisz skąd i dokąd.';return}if(!document.getElementById('trip-departure').value||!document.getElementById('trip-return-departure').value){status.textContent='Uzupełnij daty i godziny wyjazdu oraz wyjazdu powrotnego.';return}showTripRouteDetails();showTripRouteMap();status.textContent='Wyliczam trasę…';try{const response=await fetch(@js(route('hr.route.calculate')),{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({origin,destination})});const data=await response.json();if(!response.ok)throw new Error(data.message);const roundedHours=Math.round(Number(data.hours)*4)/4;document.getElementById('trip-distance').value=(data.distance_km*2).toFixed(1);document.getElementById('trip-outbound-hours').value=roundedHours.toFixed(2);document.getElementById('trip-return-hours').value=roundedHours.toFixed(2);syncDurationParts('outbound');syncDurationParts('return');hoursToArrival('outbound');hoursToArrival('return');status.textContent=`Trasa w jedną stronę: ${data.distance_km} km, około ${Math.floor(roundedHours)} godz. ${Math.round((roundedHours%1)*60)} min.`}catch(error){status.textContent=(error.message||'Nie udało się wyliczyć trasy.')+' Uzupełnij pokazane pola ręcznie.'}}
function setupPlaceSuggestions(inputId,listId){const input=document.getElementById(inputId),list=document.getElementById(listId);let timer;input.addEventListener('input',()=>{clearTimeout(timer);const query=input.value.trim();if(query.length<3){list.replaceChildren();return}timer=setTimeout(async()=>{try{const response=await fetch(`${@js(route('hr.places.autocomplete'))}?q=${encodeURIComponent(query)}`,{headers:{Accept:'application/json'}}),data=await response.json();list.replaceChildren(...(data.suggestions||[]).map(text=>{const option=document.createElement('option');option.value=text;return option}))}catch(error){list.replaceChildren()}},250)})}
setupPlaceSuggestions('trip-origin','trip-origin-suggestions');setupPlaceSuggestions('trip-destination','trip-destination-suggestions');
</script>
@endsection
