<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><style>
@page{margin:34px 42px 38px}body{font-family:DejaVu Sans,sans-serif;color:#111;font-size:11px;line-height:1.45}.header{width:100%;border-collapse:collapse}.header td{width:50%;vertical-align:top}.employee{padding-top:42px}.employer{text-align:right}.employer img{display:block;max-width:105px;max-height:48px;margin:0 0 12px auto}.line{display:inline-block;min-width:245px;border-bottom:1px dotted #111;text-align:center;padding:0 4px 3px}.caption{margin-top:3px;font-size:9px}h1{margin:76px 0 34px;text-align:center;font-size:16px}.request{font-size:12px}.row{margin-top:16px}.value{border-bottom:1px dotted #111;padding:0 6px 2px}.signature-table{width:100%;margin-top:62px;border-collapse:collapse}.signature-table td{width:50%;text-align:center;vertical-align:bottom}.signature-space{height:54px}.signature-space img{max-width:190px;max-height:52px}.signature-line{display:inline-block;width:230px;border-bottom:1px dotted #111}.approval{margin-top:70px}.footer{position:fixed;bottom:0;left:0;right:0;color:#777;font-size:8px;text-align:center}
</style></head><body>
<table class="header"><tr><td class="employee"><span class="line">{{ $leave->user?->name }}</span><div class="caption">(imię i nazwisko pracownika)</div></td><td class="employer">@if($logo)<img src="{{ $logo }}" alt="Logo">@endif<span class="line">{{ $company?->name }}</span>@if($company?->address)<div>{{ $company->address }}</div>@endif @if($company?->nip)<div>NIP: {{ $company->nip }}</div>@endif<div class="caption">(pracodawca)</div></td></tr></table>
<h1>{{ in_array($leave->type, ['annual', 'on_demand'], true) ? 'Wniosek o urlop wypoczynkowy' : 'Wniosek o nieobecność' }}</h1>
<div class="request">Proszę o udzielenie {{ in_array($leave->type, ['annual', 'on_demand'], true) ? 'urlopu wypoczynkowego' : 'nieobecności' }} w terminie od <span class="value">{{ $leave->start_date->format('d.m.Y') }}</span> do <span class="value">{{ $leave->end_date->format('d.m.Y') }}</span>.</div>
<div class="row">Liczba dni: <span class="value">{{ $leave->days }}</span></div><div class="row">Data złożenia wniosku: <span class="value">{{ ($leave->document_date ?? $leave->created_at)->format('d.m.Y') }}</span></div><div class="row">Rodzaj nieobecności: <span class="value">{{ \App\Models\HrLeave::TYPES[$leave->type] ?? $leave->type }}</span></div>@if($leave->notes)<div class="row">Uwagi: <span class="value">{{ $leave->notes }}</span></div>@endif
<table class="signature-table"><tr><td></td><td><div class="signature-space">@if($leave->user?->signatureDataUri())<img src="{{ $leave->user->signatureDataUri() }}" alt="Podpis pracownika">@endif</div><span class="signature-line"></span><div class="caption">(podpis pracownika)</div></td></tr></table>
<div class="approval">Akceptacja przełożonego: <span class="line"></span></div><div class="footer">Dokument nr HR/U/{{ $leave->id }}/{{ $leave->start_date->format('Y') }}</div>
</body></html>
