<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><style>
@page{size:A5 portrait;margin:24px 28px 30px}body{font-family:DejaVu Sans,sans-serif;color:#111;font-size:9px;line-height:1.4}.header{width:100%;border-collapse:collapse}.header td{width:50%;vertical-align:top}.employee{padding-top:32px}.party-block{width:185px;text-align:center}.employer{text-align:right}.employer .party-block{display:inline-block}.employer img{display:block;max-width:92px;max-height:42px;margin:0 auto 9px}.party-value{font-weight:700;line-height:1.45}.company-address{margin-top:3px}.line{display:inline-block;min-width:175px;border-bottom:1px dotted #111;text-align:center;padding:0 4px 3px}.caption{margin-top:3px;font-size:8px;font-weight:400}h1{margin:50px 0 27px;text-align:center;font-size:14px}.request{font-size:9.5px}.row{margin-top:14px}.value{border-bottom:1px dotted #111;padding:0 5px 2px}.signature-table{width:100%;margin-top:46px;border-collapse:collapse}.signature-table td{width:50%;text-align:center;vertical-align:bottom}.signature-space{height:43px}.signature-space img{max-width:150px;max-height:41px}.signature-line{display:inline-block;width:155px;border-bottom:1px dotted #111}.approval{margin-top:52px}.footer{position:fixed;bottom:0;left:0;right:0;color:#777;font-size:7px;text-align:center}
</style></head><body>
<table class="header"><tr><td class="employee"><div class="party-block"><div class="party-value">{{ $leave->user?->name }}</div><div class="caption">(imię i nazwisko pracownika)</div></div></td><td class="employer"><div class="party-block">@if($logo)<img src="{{ $logo }}" alt="Logo">@endif<div class="party-value">{{ $company?->name }}</div>@if($company?->address)<div class="company-address">{{ $company->address }}</div>@endif @if($company?->nip)<div>NIP: {{ $company->nip }}</div>@endif<div class="caption">(pracodawca)</div></div></td></tr></table>
<h1>{{ in_array($leave->type, ['annual', 'on_demand'], true) ? 'Wniosek o urlop wypoczynkowy' : 'Wniosek o nieobecność' }}</h1>
<div class="request">Proszę o udzielenie {{ in_array($leave->type, ['annual', 'on_demand'], true) ? 'urlopu wypoczynkowego' : 'nieobecności' }} w terminie od <span class="value">{{ $leave->start_date->format('d.m.Y') }}</span> do <span class="value">{{ $leave->end_date->format('d.m.Y') }}</span>.</div>
<div class="row">Liczba dni: <span class="value">{{ $leave->days }}</span></div><div class="row">Data złożenia wniosku: <span class="value">{{ ($leave->document_date ?? $leave->created_at)->format('d.m.Y') }}</span></div><div class="row">Rodzaj nieobecności: <span class="value">{{ \App\Models\HrLeave::TYPES[$leave->type] ?? $leave->type }}</span></div>@if($leave->notes)<div class="row">Uwagi: <span class="value">{{ $leave->notes }}</span></div>@endif
<table class="signature-table"><tr><td></td><td><div class="signature-space">@if($leave->user?->signatureDataUri())<img src="{{ $leave->user->signatureDataUri() }}" alt="Podpis pracownika">@endif</div><span class="signature-line"></span><div class="caption">(podpis pracownika)</div></td></tr></table>
<div class="approval">Akceptacja przełożonego: <span class="line"></span></div><div class="footer">Dokument nr HR/U/{{ $leave->id }}/{{ $leave->start_date->format('Y') }}</div>
</body></html>
