<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><title>Polecenie wyjazdu służbowego</title>
<style>
@page{margin:28px 34px 30px}body{font-family:DejaVu Sans,sans-serif;color:#202b26;font-size:10px;line-height:1.3}table{width:100%;border-collapse:collapse;table-layout:fixed}td,th{padding:5px 7px;border:1px solid #9da9a2;text-align:left;vertical-align:top;overflow-wrap:break-word}th{font-weight:normal;background:#f1f4f2}.header td{border:0;padding:0 0 8px}.logo{text-align:right;width:25%}.logo img{max-width:120px;max-height:48px}.company{font-size:12px;font-weight:bold}.small{font-size:8px;color:#56645c}.title{text-align:center;border:1px solid #819087;padding:9px;margin:2px 0 10px}h1{font-size:19px;margin:0 0 4px;color:#1a4d3a}.muted{font-size:10px;color:#56645c}h2{font-size:10px;margin:0;padding:5px 8px;background:#e9eeeb;border:1px solid #9da9a2;border-bottom:0;text-transform:uppercase}.section{margin-top:9px}.keep{page-break-inside:avoid}.info th{width:20%}.signature-space{height:34px;text-align:center}.signature-line{border-top:1px dotted #66776d;padding-top:4px;font-size:8px;text-align:center}.signatures td{border:0;padding:5px 12px 0}.signatures img{max-width:150px;max-height:32px}.journey th{font-size:9px}.time{white-space:nowrap}.amount{text-align:right;white-space:nowrap}.total{font-weight:bold;background:#e9eeeb}.blank{display:inline-block;border-bottom:1px dotted #66776d;min-width:110px;height:12px}.note{white-space:pre-wrap;overflow-wrap:break-word;margin:6px 8px}.footer{position:fixed;bottom:-16px;font-size:8px;color:#68766e;text-align:center;width:100%}.confirmation{border:1px solid #9da9a2;padding:7px}
td,th{padding:3px 7px}h2{padding:4px 8px}.section{margin-top:7px}.title{padding:6px;margin-bottom:8px}.signature-space{height:30px}.confirmation{padding:5px 7px}
</style></head><body>
<table class="header"><tr><td><div class="company">{{$company?->name}}</div><div class="small">{{collect([$company?->address,trim(($company?->postcode ?? '').' '.($company?->city ?? ''))])->filter()->implode(', ')}}@if($company?->nip)<br>NIP: {{$company->nip}}@endif</div></td><td class="logo">@if($logo)<img src="{{$logo}}" alt="Logo firmy">@endif</td></tr></table>
<div class="title"><h1>Polecenie wyjazdu służbowego</h1><div class="muted">Polecenie wyjazdu nr HR/{{$trip->id}}/{{$trip->departure_at->format('Y')}}</div></div>
<section class="keep"><h2>I. Zlecenie wyjazdu</h2>
<table class="info"><tr><th>Osoba delegowana</th><td><strong>{{$trip->user?->name}}</strong></td></tr><tr><th>Miejsce wyjazdu</th><td>{{$trip->destination}}</td></tr><tr><th>Termin</th><td>od {{$trip->departure_at->format('d.m.Y H:i')}} do {{optional($trip->return_at)->format('d.m.Y H:i') ?: '................................'}}</td></tr><tr><th>Cel wyjazdu</th><td>{{$trip->purpose}}</td></tr><tr><th>Środek transportu</th><td>{{$trip->vehicle_type==='company'?'Samochód służbowy':'Samochód prywatny'}}@if($trip->vehicle_name) - {{$trip->vehicle_name}}@endif @if($trip->registration_number) · nr rej. {{$trip->registration_number}}@endif</td></tr></table>
<table class="signatures"><tr><td></td><td><div class="signature-space"></div><div class="signature-line">Podpis osoby zlecającej wyjazd</div></td></tr></table></section>
<section class="section keep"><h2>II. Przebieg i potwierdzenie odbycia podróży</h2>
<table class="journey"><thead><tr><th style="width:14%">Podróż</th><th style="width:29%">Wyjazd / miejscowość</th><th style="width:29%">Przyjazd / miejscowość</th><th style="width:16%">Czas jazdy</th></tr></thead><tbody>
<tr><th>Do celu</th><td><span class="time">{{$trip->departure_at->format('d.m.Y H:i')}}</span><br>{{$trip->origin}}</td><td><span class="time">{{optional($trip->outbound_arrival_at)->format('d.m.Y H:i') ?: '................................'}}</span><br>{{$trip->destination}}</td><td class="time">{{$trip->outbound_travel_hours !== null ? number_format((float)$trip->outbound_travel_hours,2,',',' ').' godz.' : '................'}}</td></tr>
<tr><th>Powrót</th><td><span class="time">{{optional($trip->return_departure_at)->format('d.m.Y H:i') ?: '................................'}}</span><br>{{$trip->destination}}</td><td><span class="time">{{optional($trip->return_at)->format('d.m.Y H:i') ?: '................................'}}</span><br>{{$trip->origin}}</td><td class="time">{{$trip->return_travel_hours !== null ? number_format((float)$trip->return_travel_hours,2,',',' ').' godz.' : '................'}}</td></tr>
</tbody></table>
<div class="confirmation">Potwierdzam odbycie podróży służbowej do: <strong>{{$trip->destination}}</strong>, zgodnie z powyższym przebiegiem.
<table class="signatures"><tr><td><div class="signature-space">@if($employeeSignature ?? null)<img src="{{$employeeSignature}}" alt="Podpis pracownika">@endif</div><div class="signature-line">Podpis delegowanego - potwierdzenie odbycia wyjazdu</div></td><td><div class="signature-space"></div><div class="signature-line">Potwierdzenie pobytu: podpis / pieczęć osoby potwierdzającej</div></td></tr></table></div></section>
<section class="section keep"><h2>III. Rachunek kosztów podróży</h2>
<table><tr><td>Przebieg: {{$trip->distance_km !== null ? number_format((float)$trip->distance_km,1,',',' ').' km' : 'nie podano'}}</td><td>Stawka za kilometr: {{$trip->vehicle_type==='company' ? 'nie dotyczy (samochód służbowy)' : number_format((float)$trip->km_rate,2,',',' ').' zł/km'}}</td></tr></table>
<table><tr><td>Kilometrówka</td><td class="amount">{{number_format((float)$trip->mileage_amount,2,',',' ')}} zł</td></tr><tr><td>Dieta</td><td class="amount">{{number_format((float)$trip->diet_amount,2,',',' ')}} zł</td></tr><tr><td>Autostrady / opłaty drogowe</td><td class="amount">{{number_format((float)$trip->toll_cost,2,',',' ')}} zł</td></tr><tr><td>Noclegi</td><td class="amount">{{number_format((float)$trip->accommodation_cost,2,',',' ')}} zł</td></tr><tr><td>Inne koszty</td><td class="amount">{{number_format((float)$trip->other_cost,2,',',' ')}} zł</td></tr><tr class="total"><td>Razem koszty podróży</td><td class="amount">{{number_format((float)$trip->total_amount,2,',',' ')}} zł</td></tr></table>
<div class="confirmation">Pobrana zaliczka: <span class="blank"></span> zł &nbsp; Do wypłaty / zwrotu: <span class="blank"></span> zł<br><span class="small">Pola uzupełnia osoba rozliczająca delegację.</span></div></section>
<section class="section keep"><h2>IV. Kontrola i zatwierdzenie rozliczenia</h2><div class="confirmation">Rachunek sprawdzono pod względem formalnym i rachunkowym.
<table class="signatures"><tr><td><div class="signature-space"></div><div class="signature-line">Podpis osoby sprawdzającej</div></td><td><div class="signature-space"></div><div class="signature-line">Podpis zatwierdzającego rozliczenie</div></td></tr></table></div></section>
<section class="section keep"><h2>V. Potwierdzenie odbioru środków (jeżeli dotyczy)</h2><div class="confirmation">Kwota otrzymana: <span class="blank"></span> zł &nbsp; Data odbioru: <span class="blank"></span><br>Słownie: ...................................................................................................................................................
<table class="signatures"><tr><td></td><td><div class="signature-space" style="height:24px"></div><div class="signature-line">Podpis delegowanego - odbiór środków</div></td></tr></table></div></section>
@if($trip->notes)<section class="section"><h2>Uwagi / załączniki</h2><p class="note">{{$trip->notes}}</p></section>@endif
<div class="footer">{{$company?->name}} · HR/{{$trip->id}}/{{$trip->departure_at->format('Y')}}</div>
</body></html>
