<!doctype html><html lang="pl"><head><meta charset="utf-8"><style>
@page{margin:28px 34px}body{font-family:DejaVu Sans,sans-serif;color:#1f2937;font-size:11px}h1{font-size:20px;color:#1A4D3A;margin:0 0 4px}.muted{color:#6b7280}.section{margin-top:18px}.section h2{font-size:12px;text-transform:uppercase;color:#1A4D3A;border-bottom:1px solid #b9c9c0;padding-bottom:5px}table{width:100%;border-collapse:collapse}td,th{padding:7px 8px;border:1px solid #d9ddd9;text-align:left;vertical-align:top}th{background:#eef4f0;width:28%}.amount{font-size:16px;font-weight:bold;color:#1A4D3A;text-align:right}.footer{position:fixed;bottom:0;left:0;right:0;font-size:9px;color:#777;text-align:center}
</style></head><body>
<h1>Rozliczenie delegacji krajowej</h1><div class="muted">Nr {{$trip->id}} · wygenerowano {{now()->format('d.m.Y H:i')}}</div>
<div class="section"><h2>Dane pracownika i cel</h2><table><tr><th>Pracownik</th><td>{{$trip->user?->name}}</td></tr><tr><th>Cel wyjazdu</th><td>{{$trip->purpose}}</td></tr><tr><th>Trasa</th><td>{{$trip->origin}} → {{$trip->destination}} → {{$trip->origin}}</td></tr></table></div>
<div class="section"><h2>Przebieg podróży</h2><table><tr><th>Wyjazd</th><td>{{$trip->departure_at->format('d.m.Y H:i')}}</td><th>Przyjazd do celu</th><td>{{optional($trip->outbound_arrival_at)->format('d.m.Y H:i')}}</td></tr><tr><th>Czas jazdy do celu</th><td>{{number_format((float)$trip->outbound_travel_hours,2,',',' ')}} godz.</td><th>Wyjazd powrotny</th><td>{{optional($trip->return_departure_at)->format('d.m.Y H:i')}}</td></tr><tr><th>Powrót</th><td>{{optional($trip->return_at)->format('d.m.Y H:i')}}</td><th>Czas jazdy powrotnej</th><td>{{number_format((float)$trip->return_travel_hours,2,',',' ')}} godz.</td></tr></table></div>
<div class="section"><h2>Pojazd</h2><table><tr><th>Rodzaj</th><td>{{$trip->vehicle_type==='company'?'Służbowy':'Prywatny'}}</td><th>Samochód</th><td>{{collect([$trip->vehicle_name,$trip->registration_number])->filter()->implode(' · ') ?: '—'}}</td></tr><tr><th>Łączny przebieg</th><td>{{number_format((float)$trip->distance_km,1,',',' ')}} km</td><th>Stawka za km</th><td>{{number_format((float)$trip->km_rate,4,',',' ')}} zł</td></tr></table></div>
<div class="section"><h2>Rozliczenie</h2><table><tr><th>Kilometrówka</th><td>{{number_format((float)$trip->mileage_amount,2,',',' ')}} zł</td></tr><tr><th>Dieta</th><td>{{number_format((float)$trip->diet_amount,2,',',' ')}} zł (stawka pełna {{number_format((float)$trip->diet_rate,2,',',' ')}} zł)</td></tr><tr><th>Koszty autostradowe</th><td>{{number_format((float)$trip->toll_cost,2,',',' ')}} zł</td></tr><tr><th>Łącznie</th><td class="amount">{{number_format((float)$trip->total_amount,2,',',' ')}} zł</td></tr></table></div>
@if($trip->notes)<div class="section"><h2>Notatki</h2><p>{{$trip->notes}}</p></div>@endif
<div class="section" style="margin-top:45px"><table><tr><td style="border:0;text-align:center;width:45%">........................................................<br>podpis pracownika</td><td style="border:0;width:10%"></td><td style="border:0;text-align:center;width:45%">........................................................<br>zatwierdzenie</td></tr></table></div>
<div class="footer">Dokument wygenerowany w systemie {{$trip->created_at?->format('d.m.Y H:i')}}</div>
</body></html>
