<!doctype html><html lang="pl"><head><meta charset="utf-8"><style>
@page{margin:17mm}body{font-family:DejaVu Sans,sans-serif;color:#26352d;font-size:9pt;line-height:1.42}h1{font-size:18pt;color:#174c38;margin:2px 0 3px}h2{font-size:12pt;color:#174c38;margin:18px 0 7px}.tag{font-weight:bold;color:#19704b}.meta{color:#637168;border-bottom:2px solid #174c38;padding-bottom:9px}.info{margin:12px 0}table{border-collapse:collapse;width:100%;font-size:7.7pt;margin:5px 0 10px}th{background:#174c38;color:#fff;text-align:left;padding:5px}td{border:1px solid #d9e0db;padding:5px;vertical-align:top}.swot td:first-child{width:22%;font-weight:bold;background:#f3f7f4}.foot{margin-top:22px;border-top:1px solid #ddd;padding-top:7px;color:#718078;font-size:7.5pt}
</style></head><body>
<div class="tag">D-EnMS-KON-01</div><h1>Kontekst organizacji i strony zainteresowane</h1><div class="meta">PN-EN ISO 50001:2018 · klauzule 4.1 i 4.2</div>
<div class="info"><b>Organizacja:</b> {{ data_get($answers, 'facts.organization', $audit->company->name) ?: $audit->company->name }}<br><b>Zakres systemu:</b> {{ data_get($answers, 'facts.scope') ?: 'Do uzupełnienia' }}<br><b>Data opracowania:</b> {{ now()->format('d.m.Y') }}</div>
<h2>1. Cel dokumentu</h2><p>Dokument identyfikuje czynniki wewnętrzne i zewnętrzne wpływające na zdolność organizacji do osiągania zamierzonych wyników systemu zarządzania energią oraz stanowi wejście do określenia zakresu, ryzyk, szans i celów energetycznych.</p>
<h2>2. Czynniki kontekstowe</h2><table><thead><tr><th>Obszar</th><th>Zidentyfikowany czynnik</th><th>Wpływ</th><th>Skutek dla systemu</th></tr></thead><tbody>@foreach($factors as $factor)<tr><td>{{ $factor['area'] }}</td><td>{{ $factor['text'] }}</td><td>{{ $factor['impact'] }}</td><td>{{ $factor['effect'] }}</td></tr>@endforeach</tbody></table>
<h2>3. Synteza — analiza SWOT</h2><table class="swot">@foreach(config('iso50001-context.swot') as $key=>$label)<tr><td>{{ $label }}</td><td>{!! nl2br(e(data_get($answers, 'swot.'.$key) ?: '[do uzupełnienia]')) !!}</td></tr>@endforeach</table>
<h2>4. Strony zainteresowane</h2><table><tr><th>Strona</th><th>Wymagania i oczekiwania</th><th>Wymóg zgodności</th></tr><tr><td>Zarząd</td><td>Ograniczenie kosztów energii i przewidywalność wydatków</td><td>Nie</td></tr><tr><td>Pracownicy i utrzymanie ruchu</td><td>Jasne zasady eksploatacji, bezpieczna praca i dostęp do danych</td><td>Do oceny</td></tr><tr><td>Organy regulacyjne</td><td>Spełnienie wymagań prawnych efektywności energetycznej</td><td>Tak</td></tr><tr><td>Odbiorcy</td><td>{{ data_get($answers, 'facts.customers_co2') === 'tak' ? 'Informacja o śladzie węglowym i efektywności' : 'Brak zgłoszonych wymagań energetycznych' }}</td><td>Do oceny</td></tr><tr><td>Jednostka certyfikująca</td><td>Kompletność i dostępność zapisów systemowych</td><td>Tak</td></tr></table>
<h2>5. Wnioski i decyzje projektowe</h2><table><tr><th>Lp.</th><th>Wniosek</th><th>Decyzja projektowa</th><th>Dokument</th></tr>@foreach(data_get($answers, 'conclusions', []) as $index=>$row)<tr><td>{{ $index+1 }}</td><td>{{ $row['finding'] ?: '[do uzupełnienia]' }}</td><td>{{ $row['decision'] ?: '[do uzupełnienia]' }}</td><td>{{ $row['document'] ?: '[do uzupełnienia]' }}</td></tr>@endforeach</table>
<h2>6. Dokumenty powiązane i aktualizacja</h2><p>D-EnMS-ZAK-01 — Zakres systemu · D-EnMS-RYZ-01 — Rejestr ryzyk i szans · D-EnMS-CEL-01 — Cele energetyczne · Protokół Przeglądu Zarządzania.</p><p>Dokument podlega przeglądowi co najmniej raz w roku oraz przy istotnej zmianie otoczenia organizacji.</p>
<div class="foot">Wygenerowano {{ now()->format('d.m.Y H:i') }} · {{ $generatedBy->name }} · dokument roboczy EnMS</div>
</body></html>
