@extends('layouts.app')
@section('page-title',$audit->title)
@push('styles')
<style>
.aw-head{display:flex;justify-content:space-between;gap:16px;margin-bottom:18px}.aw-head h1{font-size:24px;margin:3px 0}.aw-meta{display:flex;gap:14px;flex-wrap:wrap;color:#65736b;font-size:12px}.aw-badge{display:inline-flex;padding:5px 9px;border-radius:20px;background:#eaf4ef;color:var(--green);font-size:11px;font-weight:800}.aw-tabs{display:flex;overflow:auto;border-bottom:2px solid #dedbd3}.aw-tab{border:0;background:transparent;padding:12px 14px;font:700 12px Manrope;color:#69766e;white-space:nowrap;cursor:pointer;border-bottom:2px solid transparent;margin-bottom:-2px}.aw-tab.active{color:var(--green);border-color:var(--green)}.aw-pane{display:none;padding-top:17px}.aw-pane.active{display:block}.aw-card{background:#fff;border:1px solid #e3dfd7;border-radius:11px;padding:18px;margin-bottom:14px}.aw-card h2{font-size:15px;margin-bottom:13px}.aw-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:11px}.aw-field{display:flex;flex-direction:column;gap:5px}.aw-field.wide{grid-column:span 2}.aw-field.full{grid-column:1/-1}.aw-field label{font-size:10px;font-weight:800;color:#56635b}.aw-input{border:1px solid #d7d2c8;border-radius:7px;padding:9px 10px;font:12px Manrope;background:#fff}.aw-btn{border:0;border-radius:7px;background:var(--green);color:#fff;padding:9px 12px;font:700 12px Manrope;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;gap:5px}.aw-btn.soft{background:#eaf4ef;color:var(--green)}.aw-btn.red{background:#b91c1c}.aw-actions{display:flex;justify-content:flex-end;gap:7px;margin-bottom:12px}.aw-table{width:100%;border-collapse:collapse}.aw-table th,.aw-table td{text-align:left;padding:10px;border-bottom:1px solid #eee;font-size:11px}.aw-table th{background:#faf9f5;color:#738078;text-transform:uppercase;font-size:9px}.aw-empty{text-align:center;padding:28px;color:#7b8780}.aw-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:14px}.aw-kpi{background:#fff;border:1px solid #e3dfd7;border-radius:10px;padding:14px}.aw-kpi strong{display:block;font-size:19px;color:var(--green)}.aw-form{border-top:1px solid #eee;margin-top:12px;padding-top:13px}.aw-modal{display:none;position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:2000;align-items:center;justify-content:center;padding:16px}.aw-modal.open{display:flex}.aw-modal-box{background:#fff;border-radius:13px;padding:20px;width:min(760px,100%);max-height:90vh;overflow:auto}@media(max-width:850px){.aw-grid{grid-template-columns:1fr 1fr}.aw-field.wide{grid-column:auto}.aw-kpis{grid-template-columns:1fr}}@media(max-width:550px){.aw-grid{grid-template-columns:1fr}.aw-field.full{grid-column:auto}}
</style>
@endpush
@section('content')
@php
    $statusLabels = ['draft' => 'Roboczy', 'in_progress' => 'W trakcie', 'done' => 'Zakończony', 'cancelled' => 'Anulowany'];
    $income = (float) $audit->financialEntries->where('type', 'invoice')->sum('amount');
    $cost = (float) $audit->financialEntries->where('type', 'cost')->sum('amount');
@endphp
<a href="{{route('companies.show',$audit->company)}}" style="color:var(--green);font-size:12px;font-weight:700;text-decoration:none"><i class="ti ti-arrow-left"></i> Karta klienta</a>
<div class="aw-head"><div><small style="font-weight:800;color:var(--green)">{{$audit->number}}</small><h1>{{$audit->title}}</h1><div class="aw-meta"><span><i class="ti ti-building"></i> {{$audit->company->name}}</span><span><i class="ti ti-user-star"></i> {{$audit->manager?->name??'Brak kierownika'}}</span><span><i class="ti ti-calendar"></i> {{$audit->start_date?->format('d.m.Y')??'—'}} – {{$audit->end_date?->format('d.m.Y')??'—'}}</span></div></div><span class="aw-badge">{{$statusLabels[$audit->status]??$audit->status}}</span></div>
@if(session('success'))<div style="padding:11px 14px;background:#eaf7ee;color:#176139;border-radius:8px;margin-bottom:14px">{{session('success')}}</div>@endif
@if($errors->any())<div style="padding:11px 14px;background:#fff0f0;color:#991b1b;border-radius:8px;margin-bottom:14px">{{$errors->first()}}</div>@endif
<nav class="aw-tabs">@foreach(['overview'=>'Podgląd','schedule'=>'Harmonogram i zadania','finances'=>'Finanse','documents'=>'Dokumenty','surveys'=>'Ankiety Audytowe','passports'=>'Paszporty Energetyczne'] as $id=>$label)<button class="aw-tab {{$loop->first?'active':''}}" onclick="showAuditTab('{{$id}}',this)">{{$label}}</button>@endforeach</nav>

<section id="aw-overview" class="aw-pane active"><div class="aw-card"><h2>Dane audytu</h2><form method="POST" action="{{route('audits.update',$audit)}}">@csrf @method('PUT')<div class="aw-grid"><div class="aw-field"><label>Numer</label><input class="aw-input" name="number" value="{{$audit->number}}" @disabled(!$canManage) required></div><div class="aw-field wide"><label>Nazwa</label><input class="aw-input" name="title" value="{{$audit->title}}" @disabled(!$canManage) required></div><div class="aw-field"><label>Status</label><select class="aw-input" name="status" @disabled(!$canManage)>@foreach($statusLabels as $value=>$label)<option value="{{$value}}" @selected($audit->status===$value)>{{$label}}</option>@endforeach</select></div><div class="aw-field"><label>Kierownik</label><select class="aw-input" name="manager_id" @disabled(!$canManage)>@foreach($users as $user)<option value="{{$user->id}}" @selected($audit->manager_id===$user->id)>{{$user->name}}</option>@endforeach</select></div><div class="aw-field"><label>Start</label><input class="aw-input" type="date" name="start_date" value="{{$audit->start_date?->format('Y-m-d')}}" @disabled(!$canManage)></div><div class="aw-field"><label>Koniec</label><input class="aw-input" type="date" name="end_date" value="{{$audit->end_date?->format('Y-m-d')}}" @disabled(!$canManage)></div><div class="aw-field"><label>Wartość netto</label><input class="aw-input" type="number" step="0.01" name="contract_value" value="{{$audit->contract_value}}" @disabled(!$canManage)></div><div class="aw-field full"><label>Opis</label><textarea class="aw-input" name="description" @disabled(!$canManage)>{{$audit->description}}</textarea></div></div>@if($canManage)<div class="aw-actions" style="margin-top:12px"><button class="aw-btn">Zapisz dane audytu</button></div>@endif</form></div><div class="aw-card"><h2>Zespół audytu</h2><div style="display:flex;gap:7px;flex-wrap:wrap">@foreach($audit->members as $member)<span class="aw-badge">{{$member->name}}</span>@endforeach</div></div></section>

<section id="aw-schedule" class="aw-pane">@if($canManage)<div class="aw-actions"><button class="aw-btn" onclick="openAwModal('task-modal')"><i class="ti ti-plus"></i> Dodaj zadanie</button></div>@endif<div class="aw-card"><h2>Harmonogram i zadania</h2>@if($audit->tasks->isEmpty())<div class="aw-empty">Brak zadań audytowych.</div>@else<table class="aw-table"><thead><tr><th>Zadanie</th><th>Osoba</th><th>Termin</th><th>Postęp</th><th>Status</th><th></th></tr></thead><tbody>@foreach($audit->tasks as $task)<tr><td><strong>{{$task->title}}</strong><br><small>{{$task->description}}</small></td><td>{{$task->assignedUser?->name??'—'}}</td><td>{{$task->start_date?->format('d.m.Y')}} – {{$task->due_date?->format('d.m.Y')}}</td><td>{{$task->progress}}%</td><td>{{$task->status}}</td><td>@if($canManage)<form method="POST" action="{{route('audits.tasks.destroy',[$audit,$task])}}">@csrf @method('DELETE')<button class="aw-btn red">×</button></form>@endif</td></tr>@endforeach</tbody></table>@endif</div></section>

<section id="aw-finances" class="aw-pane"><div class="aw-kpis"><div class="aw-kpi"><span>Faktury</span><strong>{{number_format($income,2,',',' ')}} zł</strong></div><div class="aw-kpi"><span>Koszty</span><strong>{{number_format($cost,2,',',' ')}} zł</strong></div><div class="aw-kpi"><span>Wynik</span><strong>{{number_format($income-$cost,2,',',' ')}} zł</strong></div></div>@if($canManage)<div class="aw-actions"><button class="aw-btn" onclick="openAwModal('finance-modal')"><i class="ti ti-plus"></i> Dodaj pozycję</button></div>@endif<div class="aw-card"><table class="aw-table"><thead><tr><th>Data</th><th>Typ</th><th>Nazwa</th><th>Status</th><th>Kwota</th><th></th></tr></thead><tbody>@forelse($audit->financialEntries as $entry)<tr><td>{{$entry->entry_date->format('d.m.Y')}}</td><td>{{$entry->type==='invoice'?'Faktura':'Koszt'}}</td><td>{{$entry->name}}<br><small>{{$entry->document_number}}</small></td><td>{{$entry->status}}</td><td>{{number_format((float)$entry->amount,2,',',' ')}} zł</td><td>@if($canManage)<form method="POST" action="{{route('audits.finances.destroy',[$audit,$entry])}}">@csrf @method('DELETE')<button class="aw-btn red">×</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="aw-empty">Brak pozycji finansowych.</td></tr>@endforelse</tbody></table></div></section>

<section id="aw-documents" class="aw-pane">@if($canManage)<div class="aw-card"><h2>Dodaj dokument audytu</h2><form method="POST" enctype="multipart/form-data" action="{{route('audits.documents.store',$audit)}}">@csrf<input type="file" name="file" required> <button class="aw-btn">Wgraj dokument</button></form></div>@endif<div class="aw-card"><table class="aw-table"><thead><tr><th>Plik</th><th>Rozmiar</th><th>Dodał</th><th>Data</th><th></th></tr></thead><tbody>@forelse($audit->documents as $document)<tr><td><a href="{{route('audits.documents.download',[$audit,$document])}}">{{$document->original_filename}}</a></td><td>{{$document->formattedSize()}}</td><td>{{$document->uploader?->name??'System'}}</td><td>{{$document->created_at->format('d.m.Y H:i')}}</td><td>@if($canManage)<form method="POST" action="{{route('audits.documents.destroy',[$audit,$document])}}">@csrf @method('DELETE')<button class="aw-btn red">Usuń</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="aw-empty">Brak dokumentów.</td></tr>@endforelse</tbody></table></div></section>

<section id="aw-surveys" class="aw-pane">@if($canManage)<div class="aw-actions"><button class="aw-btn" onclick="openAwModal('survey-modal')"><i class="ti ti-plus"></i> Dodaj ankietę</button></div>@endif<div class="aw-card"><h2>Ankiety Audytowe</h2><table class="aw-table"><thead><tr><th>Nazwa</th><th>Status</th><th>Notatki</th><th></th></tr></thead><tbody>@forelse($audit->surveys as $survey)<tr><td><strong>{{$survey->title}}</strong></td><td>{{['draft'=>'Robocza','ready'=>'Gotowa','completed'=>'Wypełniona'][$survey->status]??$survey->status}}</td><td>{{$survey->notes}}</td><td>@if($canManage)<form method="POST" action="{{route('audits.surveys.destroy',[$audit,$survey])}}">@csrf @method('DELETE')<button class="aw-btn red">Usuń</button></form>@endif</td></tr>@empty<tr><td colspan="4" class="aw-empty">Dodaj pierwszą ankietę dla tego audytu.</td></tr>@endforelse</tbody></table></div></section>

<section id="aw-passports" class="aw-pane">@if($canManage)<div class="aw-actions"><button class="aw-btn" onclick="openAwModal('passport-modal')"><i class="ti ti-plus"></i> Dodaj paszport</button></div>@endif<div class="aw-card"><h2>Paszporty Energetyczne</h2><table class="aw-table"><thead><tr><th>Nazwa</th><th>Szablon</th><th>ID urządzenia</th><th>Status</th><th></th></tr></thead><tbody>@forelse($audit->energyPassports as $passport)<tr><td><strong>{{$passport->name}}</strong></td><td>{{$passport->template?->name}}</td><td>{{$passport->asset_identifier??'—'}}</td><td>{{$passport->status}}</td><td><a class="aw-btn soft" href="{{route('energy-passports.edit',$passport)}}">Otwórz</a></td></tr>@empty<tr><td colspan="5" class="aw-empty">Brak paszportów przypisanych do audytu.</td></tr>@endforelse</tbody></table></div></section>

@if($canManage)
<div id="task-modal" class="aw-modal"><div class="aw-modal-box"><h2>Nowe zadanie audytowe</h2><form method="POST" action="{{route('audits.tasks.store',$audit)}}">@csrf<div class="aw-grid"><div class="aw-field full"><label>Nazwa</label><input class="aw-input" name="title" required></div><div class="aw-field"><label>Start</label><input class="aw-input" type="date" name="start_date" required></div><div class="aw-field"><label>Koniec</label><input class="aw-input" type="date" name="due_date" required></div><div class="aw-field"><label>Osoba</label><select class="aw-input" name="assigned_to"><option value="">Nieprzypisane</option>@foreach($audit->members as $member)<option value="{{$member->id}}">{{$member->name}}</option>@endforeach</select></div><div class="aw-field"><label>Priorytet</label><select class="aw-input" name="priority"><option value="low">Niski</option><option value="medium" selected>Średni</option><option value="high">Wysoki</option></select></div><input type="hidden" name="status" value="todo"><input type="hidden" name="progress" value="0"><div class="aw-field full"><label>Opis</label><textarea class="aw-input" name="description"></textarea></div></div><div class="aw-actions"><button type="button" class="aw-btn soft" onclick="closeAwModal('task-modal')">Anuluj</button><button class="aw-btn">Dodaj</button></div></form></div></div>
<div id="finance-modal" class="aw-modal"><div class="aw-modal-box"><h2>Nowa pozycja finansowa</h2><form method="POST" action="{{route('audits.finances.store',$audit)}}">@csrf<div class="aw-grid"><div class="aw-field"><label>Typ</label><select class="aw-input" name="type"><option value="invoice">Faktura</option><option value="cost">Koszt</option></select></div><div class="aw-field wide"><label>Nazwa</label><input class="aw-input" name="name" required></div><div class="aw-field"><label>Numer dokumentu</label><input class="aw-input" name="document_number"></div><div class="aw-field"><label>Data</label><input class="aw-input" type="date" name="entry_date" required></div><div class="aw-field"><label>Kwota</label><input class="aw-input" type="number" step="0.01" min="0" name="amount" required></div><div class="aw-field"><label>Status</label><select class="aw-input" name="status"><option value="planned">Planowana</option><option value="issued">Wystawiona / zaksięgowana</option><option value="paid">Opłacona</option></select></div></div><div class="aw-actions"><button type="button" class="aw-btn soft" onclick="closeAwModal('finance-modal')">Anuluj</button><button class="aw-btn">Dodaj</button></div></form></div></div>
<div id="survey-modal" class="aw-modal"><div class="aw-modal-box"><h2>Nowa ankieta audytowa</h2><form method="POST" action="{{route('audits.surveys.store',$audit)}}">@csrf<div class="aw-field"><label>Typ audytu</label><select class="aw-input" name="audit_type_id" required><option value="">Wybierz typ audytu</option>@foreach($auditTypes as $auditType)<option value="{{$auditType->id}}">{{$auditType->name}}</option>@endforeach</select>@if($auditTypes->isEmpty())<small>Brak dostępnych typów audytu. Najpierw dodaj typ w ustawieniach audytów.</small>@endif</div><div class="aw-field"><label>Status</label><select class="aw-input" name="status"><option value="draft">Robocza</option><option value="ready">Gotowa</option><option value="completed">Wypełniona</option></select></div><div class="aw-field"><label>Notatki</label><textarea class="aw-input" name="notes"></textarea></div><div class="aw-actions"><button type="button" class="aw-btn soft" onclick="closeAwModal('survey-modal')">Anuluj</button><button class="aw-btn" @disabled($auditTypes->isEmpty())>Dodaj</button></div></form></div></div>
<div id="passport-modal" class="aw-modal"><div class="aw-modal-box"><h2>Nowy paszport energetyczny</h2><form method="POST" action="{{route('audits.passports.store',$audit)}}">@csrf<div class="aw-field"><label>Szablon z biblioteki</label><select class="aw-input" name="template_id" required>@foreach($passportTemplates as $template)<option value="{{$template->id}}">{{$template->name}} · {{$template->category}}</option>@endforeach</select></div><div class="aw-field"><label>Nazwa paszportu</label><input class="aw-input" name="name" required></div><div class="aw-grid"><div class="aw-field wide"><label>ID urządzenia</label><input class="aw-input" name="asset_identifier"></div><div class="aw-field wide"><label>Lokalizacja</label><input class="aw-input" name="location"></div></div><div class="aw-actions"><button type="button" class="aw-btn soft" onclick="closeAwModal('passport-modal')">Anuluj</button><button class="aw-btn">Dodaj i uzupełnij</button></div></form></div></div>
@endif
@endsection
@push('scripts')<script>function showAuditTab(id,button){document.querySelectorAll('.aw-pane').forEach(p=>p.classList.toggle('active',p.id==='aw-'+id));document.querySelectorAll('.aw-tab').forEach(t=>t.classList.remove('active'));button.classList.add('active');history.replaceState(null,'','?tab='+id)}function openAwModal(id){document.getElementById(id)?.classList.add('open')}function closeAwModal(id){document.getElementById(id)?.classList.remove('open')}document.addEventListener('DOMContentLoaded',()=>{const tab=new URLSearchParams(location.search).get('tab');if(tab){const buttons=[...document.querySelectorAll('.aw-tab')];const map=['overview','schedule','finances','documents','surveys','passports'];const i=map.indexOf(tab);if(i>=0)showAuditTab(tab,buttons[i])}});document.querySelectorAll('.aw-modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));</script>@endpush
