@extends('layouts.app')

@section('page-title', $supplier->name)

@section('content')
@php($canEdit = auth()->user()->can('update', $supplier))
<style>
.s-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:18px}.s-kicker{font-size:11px;color:var(--green);font-weight:900;text-transform:uppercase;letter-spacing:.08em}.s-head h1{margin:5px 0;font-size:25px}.s-contact{display:flex;gap:14px;flex-wrap:wrap;color:#69776f;font-size:12px}.s-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.s-card{background:#fff;border:1px solid #e5e1d8;border-radius:11px;padding:18px;margin-bottom:15px}.s-card h2{font-size:15px;margin:0 0 13px}.s-copy{font-size:13px;line-height:1.65;color:#526058;white-space:pre-line}.s-tags{display:flex;gap:7px;flex-wrap:wrap}.s-tag{background:#eef5f0;color:#28543e;border-radius:999px;padding:6px 10px;font-size:11px;font-weight:700}.s-table{width:100%;border-collapse:collapse}.s-table th,.s-table td{text-align:left;padding:10px;border-bottom:1px solid #eee;font-size:12px}.s-table th{font-size:10px;text-transform:uppercase;color:#78827c;background:#fafaf6}.s-table a{color:var(--green);font-weight:800;text-decoration:none}.s-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.s-field{display:flex;flex-direction:column;gap:5px}.s-field label{font-size:10px;font-weight:800;color:#56635c}.s-field input,.s-field textarea{border:1px solid #d8d3c8;border-radius:7px;padding:9px;font:inherit}.full{grid-column:1/-1}.btn{border:0;border-radius:7px;background:var(--green);color:#fff;padding:9px 14px;font-weight:800;cursor:pointer}.btn-soft{background:#edf4ef;color:var(--green)}.back{color:var(--green);text-decoration:none;font-size:12px;font-weight:800}.s-modal{display:none;position:fixed;inset:0;z-index:4000;background:rgba(0,0,0,.48);align-items:center;justify-content:center;padding:16px}.s-modal.open{display:flex}.s-modal-box{width:min(720px,100%);max-height:calc(100vh - 32px);overflow:auto;background:#fff;border-radius:13px;padding:20px;box-shadow:0 20px 60px rgba(0,0,0,.22)}.s-modal-head{display:flex;align-items:flex-start;justify-content:space-between;gap:15px;margin-bottom:16px}.s-modal-head h2{margin:0 0 4px}.s-modal-close{border:0;background:none;font-size:25px;cursor:pointer}@media(max-width:800px){.s-grid,.s-form{grid-template-columns:1fr}.full{grid-column:auto}.s-head{flex-direction:column}}
</style>

<div class="s-head"><div><a class="back" href="{{route('suppliers.index')}}">← Wszyscy dostawcy</a><div class="s-kicker" style="margin-top:12px">Dostawca</div><h1>{{$supplier->name}}</h1><div class="s-contact"><span><i class="ti ti-map-pin"></i> {{$supplier->address}} {{$supplier->city}}</span><span><i class="ti ti-mail"></i> {{$supplier->email ?: '—'}}</span><span><i class="ti ti-phone"></i> {{$supplier->phone ?: '—'}}</span><span>NIP {{$supplier->nip ?: '—'}}</span></div></div>@if($canEdit)<button type="button" class="btn" onclick="document.getElementById('supplier-edit-modal').classList.add('open')"><i class="ti ti-edit"></i> Edytuj dostawcę</button>@endif</div>
@if(session('success'))<div style="padding:11px 14px;background:#ecfdf5;color:#166534;border-radius:8px;margin-bottom:14px">{{session('success')}}</div>@endif

<div class="s-grid">
    <div class="s-card"><h2>Zakres dostaw i usług</h2><div class="s-copy">{{$supplier->supplier_capabilities ?: 'Brak informacji. Uzupełnij profil dostawcy.'}}</div></div>
    <div class="s-card"><h2>Materiały i asortyment</h2><div class="s-tags">@forelse(collect(preg_split('/[,;\r\n]+/', $supplier->supplier_materials ?? '', -1, PREG_SPLIT_NO_EMPTY))->map(fn($item)=>trim($item))->filter() as $material)<span class="s-tag">{{$material}}</span>@empty<span class="s-copy">Brak zapisanych materiałów.</span>@endforelse</div></div>
</div>

<div class="s-card"><h2>Udział w projektach</h2>@if($projects->isEmpty())<div class="s-copy">Dostawca nie został jeszcze przypisany do żadnego projektu.</div>@else<div style="overflow:auto"><table class="s-table"><thead><tr><th>Projekt</th><th>Kierownik</th><th>Dostarczane pozycje</th><th>Wartość szacowana</th></tr></thead><tbody>@foreach($projects as $project)@php($requirements=$supplier->supplierRequirements->where('project_id',$project->id))<tr><td><a href="{{route('projects.show',$project)}}">{{$project->number}} · {{$project->name}}</a></td><td>{{$project->manager?->name ?: '—'}}</td><td>{{$requirements->pluck('name')->join(', ') ?: 'Pozycje finansowe'}}</td><td>{{number_format($requirements->sum(fn($item)=>(float)$item->estimated_cost),2,',',' ')}} zł</td></tr>@endforeach</tbody></table></div>@endif</div>

<div class="s-card"><h2>Materiały i usługi w projektach</h2>@if($supplier->supplierRequirements->isEmpty())<div class="s-copy">Brak przypisanych pozycji.</div>@else<div style="overflow:auto"><table class="s-table"><thead><tr><th>Pozycja</th><th>Projekt</th><th>Ilość</th><th>Status</th><th>Termin</th></tr></thead><tbody>@foreach($supplier->supplierRequirements->sortByDesc('created_at') as $item)<tr><td><strong>{{$item->name}}</strong><br><small>{{$item->type==='material'?'Materiał':'Usługa'}}</small></td><td><a href="{{route('projects.show',$item->project)}}">{{$item->project?->number}}</a></td><td>{{$item->quantity}} {{$item->unit}}</td><td>{{['planned'=>'Planowane','requested'=>'Zapotrzebowanie','ordered'=>'Zamówione','in_progress'=>'W realizacji','purchased'=>'Kupione','cancelled'=>'Anulowane'][$item->status]??$item->status}}</td><td>{{$item->needed_by?->format('d.m.Y') ?: '—'}}</td></tr>@endforeach</tbody></table></div>@endif</div>

@if($canEdit)
<div id="supplier-edit-modal" class="s-modal" onclick="if(event.target===this)this.classList.remove('open')"><div class="s-modal-box"><div class="s-modal-head"><div><h2>Edytuj dostawcę</h2><small style="color:#718078">Zmień dane kontaktowe oraz zakres dostaw.</small></div><button type="button" class="s-modal-close" onclick="document.getElementById('supplier-edit-modal').classList.remove('open')">×</button></div>
@if($errors->supplierEdit->any())<div style="padding:11px 13px;background:#fef2f2;color:#991b1b;border-radius:8px;margin-bottom:14px">{{$errors->supplierEdit->first()}}</div>@endif
<form class="s-form" method="POST" action="{{route('suppliers.update',$supplier)}}">@csrf @method('PUT')<div class="s-field full"><label>Nazwa</label><input name="name" value="{{old('name',$supplier->name)}}" required></div><div class="s-field"><label>NIP</label><input name="nip" value="{{old('nip',$supplier->nip)}}"></div><div class="s-field"><label>Miasto</label><input name="city" value="{{old('city',$supplier->city)}}"></div><div class="s-field"><label>Adres</label><input name="address" value="{{old('address',$supplier->address)}}"></div><div class="s-field"><label>E-mail</label><input type="email" name="email" value="{{old('email',$supplier->email)}}"></div><div class="s-field"><label>Telefon</label><input name="phone" value="{{old('phone',$supplier->phone)}}"></div><div class="s-field full"><label>Co może dostarczać / jakie świadczy usługi</label><textarea name="supplier_capabilities" rows="4" placeholder="Opisz zakres współpracy…">{{old('supplier_capabilities',$supplier->supplier_capabilities)}}</textarea></div><div class="s-field full"><label>Materiały i asortyment (oddziel przecinkami lub nowymi liniami)</label><textarea name="supplier_materials" rows="4" placeholder="Pompy, przewody, armatura…">{{old('supplier_materials',$supplier->supplier_materials)}}</textarea></div><div class="s-field full"><label>Notatki wewnętrzne</label><textarea name="notes" rows="3">{{old('notes',$supplier->notes)}}</textarea></div><div class="full" style="display:flex;justify-content:flex-end;gap:8px"><button type="button" class="btn btn-soft" onclick="document.getElementById('supplier-edit-modal').classList.remove('open')">Anuluj</button><button class="btn">Zapisz zmiany</button></div></form></div></div>
@if($errors->supplierEdit->any())<script>document.addEventListener('DOMContentLoaded',()=>document.getElementById('supplier-edit-modal')?.classList.add('open'));</script>@endif
@endif
@endsection
