@php($editing = isset($inspectionForm))
<div class="cyl-grid">
@foreach(['inspected_at'=>'Data przeglądu', 'next_due_at'=>'Następny termin'] as $field=>$label)
<div><label for="inspection-{{ $field }}">{{ $label }}</label><input id="inspection-{{ $field }}" name="{{ $field }}" type="date" value="{{ old($field, $editing ? $inspectionForm->$field?->format('Y-m-d') : ($field === 'inspected_at' ? today()->format('Y-m-d') : '')) }}" @if($field === 'inspected_at') required max="{{ today()->format('Y-m-d') }}" @endif @error($field) aria-invalid="true" @enderror>@error($field)<small class="cyl-field-error">{{ $message }}</small>@enderror</div>
@endforeach
@foreach(['weight_kg'=>'Waga według ważenia [kg]', 'working_pressure_bar'=>'Ciśnienie robocze [bar]'] as $field=>$label)
<div><label for="inspection-{{ $field }}">{{ $label }}</label><input id="inspection-{{ $field }}" name="{{ $field }}" type="text" inputmode="decimal" value="{{ old($field, $editing ? $inspectionForm->$field : '') }}" @error($field) aria-invalid="true" @enderror>@error($field)<small class="cyl-field-error">{{ $message }}</small>@enderror</div>
@endforeach
<div class="cyl-wide"><label for="inspection-result">Wynik *</label><select id="inspection-result" name="result" required @error('result') aria-invalid="true" @enderror><option value="">Wybierz wynik</option>@foreach($results as $value=>$label)@if($value !== 'further_review' || ($editing && $inspectionForm->result === 'further_review'))<option value="{{ $value }}" @selected(old('result', $editing ? $inspectionForm->result : '') === $value)>{{ $label }}</option>@endif @endforeach</select></div>
<div class="cyl-wide"><label for="inspection-observations">Zakres i uwagi *</label><textarea id="inspection-observations" name="observations" rows="3" maxlength="20000" required @error('observations') aria-invalid="true" @enderror>{{ old('observations', $editing ? $inspectionForm->observations : '') }}</textarea></div>
<div><label for="inspection-video">Film MP4 / MOV (jeden na przegląd)</label>@if($editing && $inspectionForm->videos()->exists())<p class="cyl-muted">Film jest już dołączony. Zachowujemy istniejące nagranie.</p>@else<input id="inspection-video" type="file" name="inspection_video" accept="video/mp4,video/quicktime,.mp4,.mov"><small class="cyl-muted">Z telefonu lub dysku, do {{ number_format(config('cylinders.video_max_kb') / 1024, 0, ',', ' ') }} MB. MOV może wymagać pobrania do odtworzenia.</small>@endif @error('inspection_video')<small class="cyl-field-error">{{ $message }}</small>@enderror</div>
<div><label for="inspection-photos">Zdjęcia JPG / PNG</label><input id="inspection-photos" type="file" name="inspection_photos[]" accept="image/jpeg,image/png,.jpg,.jpeg,.png" multiple><small class="cyl-muted">Aparat lub dysk. Do {{ config('cylinders.photos_per_request') }} zdjęć na zapis, każde do {{ number_format(config('cylinders.photo_max_kb') / 1024, 0, ',', ' ') }} MB i 12 megapikseli. Kolejne zdjęcia możesz dopiąć przez edycję wpisu.</small>@foreach($errors->get('inspection_photos.*') as $messages)@foreach($messages as $message)<small class="cyl-field-error">{{ $message }}</small>@endforeach @endforeach</div>
</div>
