@extends($layout)
@section('title', 'Butla '.$cylinder->serial_number)
@section('page-title', 'Karta butli')
@section('content')
<div class="cyl-module">
@include('cylinders.style')
<div class="cyl-notice cyl-state-{{ $cylinder->conditionStatus() }}">{{ $cylinder->conditionLabel() }}</div>
<div class="cyl-head"><div><h1>Butla {{ $cylinder->serial_number }}</h1><p>{{ $cylinder->company?->name }} @if($cylinder->archived_at)<span class="cyl-badge">Archiwum</span>@endif</p></div><div class="cyl-actions"><a class="cyl-btn" href="{{ route($routePrefix.'index') }}">Wróć do rejestru</a>@if($canManage)<a class="cyl-btn" href="{{ route('cylinders.edit', $cylinder) }}">Edytuj dane</a><form method="post" action="{{ route('cylinders.archive', $cylinder) }}">@csrf @method('PATCH')<input type="hidden" name="archived" value="{{ $cylinder->archived_at ? 0 : 1 }}"><button class="cyl-btn">{{ $cylinder->archived_at ? 'Przywróć' : 'Archiwizuj' }}</button></form>@endif</div></div>
<div class="cyl-card cyl-grid">@foreach(['type'=>'Typ / zastosowanie', 'manufacturer'=>'Producent', 'manufactured_year'=>'Rok produkcji', 'capacity_litres'=>'Pojemność [l]', 'working_pressure_bar'=>'Ciśnienie robocze [bar]'] as $field=>$label)<div><span class="cyl-muted">{{ $label }}</span><div>{{ $cylinder->$field ?? '—' }}</div></div>@endforeach<div class="cyl-wide"><span class="cyl-muted">Uwagi</span><div style="white-space:pre-wrap">{{ $cylinder->notes ?: 'Brak uwag.' }}</div></div></div>
<div class="cyl-card"><h2>Historia przeglądów</h2><p class="cyl-muted">Wpisy opisują wykonane czynności. Nie stanowią automatycznego dopuszczenia urządzenia do eksploatacji.</p><div class="cyl-table"><table><thead><tr><th>Wpis</th><th>Data przeglądu</th><th>Inspektor</th><th>Wynik</th><th>Zakres, pomiary i uwagi</th><th>Następny termin</th></tr></thead><tbody>@forelse($inspections as $inspection)<tr><td>#{{ $inspection->id }}<br><small class="cyl-muted">Zapisano {{ $inspection->created_at->format('d.m.Y H:i') }}</small></td><td>{{ $inspection->inspected_at->format('d.m.Y') }}</td><td>{{ $inspection->inspector_name }}</td><td>{{ $results[$inspection->result] ?? $inspection->result }}</td><td class="cyl-observations">{{ $inspection->observations }}</td><td>{{ $inspection->next_due_at?->format('d.m.Y') ?? 'Nie ustalono' }}</td></tr>@empty<tr><td colspan="6">Nie zapisano jeszcze przeglądów tej butli.</td></tr>@endforelse</tbody></table></div>{{ $inspections->links() }}</div>
<section class="cyl-card"><h2>Filmy butli</h2>
<div class="cyl-videos">@forelse($videos as $video)<article><h3>{{ $video->title }}</h3><video controls playsinline preload="none" aria-label="{{ $video->title }}"><source src="{{ route($routePrefix.'videos.show', [$cylinder, $video]) }}" type="{{ $video->mime_type }}">Twoja przeglądarka nie obsługuje tego filmu.</video><p class="cyl-muted">{{ $video->created_at->format('d.m.Y H:i') }} · {{ \App\Models\Document::formatBytes($video->size) }}</p></article>@empty<p class="cyl-muted">Nie dodano jeszcze filmów.</p>@endforelse</div>{{ $videos->links() }}
@if($canManage && !$cylinder->archived_at)
<details><summary class="cyl-btn">+ Dodaj film</summary><form method="post" enctype="multipart/form-data" action="{{ route('cylinders.videos.store', $cylinder) }}" style="margin-top:16px">@csrf<div class="cyl-grid"><div><label for="video-title">Tytuł filmu</label><input id="video-title" name="title" maxlength="160" required value="{{ old('title') }}"></div><div><label for="video-file">Plik MP4 lub WebM (do 100 MB)</label><input id="video-file" type="file" name="file" accept="video/mp4,video/webm,.mp4,.webm" required></div></div><p class="cyl-muted">Film będzie dostępny inspektorom z uprawnieniami oraz klientowi tej butli. Zajęte miejsce wlicza się do Twojego limitu dokumentów. Dla szerokiej zgodności użyj MP4 z obrazem H.264 i dźwiękiem AAC.</p><button class="cyl-btn cyl-btn-primary">Wgraj film</button></form></details>
@endif</section>
@if($canManage && !$cylinder->archived_at)
<form class="cyl-card" method="post" action="{{ route('cylinders.inspections.store', $cylinder) }}">@csrf<h2>Zapisz przegląd</h2><p class="cyl-muted">Wpis zostanie podpisany Twoim imieniem i nazwiskiem. Nie można go nadpisać ani usunąć; sprostowanie zapisz jako kolejny wpis z odniesieniem do numeru poprzedniego.</p><div class="cyl-grid"><div><label for="inspected_at">Data przeglądu *</label><input id="inspected_at" type="date" name="inspected_at" value="{{ old('inspected_at', date('Y-m-d')) }}" max="{{ date('Y-m-d') }}" required></div><div><label for="next_due_at">Następny termin według właściwej procedury</label><input id="next_due_at" type="date" name="next_due_at" value="{{ old('next_due_at') }}"></div><div class="cyl-wide"><label for="result">Wynik zapisanych czynności *</label><select id="result" name="result" required><option value="">Wybierz wynik</option>@foreach($results as $value=>$label)<option value="{{ $value }}" @selected(old('result') === $value)>{{ $label }}</option>@endforeach</select></div><div class="cyl-wide"><label for="observations">Zakres czynności, wyniki pomiarów z jednostkami, nieprawidłowości i zalecenia *</label><textarea id="observations" name="observations" rows="6" maxlength="20000" required>{{ old('observations') }}</textarea></div></div><p><button class="cyl-btn cyl-btn-primary">Zapisz w historii</button></p></form>
@endif
</div>
@endsection
