@if($canDelegations)
<div id="trip-modal" class="hr-modal"><div class="hr-modal-card"><div class="hr-head"><h2 id="trip-modal-title" style="margin:0">Nowa delegacja</h2><button type="button" class="hr-btn danger" onclick="closeHrModal('trip-modal')">×</button></div>
<form id="trip-form" method="POST" action="{{route('hr.delegations.store')}}">@csrf<input id="trip-method" type="hidden" name="_method" value="PUT" disabled><div class="hr-grid">
 @if($canTeam)<div class="hr-field"><label>Pracownik</label><select id="trip-user-id" name="user_id">@foreach($users as $person)<option value="{{$person->id}}" @selected($selectedUserId===$person->id)>{{$person->name}}</option>@endforeach</select></div>@endif
 <div class="hr-field {{$canTeam?'':'hr-full'}}"><label>Cel wyjazdu *</label><input id="trip-purpose" name="purpose" required maxlength="500"></div>
 <div class="hr-field"><label>Skąd *</label><input id="trip-origin" name="origin" value="{{$defaultOrigin}}" required maxlength="255" autocomplete="off" list="trip-origin-suggestions" placeholder="Adres lub nazwa miejsca"><datalist id="trip-origin-suggestions"></datalist></div><div class="hr-field"><label>Dokąd *</label><input id="trip-destination" name="destination" required maxlength="255" autocomplete="off" list="trip-destination-suggestions" placeholder="Adres lub nazwa miejsca"><datalist id="trip-destination-suggestions"></datalist></div>
 <div class="hr-full"><button type="button" class="hr-btn" onclick="calculateGoogleRoute()"><i class="ti ti-route"></i> Wylicz czas i kilometry z trasy</button><span id="trip-route-status" style="font-size:12px;margin-left:8px;color:#6b7280"></span></div>
 <div class="hr-field"><label>Wyjazd — data i godzina *</label><div class="hr-date-time"><input id="trip-departure-date" type="date" required onchange="syncTripDateTime('departure')"><select id="trip-departure-time" required onchange="syncTripDateTime('departure')">@for($slot=0;$slot<96;$slot++)@php($time=sprintf('%02d:%02d',intdiv($slot,4),($slot%4)*15))<option value="{{$time}}">{{$time}}</option>@endfor</select></div><input id="trip-departure" type="hidden" name="departure_at"></div>
 <div class="hr-field"><label>Wyjazd w drogę powrotną *</label><div class="hr-date-time"><input id="trip-return-departure-date" type="date" required onchange="syncTripDateTime('return-departure')"><select id="trip-return-departure-time" required onchange="syncTripDateTime('return-departure')">@for($slot=0;$slot<96;$slot++)@php($time=sprintf('%02d:%02d',intdiv($slot,4),($slot%4)*15))<option value="{{$time}}">{{$time}}</option>@endfor</select></div><input id="trip-return-departure" type="hidden" name="return_departure_at"></div>
 <div id="trip-route-fields" class="hr-full hr-route-fields" hidden><div class="hr-grid">
  <div class="hr-field"><label>Przyjazd do celu *</label><div class="hr-date-time"><input id="trip-outbound-arrival-date" type="date" required onchange="syncTripDateTime('outbound-arrival');datesToHours('outbound')"><select id="trip-outbound-arrival-time" required onchange="syncTripDateTime('outbound-arrival');datesToHours('outbound')">@for($slot=0;$slot<96;$slot++)@php($time=sprintf('%02d:%02d',intdiv($slot,4),($slot%4)*15))<option value="{{$time}}">{{$time}}</option>@endfor</select></div><input id="trip-outbound-arrival" type="hidden" name="outbound_arrival_at"></div>
  <div class="hr-field"><label>Czas jazdy do celu *</label><div class="hr-duration"><select id="trip-outbound-hours-part" onchange="syncTravelDuration('outbound')">@for($hour=0;$hour<=99;$hour++)<option value="{{$hour}}">{{$hour}} godz.</option>@endfor</select><select id="trip-outbound-minutes-part" onchange="syncTravelDuration('outbound')">@foreach([0,15,30,45] as $minute)<option value="{{$minute}}">{{$minute}} min</option>@endforeach</select></div><input id="trip-outbound-hours" type="hidden" name="outbound_travel_hours"></div>
  <div class="hr-field"><label>Przyjazd z powrotem *</label><div class="hr-date-time"><input id="trip-return-date" type="date" required onchange="syncTripDateTime('return-arrival');datesToHours('return')"><select id="trip-return-time" required onchange="syncTripDateTime('return-arrival');datesToHours('return')">@for($slot=0;$slot<96;$slot++)@php($time=sprintf('%02d:%02d',intdiv($slot,4),($slot%4)*15))<option value="{{$time}}">{{$time}}</option>@endfor</select></div><input id="trip-return" type="hidden" name="return_at"></div>
  <div class="hr-field"><label>Czas jazdy powrotnej *</label><div class="hr-duration"><select id="trip-return-hours-part" onchange="syncTravelDuration('return')">@for($hour=0;$hour<=99;$hour++)<option value="{{$hour}}">{{$hour}} godz.</option>@endfor</select><select id="trip-return-minutes-part" onchange="syncTravelDuration('return')">@foreach([0,15,30,45] as $minute)<option value="{{$minute}}">{{$minute}} min</option>@endforeach</select></div><input id="trip-return-hours" type="hidden" name="return_travel_hours"></div>
  <div class="hr-field hr-full"><label>Łączny przebieg (km)</label><input id="trip-distance" type="number" name="distance_km" min="0" step="0.1" oninput="updateTripSummary()"><small>Wartość wyliczona dla trasy tam i z powrotem; zawsze można ją poprawić ręcznie.</small></div>
 </div></div>
 <div class="hr-field hr-full"><label>Wybierz samochód *</label><select id="trip-vehicle-id" name="vehicle_id" required onchange="chooseHrVehicle(this)"><option value="" disabled selected>Wybierz samochód</option>@foreach($vehicles as $vehicle)<option value="{{$vehicle->id}}" data-type="{{$vehicle->type}}" data-name="{{$vehicle->name}}" data-registration="{{$vehicle->registration_number}}">{{$vehicle->type==='company'?'Służbowy':'Prywatny'}} · {{$vehicle->name}} · {{$vehicle->registration_number}}{{$vehicle->user ? ' · '.$vehicle->user->name : ''}}</option>@endforeach<option value="manual">Inny samochód — wpiszę dane</option></select></div>
 <div id="trip-other-vehicle-fields" class="hr-full hr-grid" hidden><input id="trip-vehicle-type" type="hidden" name="vehicle_type" value="private"><label class="hr-private-car-check"><input id="trip-private-vehicle" type="checkbox" checked onchange="syncManualVehicleType()"><span><strong>Samochód prywatny</strong><small>Nalicz kilometrówkę według stawki HR</small></span></label><div class="hr-field"><label>Nazwa samochodu</label><input id="trip-vehicle-name" name="vehicle_name" maxlength="255"></div>
 <div class="hr-field"><label>Nr rejestracyjny</label><input id="trip-registration" name="registration_number" maxlength="30"></div><label style="font-size:13px;align-self:end;padding-bottom:9px"><input id="trip-remember-vehicle" type="checkbox" name="remember_vehicle" value="1"> Zapamiętaj samochód</label></div>
 <div class="hr-full hr-costs-row"><div class="hr-field"><label>Koszty autostradowe (zł)</label><input id="trip-toll" type="number" name="toll_cost" value="0" min="0" step="0.01" oninput="updateTripSummary()"></div><div class="hr-field"><label>Koszty noclegów (zł)</label><input id="trip-accommodation" type="number" name="accommodation_cost" value="0" min="0" step="0.01" oninput="updateTripSummary()"></div><div class="hr-field"><label>Inne koszty (zł)</label><input id="trip-other-cost" type="number" name="other_cost" value="0" min="0" step="0.01" oninput="updateTripSummary()"></div></div>
 <div class="hr-field hr-full"><label>Notatki</label><textarea id="trip-notes" name="notes" rows="3" maxlength="3000"></textarea></div>
 <input id="trip-km-rate" type="hidden" name="km_rate" value="{{$defaultKmRate}}"><input id="trip-diet-rate" type="hidden" name="diet_rate" value="{{$defaultDietRate}}">
 <div class="hr-full hr-rate-info"><i class="ti ti-info-circle"></i> Stawka za km: <strong>{{number_format($defaultKmRate,4,',',' ')}} zł</strong> (tylko samochód prywatny) · pełna dieta: <strong>{{number_format($defaultDietRate,2,',',' ')}} zł</strong></div>
 <div class="hr-full" id="trip-calculation" style="padding:12px;background:#eef6f1;border-radius:8px;color:var(--green);font-size:13px">Uzupełnij terminy i stawki, aby zobaczyć podsumowanie.</div>
 <div id="trip-route-map-wrap" class="hr-full hr-route-map" hidden><strong>Mapa przejazdu</strong><iframe id="trip-route-map" title="Mapa przejazdu delegacji" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe></div>
</div><div class="hr-actions" style="justify-content:flex-end;margin-top:18px"><button type="button" class="hr-btn danger" onclick="closeHrModal('trip-modal')">Anuluj</button><button class="hr-btn">Zapisz delegację</button></div></form></div></div>
@endif

@if($canManageHrSettings)
<div id="hr-settings-modal" class="hr-modal"><div class="hr-modal-card" style="max-width:560px"><div class="hr-head"><h2 style="margin:0">Ustawienia HR</h2><button type="button" class="hr-btn danger" onclick="closeHrModal('hr-settings-modal')">×</button></div>
<form method="POST" action="{{route('hr.settings.update')}}">@csrf @method('PUT')<div class="hr-grid"><div class="hr-field"><label>Stawka za km dla auta prywatnego (zł)</label><input type="number" name="hr_km_rate" value="{{$defaultKmRate}}" min="0" max="9999" step="0.0001" required></div><div class="hr-field"><label>Stawka pełnej diety (zł)</label><input type="number" name="hr_diet_rate" value="{{$defaultDietRate}}" min="0" max="9999" step="0.01" required></div></div><div class="hr-actions" style="justify-content:flex-end;margin-top:18px"><button type="button" class="hr-btn danger" onclick="closeHrModal('hr-settings-modal')">Anuluj</button><button class="hr-btn">Zapisz ustawienia</button></div></form></div></div>
@endif

@if($canAttendance)
<div id="attendance-modal" class="hr-modal"><div class="hr-modal-card" style="max-width:620px"><div class="hr-head"><h2 style="margin:0">Wpis obecności</h2><button type="button" class="hr-btn danger" onclick="closeHrModal('attendance-modal')">×</button></div><form method="POST" action="{{route('hr.attendance.store')}}">@csrf<div class="hr-grid">
 @if($canTeam)<div class="hr-field hr-full"><label>Pracownik</label><select name="user_id">@foreach($users as $person)<option value="{{$person->id}}" @selected($selectedUserId===$person->id)>{{$person->name}}</option>@endforeach</select></div>@endif
 <div class="hr-field"><label>Data *</label><input type="date" name="work_date" value="{{now()->toDateString()}}" required></div><div class="hr-field"><label>Status *</label><select name="status"><option value="present">Obecny</option><option value="remote">Praca zdalna</option><option value="leave">Urlop</option><option value="sick">Chorobowe</option><option value="absent">Nieobecny</option></select></div>
 <div class="hr-field"><label>Od godziny</label><input type="time" name="started_at"></div><div class="hr-field"><label>Do godziny</label><input type="time" name="finished_at"></div><div class="hr-field hr-full"><label>Notatki</label><textarea name="notes" rows="3"></textarea></div>
 </div><div class="hr-actions" style="justify-content:flex-end;margin-top:18px"><button type="button" class="hr-btn danger" onclick="closeHrModal('attendance-modal')">Anuluj</button><button class="hr-btn">Zapisz wpis</button></div></form></div></div>
@endif

@if($canDelegations)
<div id="vehicle-modal" class="hr-modal"><div class="hr-modal-card" style="max-width:620px"><div class="hr-head"><h2 style="margin:0">Nowy samochód</h2><button type="button" class="hr-btn danger" onclick="closeHrModal('vehicle-modal')">×</button></div><form method="POST" action="{{route('hr.vehicles.store')}}">@csrf<div class="hr-grid">
 <div class="hr-field"><label>Rodzaj *</label><select name="type"><option value="private">Prywatny</option>@if($canTeam)<option value="company">Służbowy</option>@endif</select></div>
 @if($canTeam)<div class="hr-field"><label>Właściciel prywatnego auta</label><select name="user_id"><option value="">— ja / samochód firmowy —</option>@foreach($users as $person)<option value="{{$person->id}}">{{$person->name}}</option>@endforeach</select></div>@endif
 <div class="hr-field"><label>Nazwa *</label><input name="name" required placeholder="np. Auto Sławka"></div><div class="hr-field"><label>Marka i model</label><input name="make_model" placeholder="np. Skoda Octavia"></div><div class="hr-field hr-full"><label>Nr rejestracyjny *</label><input name="registration_number" required maxlength="30"></div>
 </div><div class="hr-actions" style="justify-content:flex-end;margin-top:18px"><button type="button" class="hr-btn danger" onclick="closeHrModal('vehicle-modal')">Anuluj</button><button class="hr-btn">Zapisz samochód</button></div></form></div></div>
@endif
