@if($canDelegations)
<div id="trip-modal" class="hr-modal"><div class="hr-modal-card"><div class="hr-head"><h2 id="trip-modal-title" style="margin:0">Nowa delegacja</h2><button type="button" class="hr-btn danger" onclick="closeHrModal('trip-modal')">×</button></div>
<form id="trip-form" method="POST" action="{{route('hr.delegations.store')}}">@csrf<input id="trip-method" type="hidden" name="_method" value="PUT" disabled><div class="hr-grid">
 @if($canTeam)<div class="hr-field"><label>Pracownik</label><select id="trip-user-id" name="user_id">@foreach($users as $person)<option value="{{$person->id}}" @selected($selectedUserId===$person->id)>{{$person->name}}</option>@endforeach</select></div>@endif
 <div class="hr-field {{$canTeam?'':'hr-full'}}"><label>Cel wyjazdu *</label><input id="trip-purpose" name="purpose" required maxlength="500"></div>
 <div class="hr-field"><label>Stawka za km (zł)</label><input id="trip-km-rate" type="number" name="km_rate" value="{{$defaultKmRate}}" min="0" step="0.0001" required oninput="updateTripSummary()"></div><div class="hr-field"><label>Stawka pełnej diety (zł)</label><input id="trip-diet-rate" type="number" name="diet_rate" value="{{$defaultDietRate}}" min="0" step="0.01" required oninput="updateTripSummary()"></div>
 <div class="hr-field"><label>Skąd *</label><input id="trip-origin" name="origin" value="{{$defaultOrigin}}" required maxlength="255" autocomplete="off" placeholder="Zacznij wpisywać adres lub nazwę miejsca"></div><div class="hr-field"><label>Dokąd *</label><input id="trip-destination" name="destination" required maxlength="255" autocomplete="off" placeholder="Zacznij wpisywać adres lub nazwę miejsca"></div>
 <div class="hr-full"><button type="button" class="hr-btn" onclick="calculateGoogleRoute()"><i class="ti ti-route"></i> Wylicz czas i kilometry z trasy</button><span id="trip-route-status" style="font-size:12px;margin-left:8px;color:#6b7280"></span></div>
 <div class="hr-field"><label>Wyjazd — data i godzina *</label><input id="trip-departure" type="datetime-local" name="departure_at" required onchange="datesToHours('outbound')"></div><div class="hr-field"><label>Wyjazd w drogę powrotną *</label><input id="trip-return-departure" type="datetime-local" name="return_departure_at" required onchange="datesToHours('return')"></div>
 <div id="trip-route-fields" class="hr-full hr-route-fields" hidden><div class="hr-grid">
  <div class="hr-field"><label>Przyjazd do celu — data i godzina *</label><input id="trip-outbound-arrival" type="datetime-local" name="outbound_arrival_at" required onchange="datesToHours('outbound')"></div><div class="hr-field"><label>Czas jazdy do celu (godz.) *</label><input id="trip-outbound-hours" type="number" name="outbound_travel_hours" min="0" max="999.99" step="0.01" required oninput="hoursToArrival('outbound')"></div>
  <div class="hr-field"><label>Przyjazd z powrotem *</label><input id="trip-return" type="datetime-local" name="return_at" required onchange="datesToHours('return')"></div><div class="hr-field"><label>Czas jazdy powrotnej (godz.) *</label><input id="trip-return-hours" type="number" name="return_travel_hours" min="0" max="999.99" step="0.01" required oninput="hoursToArrival('return')"></div>
  <div class="hr-field hr-full"><label>Łączny przebieg (km)</label><input id="trip-distance" type="number" name="distance_km" min="0" step="0.1" oninput="updateTripSummary()"><small>Wartość wyliczona dla trasy tam i z powrotem; zawsze można ją poprawić ręcznie.</small></div>
 </div></div>
 <div class="hr-field"><label>Koszty autostradowe (zł)</label><input id="trip-toll" type="number" name="toll_cost" value="0" min="0" step="0.01" oninput="updateTripSummary()"></div>
 <div class="hr-field"><label>Koszty noclegów (zł)</label><input id="trip-accommodation" type="number" name="accommodation_cost" value="0" min="0" step="0.01" oninput="updateTripSummary()"></div><div class="hr-field"><label>Inne koszty (zł)</label><input id="trip-other-cost" type="number" name="other_cost" value="0" min="0" step="0.01" oninput="updateTripSummary()"></div>
 <div class="hr-field hr-full"><label>Wybierz samochód</label><select id="trip-vehicle-id" name="vehicle_id" onchange="chooseHrVehicle(this)"><option value="">— wpiszę dane poniżej —</option>@foreach($vehicles as $vehicle)<option value="{{$vehicle->id}}" data-type="{{$vehicle->type}}" data-name="{{$vehicle->name}}" data-registration="{{$vehicle->registration_number}}">{{$vehicle->type==='company'?'Służbowy':'Prywatny'}} · {{$vehicle->name}} · {{$vehicle->registration_number}}{{$vehicle->user ? ' · '.$vehicle->user->name : ''}}</option>@endforeach</select></div>
 <div class="hr-field"><label>Rodzaj samochodu *</label><select id="trip-vehicle-type" name="vehicle_type" required><option value="private">Prywatny</option><option value="company">Służbowy</option></select></div><div class="hr-field"><label>Nazwa samochodu</label><input id="trip-vehicle-name" name="vehicle_name" maxlength="255"></div>
 <div class="hr-field"><label>Nr rejestracyjny</label><input id="trip-registration" name="registration_number" maxlength="30"></div><label style="font-size:13px;align-self:end;padding-bottom:9px"><input id="trip-remember-vehicle" type="checkbox" name="remember_vehicle" value="1"> Zapamiętaj samochód</label>
 <div class="hr-field hr-full"><label>Notatki</label><textarea id="trip-notes" name="notes" rows="3" maxlength="3000"></textarea></div>
 <div class="hr-full" id="trip-calculation" style="padding:12px;background:#eef6f1;border-radius:8px;color:var(--green);font-size:13px">Uzupełnij terminy i stawki, aby zobaczyć podsumowanie.</div>
 <div id="trip-route-map-wrap" class="hr-full hr-route-map" hidden><strong>Mapa przejazdu</strong><iframe id="trip-route-map" title="Mapa przejazdu delegacji" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe></div>
</div><div class="hr-actions" style="justify-content:flex-end;margin-top:18px"><button type="button" class="hr-btn danger" onclick="closeHrModal('trip-modal')">Anuluj</button><button class="hr-btn">Zapisz delegację</button></div></form></div></div>
@endif

@if($canAttendance)
<div id="attendance-modal" class="hr-modal"><div class="hr-modal-card" style="max-width:620px"><div class="hr-head"><h2 style="margin:0">Wpis obecności</h2><button type="button" class="hr-btn danger" onclick="closeHrModal('attendance-modal')">×</button></div><form method="POST" action="{{route('hr.attendance.store')}}">@csrf<div class="hr-grid">
 @if($canTeam)<div class="hr-field hr-full"><label>Pracownik</label><select name="user_id">@foreach($users as $person)<option value="{{$person->id}}" @selected($selectedUserId===$person->id)>{{$person->name}}</option>@endforeach</select></div>@endif
 <div class="hr-field"><label>Data *</label><input type="date" name="work_date" value="{{now()->toDateString()}}" required></div><div class="hr-field"><label>Status *</label><select name="status"><option value="present">Obecny</option><option value="remote">Praca zdalna</option><option value="leave">Urlop</option><option value="sick">Chorobowe</option><option value="absent">Nieobecny</option></select></div>
 <div class="hr-field"><label>Od godziny</label><input type="time" name="started_at"></div><div class="hr-field"><label>Do godziny</label><input type="time" name="finished_at"></div><div class="hr-field hr-full"><label>Notatki</label><textarea name="notes" rows="3"></textarea></div>
 </div><div class="hr-actions" style="justify-content:flex-end;margin-top:18px"><button type="button" class="hr-btn danger" onclick="closeHrModal('attendance-modal')">Anuluj</button><button class="hr-btn">Zapisz wpis</button></div></form></div></div>
@endif

@if($canDelegations)
<div id="vehicle-modal" class="hr-modal"><div class="hr-modal-card" style="max-width:620px"><div class="hr-head"><h2 style="margin:0">Nowy samochód</h2><button type="button" class="hr-btn danger" onclick="closeHrModal('vehicle-modal')">×</button></div><form method="POST" action="{{route('hr.vehicles.store')}}">@csrf<div class="hr-grid">
 <div class="hr-field"><label>Rodzaj *</label><select name="type"><option value="private">Prywatny</option>@if($canTeam)<option value="company">Służbowy</option>@endif</select></div>
 @if($canTeam)<div class="hr-field"><label>Właściciel prywatnego auta</label><select name="user_id"><option value="">— ja / samochód firmowy —</option>@foreach($users as $person)<option value="{{$person->id}}">{{$person->name}}</option>@endforeach</select></div>@endif
 <div class="hr-field"><label>Nazwa *</label><input name="name" required placeholder="np. Auto Sławka"></div><div class="hr-field"><label>Marka i model</label><input name="make_model" placeholder="np. Skoda Octavia"></div><div class="hr-field hr-full"><label>Nr rejestracyjny *</label><input name="registration_number" required maxlength="30"></div>
 </div><div class="hr-actions" style="justify-content:flex-end;margin-top:18px"><button type="button" class="hr-btn danger" onclick="closeHrModal('vehicle-modal')">Anuluj</button><button class="hr-btn">Zapisz samochód</button></div></form></div></div>
@endif
