@extends('layouts.app')
@section('page-title','Magazyn — '.$document->number)
@section('content')
@include('warehouse._layout')
<div class="wh-card"><span class="wh-eyebrow">{{\App\Models\WarehouseDocument::TYPES[$document->type]}}</span><h2>{{$document->number}}</h2><dl class="wh-details"><div><dt>Data dokumentu</dt><dd>{{$document->document_date->format('d.m.Y')}}</dd></div><div><dt>Zapisał</dt><dd>{{$document->author_name}}</dd></div><div><dt>Zapisano w systemie</dt><dd>{{$document->created_at->format('d.m.Y H:i:s')}}</dd></div><div><dt>Projekt</dt><dd>{{$document->project_label ?: '—'}}</dd></div><div><dt>Dostawca</dt><dd>{{$document->supplier_name ?: '—'}}</dd></div><div><dt>Odniesienie / faktura</dt><dd>{{$document->reference ?: '—'}}</dd></div></dl><p class="wh-description">{{$document->notes}}</p></div>
<div class="wh-table-wrap"><table class="wh-table"><thead><tr><th>Kod</th><th>Nazwa</th><th>Jednostka</th><th>Stan przed</th><th>Zmiana</th><th>Stan po</th><th>Cena netto PLN</th><th>Wartość zmiany netto PLN</th></tr></thead><tbody>
@foreach($document->lines as $line)<tr><td>{{$line->sku}}</td><td><a href="{{route('warehouse.items.show',$line->warehouse_item_id)}}">{{$line->name}}</a></td><td>{{$line->unit}}</td>@foreach(['quantity_before','quantity_change','quantity_after'] as $field)<td class="num" data-sort-value="{{$line->$field}}">{{number_format((float)$line->$field,3,',',' ')}}</td>@endforeach<td class="num" data-sort-value="{{$line->unit_cost}}">{{number_format((float)$line->unit_cost,2,',',' ')}}</td><td class="num" data-sort-value="{{(float)$line->quantity_change*(float)$line->unit_cost}}">{{number_format((float)$line->quantity_change*(float)$line->unit_cost,2,',',' ')}}</td></tr>@endforeach
</tbody></table></div><div class="wh-info">Dokument jest trwałym zapisem operacji. Nie edytujemy ani nie usuwamy zapisanych ruchów. Pomyłkę rozlicz nowym dokumentem z opisem przyczyny i numerem dokumentu źródłowego. Wydanie przypisane do projektu nie tworzy automatycznie kosztu w finansach projektu.</div>
@endsection
