@extends('layouts.app')
@section('page-title','Magazyn')
@section('content')
@include('warehouse._layout')
@php($warehouseFull = auth()->user()->hasRole('superadmin') || auth()->user()->can('system.full_access'))
<div class="wh-stats"><div class="wh-stat"><span>Aktywne pozycje</span><strong>{{$totals->count}}</strong></div><div class="wh-stat"><span>Wartość ewidencyjna netto (PLN)</span><strong>{{number_format((float)$totals->value,2,',',' ')}} zł</strong></div><div class="wh-stat"><span>Na poziomie minimum lub poniżej</span><strong>{{$totals->low}}</strong></div></div>
<div class="wh-actions" style="margin-bottom:16px">@if($warehouseFull || auth()->user()->can('warehouse.manage'))<a class="wh-btn primary" href="{{route('warehouse.items.create')}}">+ Dodaj pozycję</a>@endif<a class="wh-btn" href="{{route('warehouse.export',request()->only('q','category','low','archived'))}}">Eksport CSV (Excel)</a></div>
<form class="wh-filters" method="GET"><div class="wh-field"><label for="wh-q">Szukaj / skanuj kod</label><input id="wh-q" name="q" value="{{request('q')}}" placeholder="Kod, nazwa lub lokalizacja" maxlength="200"></div><div class="wh-field"><label for="wh-category">Kategoria</label><select id="wh-category" name="category"><option value="">Wszystkie</option>@foreach($categories as $category)<option @selected(request('category')===$category)>{{$category}}</option>@endforeach</select></div><label class="wh-check"><input type="checkbox" name="low" value="1" @checked(request()->boolean('low'))> Niski stan</label><label class="wh-check"><input type="checkbox" name="archived" value="1" @checked(request()->boolean('archived'))> Archiwum</label><button class="wh-btn primary">Filtruj</button><a class="wh-btn" href="{{route('warehouse.index')}}">Wyczyść</a></form>
<div class="wh-table-wrap"><table class="wh-table" data-server-sort="sku,name,category,location,unit,quantity,minimum_stock,unit_cost,stock_value"><thead><tr><th>Kod</th><th>Nazwa</th><th>Kategoria</th><th>Lokalizacja</th><th>Jednostka</th><th>Stan</th><th>Minimum</th><th>Cena netto PLN</th><th>Wartość netto PLN</th><th>Akcje</th></tr></thead><tbody>
@forelse($items as $item)<tr><td>{{$item->sku}}</td><td><a href="{{route('warehouse.items.show',$item)}}">{{$item->name}}</a></td><td>{{$item->category ?: '—'}}</td><td>{{$item->location ?: '—'}}</td><td>{{$item->unit}}</td><td class="num" data-sort-value="{{$item->quantity}}"><span class="wh-badge {{(float)$item->quantity <= (float)$item->minimum_stock?'low':''}}">{{number_format((float)$item->quantity,3,',',' ')}}</span></td><td class="num">{{number_format((float)$item->minimum_stock,3,',',' ')}}</td><td class="num">{{number_format((float)$item->unit_cost,2,',',' ')}}</td><td class="num">{{number_format((float)$item->stock_value,2,',',' ')}}</td><td><a class="wh-btn" href="{{route('warehouse.items.show',$item)}}">Otwórz</a></td></tr>@empty<tr><td class="wh-empty" colspan="10">Brak pozycji spełniających kryteria. Dodaj pozycję lub zmień filtry.</td></tr>@endforelse
</tbody></table></div>{{$items->links()}}
<p class="wh-muted">Wartości operacyjne netto w PLN. Cena ewidencyjna to średnia ważona przyjęć, zaokrąglana do grosza; moduł nie zastępuje księgowości. Stan zmienia się wyłącznie przez dokument magazynowy.</p>
@endsection
