<!doctype html><html lang="pl"><head><meta charset="utf-8"><style>@page{margin:32px 38px 44px}body{font-family:DejaVu Sans,sans-serif;font-size:10px;line-height:1.5;color:#243a33}h1{font-size:20px;color:#1a4d3a}h2{font-size:14px;background:#edf3ef;padding:8px;page-break-after:avoid}h3{font-size:11px;page-break-after:avoid}p{white-space:pre-wrap;overflow-wrap:break-word}.header{border-bottom:3px solid #1a4d3a}.header img{max-height:50px;max-width:150px}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1px solid #dce5df;padding:7px;text-align:left;vertical-align:top;word-wrap:break-word}th{background:#edf3ef}thead{display:table-header-group}.footer{position:fixed;bottom:-25px;font-size:8px}.page:after{content:counter(page)}</style></head><body>
<div class="footer">D-EnMS-STR-01 · Strony zainteresowane · <span class="page"></span></div>
<div class="header">@if($review->issuer['logo']??null)<img src="{{$review->issuer['logo']}}" alt="Logo">@else<strong>{{$review->issuer['name']??''}}</strong>@endif<h1>{{$title}}</h1><p>{{$profile->answers['organization.name']['value']??''}} · {{$profile->answers['site.name']['value']??''}}<br>{{$profile->answers['site.address']['value']??''}}</p></div>
<p>Data przeglądu: {{$review->analysis['reviewed_on']}} · Kolejny przegląd: {{$review->analysis['next_review']}}<br>Odpowiedzialny: {{$review->analysis['owner']}}</p>
@if(!$extract)
<h2>Rejestr stron zainteresowanych</h2><table><thead><tr><th style="width:9%">Kod</th><th style="width:16%">Strona</th><th style="width:10%">Typ</th><th style="width:30%">Wymagania i oczekiwania</th><th style="width:9%">Zgodność</th><th style="width:26%">Jak uwzględniono w systemie</th></tr></thead><tbody>@foreach($register as $row)@php($cells=array_map(fn($value)=>mb_str_split((string)$value,450),[$row['kod'],$row['nazwa'],$row['typ'],$row['wymagania'],$row['zgodnosc']==='tak'?'Tak':'Nie',$row['jak']]))@for($chunk=0;$chunk<max(array_map('count',$cells));$chunk++)<tr>@foreach($cells as $cell)<td style="white-space:pre-wrap">{{$cell[$chunk]??''}}</td>@endforeach</tr>@endfor @endforeach</tbody></table>
@foreach($register as $row)@if($row['consultant']['reason']??null)<h3>{{$row['kod']}} · {{$row['nazwa']}}</h3><p>Uzasadnienie oceny zgodności: {{$row['consultant']['reason']}}</p>@endif @endforeach
<h2>Wymagania klimatyczne</h2><p>{{$review->answers['FAKT_KLIMAT_STRONY']==='tak'?'Tak — występują':'Nie — nie stwierdzono'}}<br>{{$review->answers['climate_reason']}}</p>
<h2>Strony odrzucone — uzasadnienia</h2>@foreach($parties as $party)@if($party['visible'] && ($review->answers['parties'][$party['kod']]['decyzja']??'')==='odrzucona')<h3>{{$party['kod']}} · {{$party['nazwa']}}</h3><p>{{$review->answers['parties'][$party['kod']]['powod']}}</p>@endif @endforeach
<h2>Warunki wymagające uzupełnienia danych</h2>@foreach($parties as $party)@if(!$party['visible'] && in_array(null,$party['dependencies'],true))<p>{{$party['kod']}} · {{$party['nazwa']}}: {{$party['warunek']}}</p>@endif @endforeach
@endif
<h2>Wyciąg wymagań zgodności — wejście do 6.1 i 9.1.2</h2><p>Wyciąg obejmuje wyłącznie potwierdzone wymagania zgodności. Ocena ich spełnienia i dowody zgodności są prowadzone odrębnie.</p>
@forelse($review->compliance_register??[] as $row)<h3>{{$row['kod']}} · {{$row['nazwa']}}</h3><p><strong>Wymaganie:</strong><br>{{$row['wymagania']}}</p><p><strong>Podstawa prawna lub umowna:</strong><br>{{$row['consultant']['legal_basis']}}</p><p>Odpowiedzialny: {{$row['consultant']['owner']}}<br>Termin spełnienia: {{$row['consultant']['deadline']??'Nie określono odrębnego terminu'}}<br>Uwzględnienie w systemie: {{$row['jak']}}</p>@empty<p>Nie zidentyfikowano potwierdzonych wymagań zgodności.</p>@endforelse
<h2>Wnioski konsultanta</h2><p>{{$review->analysis['summary']}}</p>
<h2>Zatwierdzenia</h2>@foreach(['client_approval'=>'Klient','auditor_approval'=>'Audytor'] as $field=>$label)<p>{{$label}}: {{$review->$field['name']}} · {{\Carbon\Carbon::parse($review->$field['at'])->format('d.m.Y H:i')}}</p>@endforeach
</body></html>
